examples/tests/valid/resource.w, libs/wingc/src/type_check.rs, tools/hangar/src/__snapshots__/cli.test.ts.snap
This is the bare minimum just to make `init` useful. We still don't have verification that all fields are initialized etc.
See #542 
See #864
```wing
bring cloud;
resource R {
name: str;
init(name: str) {
this.name = name; // This should now work, before `this` was an unknown symbol
}
}
let r = new R("foo");
```
=> fix(compiler): support for `this` in resource/class init

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
Inspired by [CDK for Terraform](https://github.com/hashicorp/terraform-cdk/blob/main/.github/ISSUE_TEMPLATE/bug-report.md), adds a section at the beginning of the issue templates with some community guidelines.
Since we are using a form, this will look like this:
The resulting issue looks like this:
=> chore(repo): community note in issue templates

libs/wingc/src/lib.rs, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/jsii_importer.rs, libs/wingc/src/type_check/symbol_env.rs
All constants for wingsdk resource names are now define in a single place in _lib.rs_. Also use nested lookup function to get these types from the env when needed.
Also in this PR there's a non related fix for correctly handling unknown builtin types in the return value of a closure during parsing. Before this paniced:
```wing
let a = (): Set<str> => {
}
```
Now it report an error:
```
Error at ../../tmp/tmp.w:1:13 | builtin container type 'Set' is not supported yet see https://github.com/winglang/wing/issues/530
```
=> fix(compiler): constants for wingsdk resource names and other cleanups

examples/tests/invalid/resource_access_field_as_method.w, libs/wingc/src/ast.rs, libs/wingc/src/type_check.rs
This PR fixes 2 things:
1. We're changing the error message to be as appears in issue #997.
Note a couple of changes from #997: 
a. We used "at" instead of "declared in" because it makes more sense in different contexts where this diagnostic message appears.
b. We used quotes instead of ticks, since this is the convention on our compiler error messages.
A test for this already exists at: https://github.com/winglang/wing/blob/main/examples/tests/invalid/enums.w 
2. Also fixed a different error where the compiler would panic when we access a field as if it was a method. For example:
```ts
resource SomeResource {
name: str;
init() {
}
}
let x = new SomeResource();
x.name();
```
Added this as a test.
Fixes #997 
*By submitting this pull request, I confirm that my contribution is made under …
=> fix(compiler): diagnostics show the file and line as part of the type name

docs/02-getting-started/05-aws.md
The docs are inconsistent with the current hello wing code.  The code only writes the message to an s3 bucket. I believe this iteration is referring to an earlier version that wrote to a cloudwatch log.
=> fix(docs): update cloudwatch -> s3 to reflect current hello wing code

examples/tests/valid/expressions_string_interpolation.w, libs/wingc/src/parser.rs, tools/hangar/src/__snapshots__/cli.test.ts.snap
When interpolate a string with more than one variable, all variables except the last one are duplicated
I create a simple validation on string parser file to remove the duplicated value
Please review this solution carefully as I do not program in Rust, but when I run the current test with this command
```bash
$ npx nx dev -- wing/examples/tests/valid/expressions_string_interpolation.w
```
the resulting file was created correctly and can be found in the folder
`wing/examples/tests/valid/expressions_string_interpolation.w.out/preflight.js`
Closes #1041 
=> fix(compiler): removing duplicate string when interpolating

.github/workflows/build.yml
The `.jsii` from wingsdk needs to be packaged with the vscode extension.
This works locally because we build wingsdk at the same time, but the vscode build here happens after (and separately from) the wingsdk build.
=> fix: missing wingsdk .jsii manifest in vscode

.github/workflows/build.yml, apps/vscode-wing/.gitignore, apps/vscode-wing/.projenrc.ts, apps/vscode-wing/.vscodeignore, apps/vscode-wing/project.json, apps/vscode-wing/src/extension.ts
https://github.com/winglang/wing/pull/832 moved wingsdk to be a devDep, which no longer included any of its files in the final vscode vsix file. This moves the required `package.json` and `.jsii` to be treated more like the language server binaries instead.
=> fix: missing wingsdk in vscode extension (again)

docs/02-getting-started/02-installation.md
According to https://github.com/winglang/docsite/issues/207 we need to revert the work done on #988 and increase back the scope of the PAT used to fetch Wing from github package registry.
Resolves https://github.com/winglang/docsite/issues/207
=> fix(docs): wrong permissions for private auth token mentioned on getting started guide

docs/02-getting-started/02-installation.md
This arg is needed for newer versions of NPM
=> fix(docs): installing from github packages throws error on npm 9+

.github/workflows/build.yml, .github/workflows/failure_notification.yml
The `build` workflow needs to be simplified/split-up in preparation for https://github.com/winglang/wing/issues/256. The alert workflow doesn't need to run in forks, nor does it even need to run on push. This is one less thing to worry about in forks (check_run events should not be triggered by forks AFAIK)
=> chore: alerting workflow triggered by check_run event

docs/04-reference/winglang-spec.md, examples/tests/valid/asynchronous_model_implicit_await_in_functions.w, libs/wingc/src/jsify.rs, tools/hangar/src/__snapshots__/cli.test.ts.snap, tools/hangar/src/cli.test.ts
See issue #1073 for the use case - in short, we didn't propagate the phase (e.g. `inflight`) when jsifying arg list, which led to skipping adding implicit await on inflight calls.
Credit for assistance: @yoav-steinberg 👍 
Fixes #1073 
=> fix(compiler): implicit await missing in argument lists

apps/vscode-wing/package-lock.json, docs/04-reference/wingsdk-api.md, examples/tests/valid/std_containers.w, libs/wingc/src/capture.rs, libs/wingc/src/jsify.rs, libs/wingc/src/parser.rs, tools/hangar/src/__snapshots__/cli.test.ts.snap
This fixes the build break caused by #1076 as follows:
1. Missed some updates to generated API documentation.
2. Update package-lock.json
3. Emit an "unsupported capture" error only if the symbol is a preflight symbol (otherwise, it is not really a capture).
4. Synthesize `ops: ["a", "b", "c"]` instead of `ops: [a,b,c]` (regression).
5. Emit a "syntax error" when a nested identifier cannot be parsed (the test `missing_semicolon.w` failed with a panic because the type checker did not descend into the inflight closure through the error) <-- we need a more robust model for validating that there are no parse errors at all throughout the tree.
[Monada Contribution …
=> chore: follow ups on immutable capture (#1076) and fix build

.github/workflows/auto-approve.yml, .github/workflows/close-stale.yml, .github/workflows/failure_notification.yml, .github/workflows/issue-backlogger.yml, .github/workflows/pull-request-lint.yml, .github/workflows/release-commenter.yml, .github/workflows/update-docsite.yml
The primary purpose of the PR was to change ravsamhq/notify-slack-action from "v2.3.0" to "2.3.0", which was preventing it from running.
Did some additional cleanup while I was around.
=> chore: wrong version of slack notifier in workflow

.github/workflows/build.yml, .github/workflows/wingsdk-mutation.yml
Because the workflows won't run until merged to main. My fork at https://github.com/MarkMcCulloh/wing has example of the workflow running on a fork (AKA a place that doesn't have access to all the secrets). I propose an admin force merges this PR.
- build workflow now uses pull_request_target in addition to push (for `main` only)
- Ensured PROJEN_GITHUB_TOKEN is only used in places that would have access to it (pushes to main on our repo)
- GITHUB_TOKEN should have all the permissions needed to do what we need in forks
- Simplified the self-mutation logic and verified it works in a fork. Eventually, the self mutator won't be specific to wingsdk :)
Fixes #256
[Monada Contribution …
=> chore: fork-based workflows

examples/tests/invalid/container_types.w, examples/tests/invalid/mut_container_types.w, examples/tests/valid/container_types.w, examples/tests/valid/mut_container_types.w, libs/wingc/src/ast.rs, libs/wingc/src/jsify.rs, libs/wingc/src/lib.rs, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, libs/wingsdk/src/std/set.ts, libs/wingsdk/test/target-sim/queue.test.ts, tools/hangar/src/__snapshots__/cli.test.ts.snap
Adds support for mutable arrays and sets.
Misc:
- Add `Set.has()`, `MutSet.clear()` and `MutSet.delete()`.
- Add tests for all std APIs.
- Add some invalid tests for partial equality.
Resolves #852 
Resolves #663 
=> feat: mutable arrays and sets

rfcs/story10.md
Added a missing semicolon on this line:
```ts
let expected = "task 42"
```
Credit to @schosterbarak for reporting this issue.
=> rfc: added missing semicolon

.mergify.yml
This is a very bare-bones mergify config. This is just enough to handle a merge queue. After this gets merged, we should be able to make the "mergify summary check" the only required check. Then we can start getting fancy.
Fixes #698
=> chore(repo): add mergify to handle merge queue

docs/02-getting-started/02-installation.md, docs/99-status.md
Update the getting started guide to instruct users on how to upgrade from the closed alpha version (`@winglang/wing`).
Fixes #1174 
=> fix(docs): failure to migrate from closed alpha

docs/02-getting-started/02-installation.md
Wrong `</br>` in markdown instead of `<br/>`
=> chore(docs): markdown error br

apps/wing/bin/wing
This simplified shebang should be able to run anywhere. The downside is the now-required `spawn`, but I think that's worth revisiting later.
Note: this PR **does not** confirm windows support (although windows may work now 😁), but it does resolve #1157
=> fix: cross-platform wing cli shebang

apps/wing/src/commands/index.ts, apps/wing/src/commands/run.test.ts, apps/wing/src/commands/run.ts, apps/wing/src/index.ts
This PR resolves #1112
command `wing it` with no file name will work if there's a single .w file in the directory
=> feat(cli): wing it does not require a file name for single file folders

apps/wing-playground/index.html, apps/wing-playground/worker.js
regressions from https://github.com/winglang/wing/pull/1199
Writing to stderr from wingc was no longer causing an exception in the playground, which was hiding it. This does not affect the CLI, which uses the node WASI system rather than wasmer-js.
I also went ahead and made stderr more obvious, instead of showing it in where the user was expecting JS.
=> fix(playground): compiler errors missing

libs/wingsdk/src/target-sim/function.inflight.ts, libs/wingsdk/test/target-sim/__snapshots__/function.test.ts.snap, libs/wingsdk/test/target-sim/function.test.ts
Executing `panic()` in a function is being translated to process.exit(1).
This causes the Simulator process to actually exist once the function is being invoked.
In order to prevent the Simulator process to exit we override the `process.exit` command when passing the `process` object to the VM context.
=> fix(sdk): simulator crashes when executing panic() in a function

.github/workflows/build.yml
Fix build workflow to use `args` to pass `--exclude` because the action doesn't support it as a first class
=> fix(repo): build is failing due to invalid nx action config

.github/workflows/pull-request-lint.yml, .npmrc, docs/02-getting-started/02-installation.md, docs/06-contributors/handbook.md, docs/06-contributors/workflows.md
To clarify the situation:
- npm 9 works fine as a consumer of wing (e.g. you run `npx winglang compile ...` or `npm install -g winglang`)
- npm 9 did **not** work as a developer of wing (`npm install` at the root)
This PR fixes that second issue with the additional npmrc file. So now we support npm 9, however the contributor docs will still specify 8 because we should all be using the same version if possible. If you decide to use 9 anyways, it will still work but it may cause lockfile thrashing until we all make the switch.
The regular getting started guide doesn't need to mention npm, if you're at least using node 18 then your npm version should work as a consumer.
While in the docs, I also made some other random tweaks.
Fixes #1103
*By submitting this pull request, I confirm that my …
=> fix(docs): lack of clarity regarding npm v9

docs/05-rfcs/stories/story-11.md
Just fixing some typos (missing `)`, `;` and extra `()`) in story 11.
=> rfc: typos in story 11 preventing compilation

apps/vscode-wing/project.json
The SDK .jsii is copied during the build process so it needs to be available.
=> chore(vscode): nx config missing sdk dependency

apps/vscode-wing/project.json, docs/06-contributors/handbook.md
=> fix(docs): make the build vsc extention compile example work

examples/tests/invalid/missing_semicolon.w, examples/tests/valid/primitive_methods.w, examples/tests/valid/reassignment.w, examples/tests/valid/while_loop_await.w, libs/wingc/project.json, libs/wingc/src/parser.rs
Fixes #1266
After making the fix work, I discovered there were many syntax errors in our valid examples, so I fixed all of them as well.
I also noticed this sequence of commands were failing on a fresh repo:
```
npm i
cd libs/wingc
npx nx run build-native
npx nx run test
...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Expected to find .jsii file in ../wingsdk, but no such file found"', libs/wingc/src/type_check.rs:1729:18
```
The same issue applies with `npx nx run dev`.
To fix this I've added the sdk as a dependency of `wingc:dev` and `wingc:test`.
=> fix(compiler): should show errors for missing semicolons or braces

examples/tests/invalid/unimplemented_grammar.w, libs/tree-sitter-wing/grammar.js, libs/wingc/src/parser.rs
The wing compiler throws error for unimplemented grammar.
Included in this PR:
1. Removed from the list of unimplemented grammar, features we already support (MutArray, MutSet).
2. Added `defer` to that list.
3. Added a test for grammar we intend to keep unsupported also after wing is in beta.
=> chore(compiler): throw error for more unimplemented grammar cases

apps/vscode-wing/package-lock.json, apps/wing-playground/package-lock.json, apps/wing/package-lock.json, libs/wingsdk/.projen/deps.json, libs/wingsdk/.projenrc.ts, libs/wingsdk/package-lock.json, libs/wingsdk/package.json, libs/wingsdk/test/target-tf-aws/__snapshots__/bucket.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/counter.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/function.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/queue.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/topic.test.ts.snap, libs/wingsdk/test/target-tf-azure/__snapshots__/bucket.test.ts.snap, tools/hangar/src/__snapshots__/cli.test.ts.snap
The purpose of this is to stop snapshots from changing with new versions of cdktf. Originally I was just going to sanitize the snapshot, but I feel like it's entirely reasonable to pin cdktf very strictly. 
cdktf is pretty important and we may not want consumers of the SDK to freely choose the version.
=> chore: strictly pin and update cdktf version in sdk

.github/workflows/build.yml
Another follow-up for https://github.com/winglang/wing/pull/1277
Mistake this time: The `v` is only present in the tag, not the normal "version" part of the workflow. So the comparison was wrong. Changed to using version to be clear that the `v` isn't there.
=> chore: publish workflow typo in version comparison

.github/workflows/build.yml
TIL about `${...#?}` in POSIX terminals. The previous method was not completely portable (worked locally for me, not in the runner)
=> chore: shell substitution for publish version failed

libs/wingsdk/src/target-tf-azure/app.ts, libs/wingsdk/src/target-tf-azure/bucket.inflight.ts, libs/wingsdk/src/target-tf-azure/bucket.ts, libs/wingsdk/test/target-tf-azure/__snapshots__/bucket.test.ts.snap, libs/wingsdk/test/target-tf-azure/bucket.test.ts
This PR moves storage account and resource group resources to the app level to be shared across all resources defined within the app.
Also minor refactor on inflight client to only create 1 instance of containerClient.
=> fix(sdk): azure share resources at app level

docs/04-reference/wingsdk-api.md, docs/04-reference/wingsdk-spec.md, libs/wingsdk/API.md, libs/wingsdk/src/cloud/topic.ts
Closes #1390 
Closes #1389 
Updates the spec to use the `on_message` name / be consistent with the current API (`on_event` didn't seem any clearer).
Removed `subscribe` from the spec since it didn't add any new functionality and I think the API doesn't read as clearly:
```
// topic is not subscribing to the handler - it's the other way around
topic.subscribe(handler);
```
=> chore(docs): update topic.on_message docs

apps/wing/src/index.ts
Made --target required, and only allow supported options.
**note** that with commander the only way (as per documentation) to make required choices mandatory is to use the `new Option()` convention rather than the `.option()`
See: https://www.npmjs.com/package/commander#more-configuration
Compile Help Message:
```
Usage: wing compile [options] <entrypoint>
Compiles a Wing program
Arguments:
entrypoint               program .w entrypoint
Options:
-o, --out-dir <out-dir>  Output directory (default: "/Users/hasan/repos/leena/target")
-t, --target <target>    Target platform (choices: "tf-aws", "tf-azure", "tf-gcp", "sim")
-h, --help               display help for command
```
No target given
```
wing compile app.w   
error: required option '-t, --target <target>' not specified
```
Invalid …
=> feat(cli): make target required from choices

.github/pull_request_template.md
In PR description GitHub actually respects newlines in markdown (yes, an awful mistake)
=> chore(repo): remove newline in pr template

apps/wing/project.json, apps/wing/src/commands/compile.test.ts, apps/wing/src/commands/compile.ts, apps/wing/src/index.ts, docs/02-getting-started/02-installation.md, docs/02-getting-started/03-hello.md, docs/02-getting-started/05-aws.md, docs/02-getting-started/06-simulator.md, libs/wingsdk/.projen/deps.json, libs/wingsdk/.projen/tasks.json, libs/wingsdk/.projenrc.ts, libs/wingsdk/package-lock.json, libs/wingsdk/package.json, libs/wingsdk/src/core/app.ts, libs/wingsdk/src/core/tree.ts, libs/wingsdk/src/target-sim/app.ts, libs/wingsdk/test/sandbox/cdktf.json, libs/wingsdk/test/sandbox/main.ts, libs/wingsdk/test/target-sim/__snapshots__/bucket.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/counter.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/file-counter.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/function.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/immutable-capture.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/logger.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/queue.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/topic.test.ts.snap, tools/hangar/src/__snapshots__/cli.test.ts.snap, tools/hangar/src/cli.test.ts
This PR updates the CLI so that all compiler artifacts (like terraform files, simulator files, etc.) are now synthesized into target-specific directories (closes #815). For example, `wing compile -t tf-aws hello.w` will generate terraform artifacts inside `target/hello.tfaws/` while `wing compile -t tf-azure` will generate terraform artifacts inside `target/hello.tfazure/`. This avoids some problems users had where compiling to different targets would override previously compiled artifacts.
The simulator target now generates a single `.wsim` which is generated directly inside `target/`. (Under the hood, the `.wsim` file now contains the `tree.json` file that was previously generated outside).
This is a breaking change as it may require using a new version of the Wing console that …
=> feat!: compile artifacts into target-specific directories

.github/workflows/build.yml
We switched to pull_request_target a while back while making sure fork workflows would work. This made sense for the self-mutation workflow, but this isn't necessary for the build workflow. 
If triggered from a PR, the workflow does not use any secrets or attempt to write anything so it doesn't need those permissions. The only time secrets are read is on `push` to main.
The primary benefit of this change is that now we can easily test workflow changes in PRs. It's also just the generally recommended way for doing these workflows.
The explicit `ref` and `repository` settings were removed because pull_request_target didn't set it in the expected way. No longer needed, PRs will checkout the merge commit now.
*By submitting this pull request, I confirm that my contribution is made under the …
=> chore: use pull_request instead of pull_request_target for builds

apps/wing/src/commands/compile.ts, apps/wing/src/commands/run.ts, apps/wing/src/commands/test.ts, apps/wing/src/util.ts
The first of many additions of `replace(/\\/g, "/")` :)
While the CLI does work on windows, if the user provides any `\`s in the path it breaks the wasm preopens.
=> fix: windows path delimiters break cli

apps/wing/src/commands/compile.ts, apps/wing/src/util.ts
Followup to https://github.com/winglang/wing/pull/1454
My iteration cycle on fixes for Windows is a bit slow. Also added an if check to do the normalization cause it would be wasted cycles outside of windows.
=> fix: windows absolute paths break cli

docs/04-reference/winglang-spec.md
Provide a "good" example for `unsafe: true` and make P2.
=> chore(docs): better examples for `unsafe: true`

docs/04-reference/winglang-spec.md
=> chore(docs): missing `json` type initializer

.github/workflows/pull-request-lint.yml, docs/06-contributors/030-pull-requests.md
Just tying up a loose end - adding `plugins` scope to PR linter and to our documentation at: https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted to indicate PRs related to the Wing Plugin System
=> chore: add plugins scope to pr lint

docs/04-reference/winglang-spec.md, examples/tests/invalid/try_no_catch_or_finally.w, examples/tests/valid/try_catch.w, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, tools/hangar/src/__snapshots__/compile.test.ts.snap, tools/hangar/src/__snapshots__/invalid.test.ts.snap
* Support `return` in `try`/`catch`.
* Error if both `catch` and `finally` are missing.
=> fix(compiler): can't call `return` in `try`/`catch`/`finally`, no error when missing `catch`/`finally`

apps/wing/src/commands/compile.test.ts, apps/wing/src/commands/compile.ts, apps/wing/src/index.ts
https://github.com/winglang/wing/pull/1533#discussion_r1106810918
I did some minor refactoring so that the `compile` function can be unit tested more easily (it now throws an error instead of printing and exiting immediately).
=> chore: add test for compiling with missing source file

apps/wing-playground/package-lock.json, apps/wing/package-lock.json, apps/wing/package.json, libs/wingsdk/package-lock.json
Fixes #1578 by bundling wasi-js so it does not run its own preinstall script. Pretty heavy handed, but not sure what else to do.
The real fix needed is https://github.com/pnpm/only-allow/issues/13
=> chore: bundle wasi-js to avoid its preinstall script

.github/workflows/build.yml
WORKFLOW_FULL_E2E and WORKFLOW_PUBLISH were a well-meaning change, but I can't get it to resolve correctly (`github.env` and `env` worked on `act`, but not on github).
Will need to revisit.
=> chore: revert env usage in github `if` expressions

examples/tests/valid/bring_cdktf.w, examples/tests/valid/package-lock.json, examples/tests/valid/package.json, libs/wingc/src/type_check/fqn.rs, libs/wingc/src/type_check/jsii_importer.rs, libs/wingc/src/type_check/symbol_env.rs, tools/hangar/src/__snapshots__/compile.test.ts.snap, tools/hangar/src/__snapshots__/test.test.ts.snap
Fixes some limitations with the compiler's jsii importer so that it's now possible to import types from most CDKTF libraries (tested with `@cdktf/provider-aws`).
Notes:
- There were some issues with the jsii importer not unhiding namespaces correctly -- the plan is still to just remove this namespace-hiding logic (see #1487), but to avoid mixing concerns I just fixed the issues I found in this PR.
- Since the compiler doesn't support interfaces yet, I imported these types as `anything`. It's not possible skip importing them because many other resource methods reference interfaces in their parameters (e.g. "cdktf.IResolvable") and our jsii importer doesn't support gracefully failing in these kinds of situations.
- Fixed an issue with symbol shadowing (copied from #1610)
*By submitting this …
=> feat: bring cdktf

docs/04-reference/wingsdk-spec.md
Proposal to add an API to `cloud.Counter` for `counter.reset(value)`. I was trying to build some Wing applications and I noticed it was sometimes awkward to use `cloud.Counter` in unit tests without a mechanism to set the counter back to an initial value.
=> docs: add counter.reset api

apps/wing/src/commands/compile.ts
Closes #912
Panic error messages should look something like this now
=> feat(cli): ask politely for bug reports when panic occurs

docs/04-reference/wingsdk-spec.md
You must use the primary key to delete a row from a table
=> chore(docs): you must use the primary key to delete a row from a table

apps/jsii-docgen/test/__snapshots__/cli.test.ts.snap, apps/jsii-docgen/test/docgen/view/__snapshots__/documentation.test.ts.snap, apps/jsii-docgen/test/docgen/view/__snapshots__/markdown.test.ts.snap, apps/wing-playground/package-lock.json, apps/wing/package-lock.json, docs/06-contributors/020-development.md, package.json, tools/hangar/src/__snapshots__/compile.test.ts.snap
Somehow #1681 got merged with some stale snapshots and other generated artifacts. This PR fixes that.
Misc: changed the root `build` npm script to mimick what we run in CI because basically there's no easy way to run a full build on the system.
=> chore: fix broken `main` due to #1618

apps/wing/src/commands/compile.ts, tools/hangar/src/__snapshots__/test.test.ts.snap
Shares the console with preflight vm allowing us to display preflight print statements
Closes: #1538 
Screenshot of the hotness:
=> feat(compiler): display preflight prints

libs/wingii/src/lib.rs
Instead of `unwrap`-ing it should be ok to just error here
=> chore: improve error message when dependency not found

libs/wingc/src/capture.rs, libs/wingc/src/jsify.rs, libs/wingc/src/type_check.rs
done by creating a `ClassLike` trait that can be useful for other things like a `get_method` api.
=> chore(compiler): dedup interface/class method/field iterator helpers

apps/wing/src/commands/compile.ts
Adds the path to the referenced JS file in preflight error messages. This information is handy when you are trying to dive into debug why an error occurred, especially for people unfamiliar with where Wing compile artifacts are generated.
=> feat: include js path in preflight error message

libs/wingc/src/jsify.rs, libs/wingsdk/src/cloud/function.ts, libs/wingsdk/src/core/app.ts, libs/wingsdk/test/sandbox/main.ts, libs/wingsdk/test/target-sim/__snapshots__/file-counter.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/queue.test.ts.snap
Adds a workaround for an issue where compiling cloud functions (which calls esbuild) results in mangled terminal output.
=> fix: compiling cloud function mangles terminal output

.github/workflows/build.yml, Cargo.lock, apps/vscode-wing/project.json, docs/06-contributors/020-development.md, libs/tree-sitter-wing/bindings/rust/build.rs, libs/tree-sitter-wing/bindings/rust/lib.rs, libs/wingc/examples/compile.rs, libs/wingc/project.json, libs/wingc/src/lib.rs, libs/wingii/project.json, libs/wingii/src/lib.rs, libs/wingii/src/node_resolve.rs, libs/wingii/src/util.rs, nx.json, rust-toolchain.toml
- Update Rust dependencies
- Fix an issue where the vscode-wing package task could be executed before the vscode-wing build task
- Add rust linting with the built-in `clippy` tool to our build process (automatically runs as part of `nx run test wingc` and `nx run test wingii`)
For linting, clippy has over 600 different lints that are grouped into categories. To start, I've just enabled the "correctness" set of lints in this PR. But over time we can add more lints by simply adding directives into the source code.
Contributors using VS Code can install the `rust-analyzer` extension and set "Rust-analyzer › Check: Command" to "clippy" to start seeing the full set of lint errors/warnings in their editor.
*By submitting this pull request, I confirm that my contribution is made under the terms …
=> chore(repo): update rust dependencies, add rust linting

.cargo/config.toml, .github/workflows/build.yml, .gitignore, Cargo.lock, apps/wing-playground/package-lock.json, apps/wing/package-lock.json, docs/06-contributors/020-development.md, libs/tree-sitter-wing/bindings/rust/build.rs, libs/wingc/Cargo.toml, libs/wingc/project.json, libs/wingc/src/ast.rs, libs/wingc/src/diagnostic.rs, libs/wingc/src/lib.rs, libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/document_symbols.rs, libs/wingc/src/lsp/hover.rs, libs/wingc/src/lsp/notifications.rs, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/jsii_importer.rs, libs/wingii/project.json, nx.json, rust-toolchain.toml, scripts/setup_wasi.sh, tools/hangar/src/invalid.test.ts, tools/hangar/src/test.test.ts, tools/hangar/src/utils.ts
Misc changes while working on other stuff
- Update rust to 1.67.1 and made change to .cargo/config.toml to get it to work
- Changed hangar so that it stops spitting out `undefined` when the cli errors
- Updated wasi-sdk to the latest version, and changed the install scripts that it installs a tool within the repo itself (gitignored)
- This avoids using sudo in the install
- It is also now a versioned dir, this should make it easier to make sure everyone stays in sync whenever it changes
- Added WingPoint, and made better use of `Into`, `From`, and `Default` so that and WingSpan for some hopefully more idiomatic rust experiences
- Added "lint" as a cached nx operation. This should be okay since it relies on changes to src files
- Made sure clippy runs with release and a couple of other …
=> chore: update rust toolchain and several misc changes

examples/tests/valid/bucket_keys.w, libs/wingsdk/src/target-sim/bucket.inflight.ts, libs/wingsdk/test/target-sim/__snapshots__/bucket.test.ts.snap, libs/wingsdk/test/target-sim/bucket.test.ts, tools/hangar/src/__snapshots__/compile.test.ts.snap, tools/hangar/src/__snapshots__/test.test.ts.snap
Previously, many kinds of keys could not be used for objects in `cloud.Bucket`. This would result in runtime errors in the Wing simulator (even these keys are valid in AWS and other cloud providers).
Fixed the issue by storing objects in the file system according to a hashed version of their key, and storing the set of keys in-memory.
Related to #1676
Misc: cleaned up some redundant test snapshots
=> fix(sdk): some bucket keys are invalid

libs/wingc/src/type_check.rs, libs/wingc/src/type_check/jsii_importer.rs
**self inflicted goof**
removed logic in typechecker where it would try and map Json from stdlib to Json in compiler. I have since learned that the jsii_importer is a much more holistic solution. 😅 
=> fix(compiler): handle json type mapping in jsii importer

libs/wingsdk/API.md, libs/wingsdk/src/cloud/api.ts
Add the missing functions to the cloud api class.
On the initial implementation https://github.com/winglang/wing/pull/1285 only the get function was part of the abstract cloud class. 
=> fix(sdk): add missing api functions

docs/04-reference/winglang-spec.md
Following [a discussion](https://github.com/winglang/wing/pull/1665#discussion_r1120271792) - we decided to update `Json.format()` to `Json.to_str()`.
Updated the spec and also issue #1053.
=> chore(docs): rename json.format() to json.to_str()

README.md
Hey there, after committing I realised that contributor avatars didn't increase in size when the column number was decreased, leaving a huge gap on the right hand size (as seen in the screenshot below). I've reverted to the default number of columns (12) which will fill up the readme file from left to right. 
=> chore(repo): revert to default number of columns for the contributors section

.github/workflows/build.yml, .mergify.yml
Also fix mergify config, which started ignoring the E2E test requirement due to a regression from my last PR.
=> chore: exclude windows from pr build

docs/06-contributors/999-rfcs/000-stories/story-13.md
Updating story 13 to use the correct way to convert json to string (`str.from_json()` instead of `Json.to_str()`).
=> chore(docs): update story 13 - convert json to string

examples/tests/invalid/construction.w, examples/tests/invalid/unknown_symbol.w, libs/wingc/src/lsp/sync.rs, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap
When type checking and coming across a bad (_read_: typed as `any`) call/new reference, we did not traverse the arguments. That means we never gave them type info. 
The capturing process (and lsp) assumes all expressions in the AST have a type, so it panics.
Also re-enabled vscode's capture diagnostics, because this bug is why I removed them in the first place.
Fixes #1747
Fixes #1647
Fixes #1802
=> fix: panic while analyzing captures in unknown calls/news

.github/workflows/build.yml
The label still has to be added during the actual build run (won't retrigger anything), but this was an easy change and it's better than nothing.
=> chore: allow `pr/e2e-full` label to be added or removed after build starts

libs/wingsdk/src/cloud/function.ts, libs/wingsdk/test/target-tf-aws/function.test.ts
Disallows spaces from asset relative directories as they cause issues when creating TerraformAssets. Fixes issue where we could not find asset zip folder when deploying terraform
Closes: https://github.com/winglang/wing/issues/1866
=> fix(sdk): spaces in function names cause problems with terraform assets

libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/hover.rs, libs/wingc/src/lsp/sync.rs
Full credit to @yoav-steinberg for finding the root cause/solution.
While there is a more systemic issue at play here (the unsafe pointers), I would call this change a workaround rather than a hack (which is what I was doing before).
Fixes #1644
=> fix: hierarchal symbol lookups in language server sometimes fail

scripts/changelog.mjs
Regression from https://github.com/winglang/wing/pull/1902 (thanks @Chriscbr)
If it's a breaking change, then it'll increment minor
=> chore: feats should only increment patch version by default

libs/wingsdk/src/target-sim/function.inflight.ts
When copying global for the new sim context, accessing `global.wasi` triggered a `require` that fails. This only seems to happens in a REPL 🤷 
In any case, a corrupted global obj probably isn't worth crashing over. I'm not even sure it's worth logging, feel free to let me know if you do.
Fixes #1912
=> fix: unavailable global property crashes simulator

tools/hangar/src/package.setup.ts
Need to allow install scripts for dockerode in windows.
=> fix(build): allow window install hooks for dockerode

libs/wingsdk/src/target-sim/redis.inflight.ts
=> fix(sdk): correct redis container name in case of resource nesting (fix #1959)

examples/tests/valid/json.w, libs/wingc/src/ast.rs, libs/wingc/src/type_check.rs
* don't pass statement index all around the type checker, instead store it in the TypeChecker sate.
* Store `in_json` in the type checker state instead of adding the extra context struct.
* removed duplicate code for method/init type checking 
=> chore(compiler): cleanups in type checker

docs/03-concepts/02-inflight.md
The doc text was referring to an inflight by name, but the inflight no longer has a name after https://github.com/winglang/wing/commit/62b13c6c9e6760ef9423506da366b702c686a62e
=> fix(docs): refers to inflight by incorrect name

examples/tests/valid/resource_captures.w, libs/wingc/src/jsify.rs, tools/hangar/__snapshots__/test_corpus/valid/resource.w.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/resource_captures.w.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/static_members.w.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/structs.w.ts.snap
Added no-ops bindings for unused fields in resources.
Thanks @Chriscbr and @yoav-steinberg for the pow-wows on this.
Closes: https://github.com/winglang/wing/issues/1872
**Misc**
- Cleaned up unneeded code in `get_captures()` where we no longer needed to return vec of tuples and can just use vec of string
=> fix(compiler): allow unused sim resources

libs/wingc/src/ast.rs, libs/wingc/src/jsify.rs, libs/wingc/src/lsp/hover.rs, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, libs/wingc/src/visit.rs
Inside the AST nodes for `FunctionDefinition` and `Constructor`, we were storing the function signature in one field (which contains a list of parameter types) and a vector of parameter metadata (their names and whether they're reassignable) in another field. To keep all parameter information together, this PR refactors the data model so all parameter-related information is in a `FunctionParameter` struct and store that in `FunctionSignature`.
Since function type annotations don't have all this information (a function type annotation like `inflight (num): str` doesn't track reassignable-ness or parameter names), I've moved that information into a dedicated `FunctionTypeAnnotation` struct.
*By submitting this pull request, I confirm that my contribution is made under the terms of the …
=> chore(compiler): clean up how parameters are modeled

libs/wingsdk/src/core/app.ts
Today, if you try compiling your app to `tf-aws` and check the terraform JSON file that is created inside `target/`, you will find the value `terraform.backend.local.path` is set to a location at the root of your project directory (like `/path/to/my-project/terraform.root.tfstate`). This path specifies where `terraform apply` will create a local terraform state file to track what resources have already been created etc.
That works fine if you are working with a single Wing program. However, if you want to deploy or test multiple Wing apps in the cloud, they will all try to store their state in the same file, which means resources may get destroyed unexpectedly.
This PR fixes that so that the terraform state is saved in the per-target directory (for example, if you compiled `main.w` to …
=> feat: save local terraform state per app

apps/vscode-wing/syntaxes/wing.tmLanguage.json, libs/wingc/src/lsp/completions.rs
Fixes #1887
Fixes #1983
Additionally:
- Added/fixed some missing highlights
- Slipped in a fun feature where completing a function/method includes `()` and sets the cursor inside them.
- There is a smidge of duplication with this feature, but expect lots more handling of interesting snippets like this, so I think we can leave that sort of cleanup for a less special-case PR.
=> fix(vscode): wrong completion label for interfaces and aliased namespaces

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
The community note is currently at the top of the issue templates, which means that all of our issue description begin with the same text, making it hard to identify the content in short notifications, etc.
=> chore(repo): move "community note" to the end of issues

.github/ISSUE_TEMPLATE/bug.yml
Duplicate id was preventing the bug template from being usable
=> chore: duplicate id in `bug` issue template

examples/tests/valid/api_valid_path.w, libs/wingsdk/src/cloud/api.ts
fixes #2056 
- fixing it to allow any char on the URL itself (aside ":") and `A-Za-z0-9_` chars on the param placeholders (since using express under the hood, following their documentation: https://expressjs.com/en/guide/routing.html#route-parameters)
[the new pattern is this](https://regexr.com/7c0sr)
- formatting the URL validity test a bit
=> fix(sdk): fix api.url validation regex

apps/wing/package-lock.json, apps/wing/package.json, apps/wing/src/commands/compile.test.ts, apps/wing/src/commands/compile.ts, apps/wing/src/commands/docs.test.ts, apps/wing/src/commands/docs.ts, apps/wing/src/commands/run.test.ts, apps/wing/src/commands/run.ts, apps/wing/src/wingc.ts, apps/wing/vitest.config.ts
Fixes #2081
When running wing from the same directory as the wing file, relative extern specs failed to be found in wingc. This was because the WASI preopens didn't understand the given absolute path when when trying to read the same directory as ".". To be completely honest, I'm not sure why it worked from a parent directory.
I added this test to apps/wing instead of hangar, and while I was there I changed it to use vitest instead of jest since the rest of our repo uses it.
=> fix: unable to resolve extern depending on cwd

libs/wingsdk/src/target-sim/secret.inflight.ts
Add the name of the secret we are looking for.
=> chore(sdk): better error message in sim when no secrets file

libs/wingsdk/src/target-sim/api.inflight.ts
increasing sim api request size limit to match aws api gateway payload size limit.
=> fix(sdk): increasing sim api req limit to match aws'

examples/tests/valid/benchmarks/empty.w, examples/tests/valid/benchmarks/functions_1.w, examples/tests/valid/benchmarks/functions_10.w, examples/tests/valid/benchmarks/hello_world.w, examples/tests/valid/benchmarks/jsii_big.w, examples/tests/valid/benchmarks/jsii_small.w
Benchmarks were added with a limit to make sure we don't make wing any slower. I think the current limits may be too optimistic, so I added 2 seconds to all of them. 
I consider this **temporary** as we gain more data to create a more realistic target.
=> chore: add more wiggle room for benchmarks

apps/wing/src/wingc.ts, tools/hangar/src/cli.bench.ts
Initially, the "/" was removed because it didn't seem to be doing anything. The slash is needed in the lsp because no other propens are provided. Luckily the lsp mostly (or only?) uses absolute paths.
Turned off benchmark gating https://github.com/winglang/wing/issues/2210
=> fix: unable to resolve node_module jsii libraries from lsp

scripts/docsite.sh
Changes git cloning method to https instead of SSH. Also added a condition to gracefully exit the script after removing the created directory to prevent further actions unnecessarily running and throwing errors  in case of a git clone failure.
=> fix: cloning winglang docsite repo failing in "npm run docs"

docs/02-getting-started/06-simulator.md
We recently added the `Default` scope, so resources which used to wonder carelessly directly under `root/` are now under `root/Default/`. This broke the ["Testing programmatically" section on our getting started guide](https://docs.winglang.io/getting-started/simulator).
Fixes #2202 
=> fix(docs): testing programmatically broken due to new default scope

libs/wingsdk/src/shared-aws/topic.onmessage.inflight.ts, libs/wingsdk/src/target-tf-aws/bucket.onevent.inflight.ts, libs/wingsdk/test/target-awscdk/__snapshots__/topic.test.ts.snap
Change the `Topic.on_message` handle parameter on AWS to be the actual message, which aligns the behavior with the simulator.
Fixes #2223 
=> fix(sdk): aws topic onmessage parameter

package-lock.json, package.json
In newer versions of nx, commands like `npx nx wing -- compile -t sim ../../examples/tests/valid/hello.w` no longer work.
Issue: https://github.com/nrwl/nx/issues/16499
=> chore: downgrade nx to fix argument forwarding issue

docs/04-reference/wingsdk-api.md, examples/tests/valid/json_static.w, libs/wingsdk/API.md, libs/wingsdk/src/std/json.ts, tools/hangar/__snapshots__/test_corpus/json_static.w_compile_tf-aws.md
Add `try_parse()` static method on `Json`.
=> feat(sdk): try parse static method for json

docs/04-reference/wingsdk-api.md, libs/wingsdk/API.md, libs/wingsdk/src/cloud/secret.ts, libs/wingsdk/src/target-awscdk/secret.ts, libs/wingsdk/src/target-tf-aws/secret.ts, libs/wingsdk/test/target-awscdk/__snapshots__/secret.test.ts.snap, libs/wingsdk/test/target-awscdk/secret.test.ts, libs/wingsdk/test/target-tf-aws/__snapshots__/secret.test.ts.snap
If a name is provided then the `cloud.Secret` references an existing secret
in the target cloud. If no name is provided then a new secret is provisioned
in the target cloud.
⚠️ It is no longer possible to provision a secret with a well-defined/well-known name.
Closes #2252 
=> feat(sdk): reference existing secrets

examples/tests/invalid/container_types.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap
=> fix(compiler): mutarray can be assigned to an array

libs/wingsdk/src/target-tf-aws/bucket.ts, libs/wingsdk/test/target-tf-aws/__snapshots__/bucket.test.ts.snap, tools/hangar/__snapshots__/test_corpus/bucket_events.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/resource.w_compile_tf-aws.md
After pulling out about all the hairs I have left I found out why my S3 object creates were not firing events to lambda 😄 
=> fix(sdk): aws bucket event actions swapped

.github/ISSUE_TEMPLATE/bug.yml
The recent change in this template was to replace the order of the expected and the actual result. The "instead" word was relevant before but doesn't make sense now.
=> chore(repo): remove instead word from bug label

docs/04-reference/wingsdk-spec.md
This is the API we already have for `cloud.Secret`, we just didn't have it documented in the spec.
=> feat(docs): add secret to sdk spec

libs/tree-sitter-wing/grammar.js, libs/wingc/src/ast.rs, libs/wingc/src/fold.rs, libs/wingc/src/jsify.rs, libs/wingc/src/lsp/completions.rs, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, libs/wingc/src/visit.rs, tools/hangar/__snapshots__/invalid.ts.snap
- The grammar now allows new expressions like `new cloud.Bucket`
- Our parser will still yell at you about it
- Most of the changes here are due to the added TypeAnnotationKind enum and changed TypeAnnotation to a struct that also has a span
- If the jsii type is not imported, it will not show up in completion
- type annotations in variable assignment/declaration don't work
- new expressions really should only show classes
- probably other stuff
=> fix: lsp completion does not show namespaced types or static members

examples/tests/valid/json.w, libs/wingc/src/type_check.rs, libs/wingsdk/src/std/json.ts, tools/hangar/__snapshots__/test_corpus/json.w_compile_tf-aws.md
Closes: https://github.com/winglang/wing/issues/1947
**Misc:**
- Fixed typo in MutJson.set_at() macro
=> fix(compiler): allow empty json

examples/tests/invalid/inflight_ref_resource_sub_method.w, examples/tests/invalid/inflight_ref_unknown_op.w, examples/tests/valid/resource_captures_globals.w, libs/wingc/src/ast.rs, libs/wingc/src/jsify.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/api.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/api_path_vars.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/capture_resource_with_no_inflight.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/construct-base.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/doubler.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/extern_implementation.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/forward_decl.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/impl_interface.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/json.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/reassignment.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/resource.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/resource_as_inflight_literal.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/resource_captures.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/resource_captures_globals.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/resource_captures_globals.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/static_members.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/structs.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/symbol_shadow.w_compile_tf-aws.md
Re-roll of #2211 with some modifications so the implementation keeps inflight clients in their own separate files. I went through a couple iterations to get to this point, here were the potential problems I found with them:
- as @eladb called out, inlining inflight clients into `preflight.js` as implemented in #2205 seems like it could be problematic if clients need to reference other inflight clients (for example, to access static methods)
- another idea I had was to put all inflight clients all in a single file (`preflight.js` and `inflight.js` - cute, right?) - the problem with this is that global variables could conflict with each other, and there might be scoping issues if/when the user starts defining resources at places besides the top level of a wing file
original description:
--- …
=> fix(compiler): preflight objects cannot reference free variables inflight

apps/wing/src/wingc.ts
Preopen symbolic links to directories to open`/tmp`
Fixes #2321 
=> fix: preopen tmp folder

libs/wingsdk/src/target-sim/api.ts, libs/wingsdk/src/target-sim/schema-resources.ts, libs/wingsdk/test/target-sim/__snapshots__/api.test.ts.snap, libs/wingsdk/test/target-sim/api.test.ts
Adds openapi spec to api sim schema, this will be useful to help the console populate route information
=> chore(sdk): add openapi spec to api sim schema

libs/wingc/src/lib.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check_class_fields_init.rs
A little refactoring on "class without an initializer"
I removed the Class Init Visitor from the type_check file to a separate file
=> chore(compiler): refactoring class field initialization

docs/04-reference/winglang-spec.md
Found few errors while going through the lang spec and so did a lazy proofread. Few grammar fixes, few updates to inconsistent styles etc.
Note: Take  a proper look at lines 2114 and 2403
=> chore(docs): some grammar fixes to the language spec

libs/wingsdk/src/target-tf-aws/bucket.ts, libs/wingsdk/test/target-tf-aws/__snapshots__/bucket.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/website.test.ts.snap, libs/wingsdk/test/target-tf-aws/bucket.test.ts, libs/wingsdk/test/target-tf-aws/website.test.ts, tools/hangar/__snapshots__/test_corpus/captures.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/website.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/website_with_api.w_compile_tf-aws.md
I was testing cloud.Website() and there was a small issue with permissions.
I am uploading the fix, but you can already see the result at this link.
[static website example](https://d24lp7k5o7ycd7.cloudfront.net/index.html)
Another thing is that in AWS it is not possible to know the URL of the website at compile time since the URL is only created when the deployment is completed (and in this case, when CloudFront is finished activating).
=> fix(sdk): updating website permission

docs/06-contributors/020-development.md, libs/wingc/src/lsp/completions.rs
Fixes #2387
Added a special case for language completion:
If typing `new` namespace, then completion should show classes only. 
For example:
Also improved the contributors' guide for printing debug messages for the language server.
=> fix(vscode): completion - new expr for namespace returns only classes

docs/04-reference/wingsdk-api.md, libs/wingsdk/API.md, libs/wingsdk/src/cloud/counter.ts, libs/wingsdk/src/shared-aws/counter.inflight.ts, libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap
I noticed some tests using the counter resource were updating even on pull requests where no relevant changes were made. After looking into the code that was bundled into lambda functions, it looked like many other parts of the SDK were getting bundled due to how we are organizing and importing different classes/interfaces.
As a simple fix, I've removed the `CounterClientBase` since it wasn't saving us that many lines of code.
=> fix(sdk): counter inflight client is bundled with excess code

README.md
Found in the [why do we think the cloud needs a programming language](https://github.com/winglang/wing#why-do-we-think-the-cloud-needs-a-programming-language-) section
=> fix(docs): 'are' word repetition in readme

docs/06-contributors/99-maintainers/10-runbooks/000-runbook-template.md
fixing this error: 
by quoting special chars on the title.
=> fix(docs): fixing docsite build

docs/04-reference/wingsdk-spec.md
Followup for #2468.
Fixes #2528.
Another small fix: `bucket.on_upload()` on the sdk spec renamed to `onCreate()` which is what we have in our code.
=> fix(docs): sdk spec - snake case to camel case

examples/tests/valid/json_static.w, libs/wingc/src/jsify.rs, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/test_corpus/json_static.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/json_static.w_test_sim.md
Ignore stdlib types referenced inflight. They're available through the macro system and it's unclear how to import them anyway.
See #2505 
=> fix(compiler): ignore stdlib types referenced inflight

apps/wing/src/commands/__snapshots__/test.test.ts.snap, apps/wing/src/commands/test.test.ts, apps/wing/src/commands/test.ts
This change introduces the ability to see traces in Wing unit tests by including the `--debug` flag when running `wing test` (or using DEBUG=1).
=> feat(cli): show traces in wing tests with --debug

apps/wing/project.json, apps/wing/src/commands/compile.ts, apps/wing/src/wingc.ts, libs/wingc/src/ast.rs, libs/wingc/src/closure_transform.rs, libs/wingc/src/diagnostic.rs, libs/wingc/src/fold.rs, libs/wingc/src/jsify.rs, libs/wingc/src/jsify/free_var_scanner.rs, libs/wingc/src/lib.rs, libs/wingc/src/lsp/document_symbols.rs, libs/wingc/src/lsp/notifications.rs, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/class_fields_init.rs, libs/wingc/src/type_check/jsii_importer.rs, libs/wingc/src/visit.rs
- Remove dead code related to diagnostic levels. Our compiler only produces error diagnostics, so tracking the levels doesn't serve a function right now. Let's add it back when we have a use case for it
- Move FreeVariableScanner and VisitClassInit to their own self-contained modules that can only be accessed by `jsify` and `type_check` respectively.
- Renamed StmtKind::VariableDef to StmtKind::Let and ExprKind::Call.function to ExprKind::Call.callee
- Removed dead code related to case conversion
=> chore(compiler): remove diagnostic levels and other refactorings

tools/hangar/__snapshots__/error.ts.snap, tools/hangar/src/error.test.ts, tools/hangar/src/misc.test.ts
Following the merge of #2442 we saw a regression on Windows (see [here](https://github.com/winglang/wing/actions/runs/5077675549/jobs/9121654237)). Fixing the regression by normalizing paths.
=> fix(compiler): fixing windows build - normalize paths

libs/wingc/src/ast.rs, libs/wingc/src/diagnostic.rs, libs/wingc/src/lib.rs, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap
Fixes an issue where some type checking diagnostics are generated without spans showing where in your code the error is.
In the process I refactored some of the code for generating error messages. It didn't feel like it was as big of an improvement as I expected so I'm open to reverting if the changes seem counterproductive. There's also this `TypeError` struct I saw which doesn't seem to serve any purpose / it's basically the same as `Diagnostic`, so I was also thinking about removing that, but I wasn't sure so I left it as is.
Misc:
- removed some dead (unused) code
----
=> fix(compiler): diagnostics missing error messages

.github/pull_request_template.md
- Add a subheading to distinguish checklist from the rest of the description (which is prepended by github when creating the pull request).
- Tweak phrasing of checklist items
=> chore: tweaks to pull request template

docs/04-resources/bucket.md, docs/04-resources/topic.md, examples/tests/invalid/bring.w, libs/wingc/src/lib.rs, libs/wingc/src/type_check.rs, libs/wingsdk/src/cloud/bucket.md, tools/hangar/__snapshots__/invalid.ts.snap
`bring fs;` causes a compiler panic. 
We used to have a built-in `fs` module, which we removed a while ago. The panic happens because of some leftover code resolving this module.
Fixes #2668
Also fixed a small typo in Bucket resource documentation.
=> fix(compiler): `bring fs` panics

README.md
Correct misspelling of "simulator" in README.md.
=> fix(docs): misspelling in README.md

scripts/setup_wasi.sh
Opportunistically cache the WASI SDK tarball under `/tmp` to avoid having to download it every time.
=> chore(repo): cache wasi sdk tarball to reduce repo setup time

libs/wingsdk/src/shared/bundling.ts, libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap, libs/wingsdk/test/target-awscdk/__snapshots__/queue.test.ts.snap, libs/wingsdk/test/target-awscdk/__snapshots__/topic.test.ts.snap
Adds the fix from #2687 but without the error that caused.
The fix to the introduced error is to resolve all relative paths to absolute paths (the outdir path and the entrypoint path).
This time, I built winglang and the sdk locally and installed them globally. See https://github.com/winglang/wing/pull/2703 for a PR that also includes a test for the old problem.
=> fix: build process cwd is wrong in the console

.vscode/launch.json, docs/06-contributors/020-development.md
@yoav-steinberg added this launch configuration allowing to debug our Rust compiler code (wingc).
I also added a short section in the contributors guide.
Fixes #1104
=> chore(compiler): debug wingc on vscode

apps/wing/src/commands/lsp.ts, libs/wingc/src/jsify.rs, libs/wingc/src/type_check.rs
Normally when the language server panics, the whole thing crashes and you need to restart your editor. This adds a built-in mechanism to avoid exiting completely. It instead lets you know and waits until the wing file is changed before trying again.
The method is pretty naive and effectively resets the entire wasm memory. I did this because the thread local storage has a poisoned refcell and I couldn't figure out how to clear it. I think a full reset is avoidable but this current solution is ok.
=> fix(vscode): language server cannot recover from panics

apps/wing/src/commands/lsp.ts, apps/wing/src/wingc.ts, libs/wingc/src/jsify.rs, libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/mod.rs, libs/wingc/src/lsp/signature.rs, libs/wingc/src/lsp/snapshots/completions/empty.snap, libs/wingc/src/lsp/snapshots/completions/incomplete_if_statement.snap, libs/wingc/src/lsp/snapshots/completions/only_show_symbols_in_scope.snap, libs/wingc/src/lsp/snapshots/completions/static_method_call.snap, libs/wingc/src/lsp/snapshots/signature/named_arg_active.snap, libs/wingc/src/lsp/snapshots/signature/second_arg_active.snap, libs/wingc/src/lsp/snapshots/signature/single_arg_builtin.snap, libs/wingc/src/type_check.rs
Closes #2625
First pass, provides some bare-bones functionality. Note this is only for non-constructor function sigs.
https://github.com/winglang/wing/assets/1237390/28be217e-7f80-48e4-9491-a7b9db9ae676
- Threw in a fix for missing completions for std lib types. Closes #2711 and Closes #2593
- https://github.com/winglang/wing/issues/2747 Show help for constructors, slightly non-trivial compared to regular calls
- https://github.com/winglang/wing/issues/2749 Show param names 
- Need to figure out how to show struct expansion help
- Show param docs (partially waiting on https://github.com/winglang/wing/pull/2534)
*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contributio …
=> feat(vscode): show signature help

apps/vscode-wing/.projenrc.ts, apps/vscode-wing/package.json, libs/wingc/src/lsp/signature.rs, libs/wingc/src/lsp/snapshots/signature/named_arg_active.snap
Fixes #2538
Misc: Also improved the signature text to use proper syntax
=> fix(vscode): vscode extension doesn't come up when searching 'winglang`

apps/wing-playground/package-lock.json, apps/wing/package-lock.json, apps/wing/package.json, apps/wing/src/commands/test.ts, apps/wing/src/util.ts, tools/hangar/__snapshots__/test_corpus/purge.w_compile_tf-aws.md
fixes: #2789 
* using fs instead of fs-extra in the cli
* creating snapshots and running build
=> fix(cli): fixing cli failure -  cannot find module 'fs-extra'

examples/README.md
Fixing broken link to Wing Contributor's Handbook.
=> fix(docs): fixing link in examples readme

.github/workflows/build.yml
Increase build timeout by 15 minutes, seems 30mins is not reliably long enough anymore. 
=> chore(build): increase build timeout

examples/tests/sdk_tests/schedule/on_tick.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/schedule/on_tick.w_compile_tf-aws.md
Since our code is async, sleeping for one minute guarantees we have waited at least that long, but it could be longer depending on CPU scheduling.
=> fix(build): flakey on_tick test

libs/tree-sitter-wing/package.json
Adds `-y` parameter to `npx` so it installs `tree-sitter-cli` automatically.
=> chore: fix `tree-sitter-wing` hanging on some scripts

libs/wingc/src/lib.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check_assert.rs
I realized I introduced a small bug in my last PR [here](https://github.com/winglang/wing/pull/2860) - inside the main compiler pipeline (inside `compile.rs`) I added a call to `check_all_exprs_type_checked`, but didn't actually check the result. When we do check the result, it claims many AST nodes that are not type checked because it's looking at all `Expr`'s that have ever been created - but the reason for that is that some `Expr`'s nodes get thrown away. For example, in this snippet of Wing code:
```js
enum Foo { A, B }
let a = Foo.A;
```
We initially parse the expression in the last statement as something like
```js
Expr(Ref::InstanceMember(Expr(Ref::Identifier("Foo")), "A"))
```
But it's converted into this during type checking
```js
Expr(Ref::TypeMember(UserDefinedType("Foo"), …
```
=> fix(compiler): type check assertion is ignored

examples/tests/invalid/unknown_field.w, examples/tests/invalid/unknown_submodule.w, libs/wingc/src/type_check/jsii_importer.rs, libs/wingc/src/type_check/symbol_env.rs, tools/hangar/__snapshots__/invalid.ts.snap
Fixes #2602 by avoiding the creation of namespaces blindly, even if a type doesn't exist in that namespace.
Additionally fixes #2877 which was caused by mistakenly associating its symbol environment with the parent submodule, but that's not actually what we want. If I couldn't find `String` in `std.foo`, I don't want to look up string in `std`. The diagnostics emitted in this case is still weird, so I created #2876 to address this.
=> fix(compiler): panic when trying to reference an unknown field

.devcontainer/devcontainer.json, .github/workflows/build.yml, .github/workflows/wingsdk-mutation.yml
Fixes #2590
Volta was causing too many intermittent issues in CI. I kept it in the docs locally because I still think it's really great, but I'm open to removing it from there as well if it's causing enough issues for others. 
Removed from the devcontainer as well, which helps because it let's us use `postCreateCommand` and `updateContentCommand` which will be great if we want to start doing prebuilds. Verified the change locally.
The only real downside of this change is that now the node/npm version is duplicated, but I think the tradeoff is worth it.
=> chore: remove volta from ci

apps/wing/src/commands/compile.ts, examples/tests/invalid/diags_with_multibyte_chars.w, tools/hangar/__snapshots__/invalid.ts.snap
Multi byte chars in the code (mostly in comments) lead to wrong spans being produced for diagnostics:
This test:
```wing
// Here we have some multibyte haiku which we'll use to verify
// the reported diagnostics point to the correct location (line 4 column 1)
// 古池や蛙飛び込む水の音
asdf;
//^^ Unknown symbol "asdf"
```
Produced this wrong output before the fix:
We now calculate the byte offset of the diags which is what our diag reporting tool ([codespan-reporting](https://crates.io/crates/codespan-reporting)) expects instead of the character offset.
=> fix(compiler): invalid code location in errors when using multibyte chars

libs/wingc/src/lsp/completions.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/jsii_importer.rs
Due to the jsii type lazy loading, completions only show types that were used in the current file. We now eagerly load namespaces when referenced (even if incomplete).
For example:
```
bring "aws-cdk-lib" as awscdk;
new awscdk.aws_lambda.
//^ completions will show here
```
https://github.com/winglang/wing/assets/1237390/d6edeee2-8c64-428d-a2ef-0aa51b5e3b96
- I couldn't think of a reasonable way to test this, the lsp tests need a good jsii fixture system
- refactored some code into a `reference_to_udt` and as part of it, allowed a udt to basically refer to a namespace
- We also now also eagerly load jsii types that don't belong to a namespace, just to cover that base
Fixes #2639
- See notes above 
*By submitting this pull request, I confirm that my contribution is made under the terms of …
=> fix(vscode): missing completions in lazy-loaded jsii namespaces

.github/workflows/build.yml, libs/wingsdk/project.json
`post-compile` requires `compile` to run, so we might as well run the whole build step.
=> chore: wingsdk requires build before test

tools/bump-pack/src/bump.ts, tools/bump-pack/src/cli.ts
Another followup to https://github.com/winglang/wing/pull/2992
Switched back to using PROJEN_BUMP_VERSION, which is what the original script used. The issue with the last change probably was that we were trying to regenerate the version/changelog and it was failing. Using the existing variable should work and it's faster anyways.
Also explicitly added a little log, which shouldn't hurt.
=> chore: use PROJEN_BUMP_VERSION for versioning

libs/wingc/src/diagnostic.rs, libs/wingc/src/jsify.rs, libs/wingc/src/lib.rs, libs/wingc/src/lsp/sync.rs
Certain errors were not available in the lsp because we didn't run the jsify phase. This PR changes that and also avoids many panics. 
So far it seems the perf overhead of running jsify in the lsp is minimal. On my PC, it adds between 1ms and 8ms. This time scales with classes/inflight/externs.
=> fix: capture diagnostics missing from language server

.github/workflows/canary.yml
The `echo "foo=bar" >> $GITHUB_ENV` syntax doesn't work in powershell, which is the default shell for Windows jobs. Running the the job step in bash should fix it.
=> fix(build): canary job step no-ops on Windows

libs/wingcompiler/src/wingc.ts
Drive A and B are typically reserved for floppy drives. Making sure we have a preopen available for them is error-prone. If someone wants to load their node modules from a floppy then they can file an issue.
See related canary failure https://github.com/winglang/wing/actions/runs/5345295516/jobs/9690782570
=> fix: windows really wants to load stuff from a floppy drive

libs/wingsdk/patches/@aws-sdk+util-utf8-browser+3.259.0.patch, libs/wingsdk/patches/@aws-sdk+util-utf8-node++@aws-sdk+is-array-buffer+3.201.0.patch, libs/wingsdk/patches/@aws-sdk+util-utf8-node++@aws-sdk+util-buffer-from+3.208.0.patch, libs/wingsdk/patches/@aws-sdk+util-utf8-node+3.259.0.patch
So you may be looking at the diff and saying out loud "get this disgusting change out of my face" but hold on, I have a reason.
`@aws-sdk/util-utf8-node` and `@aws-sdk/util-utf8-browser` are bundled dependencies of the SDK. Both of them have a typo in the package.json `files` field. `"dist-*"` is supposed to designate all of the `dist-*` folders **and** their content. On linux, this works fine. On mac, it does not include these files. This matters when you try to run the equivalent of the ci on mac (basically `npm pack`) because these packages are missing those files. `"dist-*/**"` works for both OSes, and it's what other `@aws-sdk` do as well.
The reason there are 4 patches is because `@aws-sdk/util-utf8-node` also bundles 2 deps of its own with the same problem lol.
This change does not …
=> chore: ensure bundled deps are actually fully bundled on mac

.github/workflows/mutation.yml
=> chore: mutation workflow always pulls from the main repo

apps/wing-console/console/app/web/index.tsx, apps/wing-console/console/ui/src/AppContext.ts, apps/wing-console/console/ui/src/Console.tsx, apps/wing-console/console/ui/src/ui/api-interaction.tsx
when running the console locally (`wing it` for example), show the api resource url in the api interaction panel
resolves: https://github.com/winglang/wing/issues/3108
=> fix(console): show url for api resource when running the console locally

examples/tests/valid/json.w, libs/wingsdk/src/std/json.ts, tools/hangar/__snapshots__/test_corpus/valid/json.w_compile_tf-aws.md
😅 I forgot to make the optional part optional in javascript for the Json Macros
This uses `?.` to index the objects in javascript when calling `tryGet` or `tryGetAt` on Json and MutJson
Closes: https://github.com/winglang/wing/issues/3106
=> fix(sdk): tryGet optional chaining with nil members

.github/workflows/mutation.yml, docs/contributing/01-start-here/06-pull-requests.md
Other than security, I now remember the other reason we use a MUTATION_TOKEN rather than GITHUB_TOKEN: Github will not trigger push/pull_request events if a commit is pushed by github actions. We should try to find a way around this, but in the mean time let's go back to using a token
=> chore: self mutation does not trigger build

apps/wing-console/console/app/scripts/dev.mjs, apps/wing-console/console/app/scripts/preview.mjs
console dev scripts didn't provide the proper hosting utils functions to open url in external browser windows
resolves: https://github.com/winglang/wing/issues/3066
=> fix(console): open url in external browser window

apps/wing/src/commands/test.ts
for debugging why does the SDK spec tests command fail
=> fix(cli): logging stdout

docs/docs/02-concepts/_category_.yml, docs/docs/03-language-guide/_category_.yml, docs/docs/04-standard-library/_category_.yml, docs/docs/06-tools/_category_.yml, docs/docs/07-examples/_category_.yml, docs/docs/08-guides/_category_.yml
This PR makes all the documentation folders linkable so we can direct to them from tutorials and elswhere.
For example, we'd like to link to the documentation of Wing's core concepts from the main tutorial. With this tutorial the link would be to https://winglang.io/docs/core-concepts
=> chore(docs): make all documentation folders linkable

apps/wing-console/console/ui/src/layout/tutorial-layout.tsx
Fixes #3191 by reducing the defualt size of the logs view by half
=> fix(console): tutorial - function invoke button not visible on small screens

apps/wing-console/console/design-system/src/utils/icon-utils.ts, apps/wing-console/console/server/src/router/index.ts, apps/wing-console/console/server/src/router/website.ts, apps/wing-console/console/server/src/utils/createRouter.ts, apps/wing-console/console/server/src/wingsdk.ts, apps/wing-console/console/ui/src/features/resource-interaction-view.tsx, apps/wing-console/console/ui/src/features/website-interaction-view.tsx, apps/wing-console/console/ui/src/services/use-website.ts, apps/wing-console/console/ui/src/ui/elk-map-nodes.tsx, apps/wing-console/console/ui/src/ui/website-interaction.tsx
add website resource support to the console.
users can open the website url in a different browser tab from the website resource interaction view
resolves: https://github.com/winglang/wing/issues/2973
=> feat(console): website resource

.github/workflows/build.yml
Before this PR build automation was not trigger on libs/wingsdk/src/cloud/*.md which caused issues (for example https://github.com/winglang/wing/actions/runs/5452545128)
Used paths instead of ignore paths following this doc (https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-and-excluding-paths) don't know how to test this
=> fix: build should be triggered when changing libs/wingsdk/src/cloud/ md files

libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/snapshots/completions/optional_chaining_auto.snap, libs/wingc/src/lsp/snapshots/completions/type_annotation_shows_struct.snap
https://github.com/winglang/wing/assets/1237390/b86d3748-7d83-4c6b-a163-589afad01cda
Fixes #3143
Fixes #3306
=> feat(vscode): insert `?.` automatically and ensure structs and enums show up in type completions

apps/wing-console/console/ui/src/layout/layout-provider.tsx, apps/wing-console/console/ui/src/layout/tutorial-layout.tsx, apps/wing-console/console/ui/src/ui/bucket-interaction.tsx
This PR reduced back the default height of the logs, for the learn layout.
=> fix(console): default height for logs in learn site

apps/vscode-wing/README.md
The vscode extension's readme shows an incorrect command for installing wing.
Shows:
```sh
npm install -g @winglang/wing
```
Should instead be:
```sh
npm install -g winglang
```
Fixes #2380 
=> fix(vscode): extension's readme shows a wrong wing install command

docs/docs/04-standard-library/02-std/api-reference.md, libs/wingc/src/lsp/snapshots/completions/mut_json_methods.snap, libs/wingc/src/lsp/snapshots/completions/optional_chaining.snap, libs/wingc/src/lsp/snapshots/completions/optional_chaining_auto.snap, libs/wingc/src/lsp/snapshots/completions/parentheses_expression.snap, libs/wingsdk/src/std/json.ts
Fixing some typos in `json` method docstrings, reported by Jordin Gardner [here](https://winglang.slack.com/archives/C048QCN2XLJ/p1688619629755739?thread_ts=1688597325.876739&cid=C048QCN2XLJ).
=> chore(sdk): typos in json method signatures

docs/docs/01-start-here/06-learn-more.md
Add some meet on the 'learn more' page in the docs.
Fixes: #3325
=> chore(docs): beef up the learn more page

apps/wing-console/console/app/src/analytics.ts, apps/wing-console/console/app/src/index.ts
align analytics events names and data to Segment
part of: https://github.com/winglang/wing/issues/3321
=> chore(console): analytics events data

apps/wing/package.json, apps/wing/src/analytics/collect.ts, apps/wing/src/analytics/collectors/ci-collector.ts, apps/wing/src/analytics/collectors/cli-collector.ts, apps/wing/src/analytics/collectors/collector.ts, apps/wing/src/analytics/collectors/git-collector.ts, apps/wing/src/analytics/collectors/node-collector.ts, apps/wing/src/analytics/collectors/os-collector.ts, apps/wing/src/analytics/disclaimer.test.ts, apps/wing/src/analytics/disclaimer.ts, apps/wing/src/analytics/event.ts, apps/wing/src/analytics/export.ts, apps/wing/src/analytics/scripts/detached-export.ts, apps/wing/src/analytics/storage.test.ts, apps/wing/src/analytics/storage.ts, apps/wing/src/cli.ts, docs/docs/07-examples/14-wing-analytics.md, docs/docs/09-analytics.md, pnpm-lock.yaml, tools/hangar/src/utils.ts
Currently this PR introduces some recorded analytics that can be opted out of using `WING_DISABLE_ANALYTICS` env var. 
Here are some example analytics:
- User running from non git repo
- User running from git repo
- Note `anonymous_repo_id` has been added
- Automation running in CI
- Note `anonymous_repo_id` is added
- Note `anonymous_id` says 'ci_run' 
In order to ensure we are not slowing down the user experience when running any CLI command, the process for collecting metrics works in 3 main components. Similar to how other CLI tools I have come across collect metrics. 
- Collectors: Which is responsible for gathering up all the analytics we care about during runtime of the CLI.
- Storage: The analytics gathered by the collector are stored on disk. The storage will house the events …
=> feat(cli): collect analytics

.github/workflows/mutation.yml
Labeling during self mutation was added as a cautionary method but seems like it is not working for PRs from forks. This is because github context does not return pull request data (at least in this case) and so there is no way to form the proper url for rest api call using just github context. Instead retrieve the PR number with a rest api call and use it. Also change the labeling to after mutation commit.
Modified the step to use script module instead of run as per @MarkMcCulloh's suggestion.
fixes #3391.
=> fix: labeling during self mutation not working for pull requests from forks

libs/wingsdk/src/shared-aws/function.ts
Fixes #3396
This "instanceof" check is causing problems since it results in several other modules to get imported, including those that require `aws-cdk-lib` to be installed -- even if you're not compiling to the `awscdk` target. Removing this code path as a hotfix.
=> fix(cli): breaks without globally installed aws-cdk-lib

docs/docs/07-examples/04-flow-controls.md
It's "flow control" instead of "flow controls"
=> chore: fix topic title

apps/vscode-wing/syntaxes/wing.tmLanguage.json
This highlights `10ms` in addition to the already existing durations `s`, `m`, and `h`.
=> fix(vscode): highlight ms durations

apps/wing-console/console/server/src/utils/getWingVersion.ts
=> chore(console): clean version prints to console

docs/docs/04-standard-library/01-cloud/schedule.md, examples/tests/sdk_tests/bucket/events.w, examples/tests/sdk_tests/external/sleep.js, examples/tests/sdk_tests/queue/purge.w, examples/tests/sdk_tests/queue/set_consumer.w, examples/tests/sdk_tests/schedule/on_tick.w, examples/tests/sdk_tests/topic/on_message.w, libs/wingsdk/src/cloud/schedule.md, libs/wingsdk/src/cloud/schedule.ts, libs/wingsdk/src/target-sim/schedule.inflight.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/events.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/purge.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/set_consumer.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/schedule/on_tick.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/topic/on_message.w_compile_tf-aws.md
Fixes #3120
* Since translating a cron expression from one timezone to another is pretty tough, I also adjusted the local schedule to be in the UTC timezone.
* Removed external sleep.js and replaces it with `util.sleep` 
=> fix(sdk): adjust local schedule to UTC

apps/wing/src/cli.ts
Look.. merge conflicts are hard man 😅 
This exporthook call was supposed to be removed in my previous fix but my best guess is when I resolved a conflict I goofed and left the original call.
Closes: https://github.com/winglang/wing/issues/3423
=> fix(cli): removed duplicate export hook call

apps/wing/src/commands/compile.ts, apps/wing/src/commands/lsp.ts, libs/wingcompiler/src/wingc.ts
=> fix(vscode): lsp crashes when a non-spanned diagnostics is encountered

docs/docs/09-analytics.md
The analytic docs were using the original env var for opting out. Since then the `CLI` term was removed.
=> fix(docs): analytic opt-out env var outdated

apps/vscode-wing/syntaxes/wing.tmLanguage.json
Regression from https://github.com/winglang/wing/pull/3404
=> fix: invalid vscode highlight syntax

docs/docs/02-concepts/03-compile-targets.md
=> fix(docs): typo in docs

examples/proposed/url-shortener.js, examples/proposed/url-shortener.w
The url shortener example was not compiling.
=> fix: url shortener not compiling

Cargo.toml, libs/wingii/src/util.rs
This affected performance of JSII loading.
Profiled using:
`cargo flamegraph --profile flamegraph --freq 20000 --example compile -- ../../examples/tests/valid/hello.w`
Results show that wingii's  `load_module` previously took 40% of the compilation time and now is down to 30%.
This PR also adds a profile to our `Cargo.toml` that's more compatible with `cargo flamegraph` (see the command above).
*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.
=> fix(compiler): (performance) duplicate JSII deps are loaded more than once   

.github/workflows/mutation.yml, .github/workflows/release-commenter.yml
Added the release commenter back in, but now ignoring any PRs with the pr/backport label.
Also disabled any pr mutations from happening on the dev branch.
*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.
=> chore: add release commenter back in

examples/tests/invalid/call_inflight_from_preflight.w, libs/wingc/src/lsp/snapshots/completions/namespace_inflight.snap, libs/wingc/src/lsp/snapshots/completions/util_static_methods.snap, libs/wingc/src/type_check/jsii_importer.rs, tools/hangar/__snapshots__/invalid.ts.snap
`@inflight` docstring on methods was ignored by the jsii_importer. This meant that it was possible to call inflight util functions (such as `util.waitUntil`) from preflight. Now you receive an appropriate compiler error.
*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.
=> fix(compiler): `@inflight` docstring on methods was ignored by the jsii_importer 

libs/wingsdk/src/target-tf-aws/bucket.ts, libs/wingsdk/test/target-tf-aws/__snapshots__/bucket.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/website.test.ts.snap, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/public_url.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/website/website.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/captures.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/website_with_api.w_compile_tf-aws.md
This was a super nasty bug to track down since it's apparently working on MacOS but randomly failing on Linux (i.e. Github Actions). Due to this, I went down a few other rabbit holes but eventually was able to isolate it. There are also a few issues in the AWS Provider repo about this, where the explicit dependency is also [mentioned](https://github.com/hashicorp/terraform-provider-aws/issues/31363#issuecomment-1588091658) as the way forward here. 
With this minimal case, I'm able to reproduce this on `ghcr.io/winglang/wing-github-action:v0.1.0`.  The unscientific test with the minimal example and applying / destroying 10 times in a row:
1. Linux (Docker) 3/10 failed
2. Mac 0/10 failed (might fail if run a 100 times, don't know)
With more Terraform resources, the failure rate on Linux …
=> fix(sdk): bucket needs to be marked as public before adding a public policy

docs/contributing/01-start-here/01-contributing-to-wing.md
Github automatically promotes issues labeled as `good first issue` to github users. By adding an emoji, we may have prevented that automatic promotion. Removing the emoji and updating the contributing guide.
=> chore(docs): good first issue emoji removed

.mergify.yml
Small workflow updates are needed as well, but I wanted to wait on those as a follow-up just in case a re-freeze is needed quickly.
Un-freeze procedures:
1. [ ] Merge this
2. [ ] Freeze merge queues
3. [ ] Create and manually merge backport of this change to main
4. [ ] Lock main/dev
5. [ ] Set main as default branch
6. [ ] Rebase dev onto main
7. [ ] Wait for build to hopefully succeed and publish
8. [ ] Do some manual testing to see if things are busted with the published build
9. [ ] Change the base branch of open PRs to main
10. [ ] Unlock main and its merge queue
11. [ ] Post to slack
12. [ ] Remove misc mentions of dev branch in build/mutation workflow
13. [ ] Monitor
14. [ ] Delete dev branch and its protections
=> chore: unfreeze main branch

apps/wing-console/console/app/src/analytics.ts
our analytics crashed and caused the console server to crash as well.
resolves: https://github.com/winglang/wing/issues/3598
=> fix(console): console crash when running offline

examples/proposed/url-shortener.w
The URL shortener example as its written has a race condition because it's trying to ensure that every URL gets a unique shortened ID. If we relax this constraint (which is reasonable in practice), then the race condition is avoided and we can simplify the implementation.
Closes #2823
=> chore: simplify url-shortener example

examples/tests/valid/structs.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/test_corpus/valid/structs.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/structs.w_test_sim.md
Resolves a fun bug where structs were not always phase independent example
```js
struct A {
val: str
}
struct B extends A {
val2: num
}
test "blah" {
let b = B { val: "cool", val2: "beans" };
assert(b.val == "cool");
}
```
would result in an error where the compiler believed `b` was preflight expression
=> fix(compiler): struct definitions were not phase independent

docs/docs/03-language-reference.md, docs/docs/04-standard-library/02-std/api-reference.md, examples/tests/sdk_tests/std/datetime.w, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/jsii_importer.rs, libs/wingsdk/src/std/datetime.ts, libs/wingsdk/src/std/index.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/std/datetime.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/std/datetime.w_test_sim.md
closes #2102 
(besides adding the type mapping, opened a separate issue: https://github.com/winglang/wing/issues/3569)
a wing test added, checked both preflight and inflight both in tf-aws and sim.
=> feat(sdk): adding `datetime` type

apps/wing-console/console/design-system/package.json, apps/wing-console/console/design-system/src/loader.tsx, apps/wing-console/console/design-system/src/spinner-loader.tsx, apps/wing-console/console/ui/package.json, apps/wing-console/console/ui/src/layout/status-bar.tsx, apps/wing-console/console/ui/src/layout/vscode-layout.tsx, pnpm-lock.yaml
Reduces the bundle size of `@wingconsole/app` about 600 KB by removing the lottie player package, which is only used in a very small loading animation.
Closes #3615.
=> chore(console): remove lottie player

libs/wingsdk/src/shared-aws/bucket.inflight.ts, libs/wingsdk/src/shared-aws/permissions.ts, libs/wingsdk/test/shared-aws/bucket.inflight.test.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/delete.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/exists.w_compile_tf-aws.md
I was randomly thinking that using `ListObjectsV2Command` may not be the most efficient way to check if an object exists in a S3 bucket, since you are asking AWS to look for all the objects that have a specific prefix even though the API returns only one object when filtering with `MaxKeys: 1`. I thought that probably just checking for the metadata of the single object using `HeadObjectCommand` would be enough to determine whether the object exists.
=> chore(sdk): optimizing `bucket.exists()` for aws targets

apps/wing/src/cli.ts, apps/wing/src/commands/test.ts, docs/docs/02-concepts/04-tests.md
=> feat(cli): disable test cleanup with a `--no-clean` flag

.github/workflows/build.yml
The docsite repository needs the `docs.tgz` asset to update.
=> chore: restore `docs.tgz` asset in the github release

examples/tests/invalid/inference.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap
Fixes #3714
When making an inference in type validation, the inferred type was originally thrown away. This change instead unwraps it if needed since updating the original typeref itself won't happen til later. It's worth noting the error message will be missing information for deeply inferred types (like the return type).
Also it turns out this regression was noticeable in the snapshots before, but not noticed. So the snapshot update included 2 changes.
=> fix(compiler): missing type check for partially inferred function

docs/contributing/01-start-here/06-pull-requests.md, docs/docs/04-standard-library/01-cloud/bucket.md, docs/docs/04-standard-library/02-std/api-reference.md, docs/docs/04-standard-library/03-http/api-reference.md, docs/docs/04-standard-library/06-ex/api-reference.md, libs/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap, libs/wingc/src/lsp/snapshots/completions/namespace_inflight.snap, libs/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap, libs/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap, libs/wingsdk/.eslintrc.json, libs/wingsdk/.projenrc.ts, libs/wingsdk/src/cloud/api.ts, libs/wingsdk/src/cloud/bucket.ts, libs/wingsdk/src/core/plugin-manager.ts, libs/wingsdk/src/ex/table.ts, libs/wingsdk/src/http/http.ts, libs/wingsdk/src/shared-aws/bucket.inflight.ts, libs/wingsdk/src/std/datetime.ts, libs/wingsdk/src/std/resource.ts, libs/wingsdk/src/target-awscdk/app.ts, libs/wingsdk/src/target-awscdk/topic.ts, libs/wingsdk/src/target-sim/queue.inflight.ts, libs/wingsdk/src/target-sim/service.ts, libs/wingsdk/src/target-sim/topic.inflight.ts, libs/wingsdk/src/target-tf-aws/function.ts, libs/wingsdk/src/target-tf-aws/topic.ts, libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap, libs/wingsdk/test/target-tf-azure/bucket.inflight.test.ts
Following @Chriscbr's comment: https://github.com/winglang/wing/pull/3570#discussion_r1276452117
I added those two rules to the SDK's linter and ran it once to apply them.
The added regulations are:
* capitalizing comment- makes sure comments and doc strings are capitalized
* explicit member accessibility- makes sure that all methods and properties are marked with the right member accessibility- public, protected, or private
I also added a sentence to the docs referring to the importance of docstrings, which should be capitalized.
=> chore(sdk): adding eslint rules for capitalize comment and explicit member accessibility

examples/tests/invalid/optionals.w, examples/tests/sdk_tests/bucket/delete.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/delete.w_compile_tf-aws.md
Fixes #3713
Seems to have existed prior to the big inference changes
=> fix(compiler): optional function args are not type checked

libs/wingc/src/lib.rs, libs/wingc/src/lifting.rs, libs/wingc/src/lsp/sync.rs, tools/hangar/__snapshots__/invalid.ts.snap
This is a small cleanup changing `LiftTransform` to a `LiftVisitor`. Using a `Fold` trait for this is a leftover of an older iteration on #3213, we can now simplify things using just a `Visit` trait.
=> fix(compiler): no need to transform the AST for lifting

docs/docs/04-standard-library/02-std/api-reference.md, examples/tests/invalid/container_types.w, examples/tests/valid/container_types.w, libs/wingc/src/type_check.rs, libs/wingsdk/src/std/array.ts, libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/container_types.w_compile_tf-aws.md
There are several open issues in progress that need to be able to define generic optionals. 
Such as: 
- https://github.com/winglang/wing/issues/1868
- https://github.com/winglang/wing/issues/3575
- https://github.com/winglang/wing/issues/3653
I only added `tryAt` method for Array since the actual work is defined in another issue, but I needed an example to write some test cases with. Since there are several efforts that need this change I opted to not wait and include it in one of those PRs but just add the support here so other efforts can rebase.
=> fix(compiler): could not hydrate optionals

docs/docs/03-language-reference.md
Adds "Wing Programming" to title for SEO suggested change
See: https://github.com/winglang/wing/issues/3164
=> chore(docs): change title to "Wing Programming Language Reference"

.github/workflows/tf-aws-test.yml
Thanks to @skorfmann's amazing [code](https://github.com/winglang/examples/blob/main/.github/workflows/wing-sdk.yml), I managed to split the SDK spec tests to run in parallel on a few machines based on the tests directory!
Cannot be deployed before #3723 
finally fixes #2689! 🥳 
It looks like that:
=> feat(sdk): parallel sdk spec testing via gh action

docs/docs/03-language-reference.md
@marciocadev did a great job adding variadic arguments to the language on #3643. 
In this small PR I'm making sure the language reference is updated with the variadic arguments section.
=> chore(docs): variadic args section in language ref

docs/docs/04-standard-library/01-cloud/queue.md, libs/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap, libs/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap, libs/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap, libs/wingsdk/src/cloud/queue.ts, libs/wingsdk/src/target-awscdk/queue.ts, libs/wingsdk/src/target-sim/queue.inflight.ts, libs/wingsdk/src/target-sim/queue.ts, libs/wingsdk/src/target-sim/schema-resources.ts, libs/wingsdk/src/target-tf-aws/queue.ts, libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/file-counter.test.ts.snap, libs/wingsdk/test/target-sim/__snapshots__/queue.test.ts.snap, libs/wingsdk/test/target-sim/queue.test.ts
Removes the `initialMessages` property from `cloud.Queue` to reduce API surface area in the standard library. This capability has only worked on the `sim` target to date, and it's possible to easily achieve the capability (across clouds) using `cloud.OnDeploy`:
```js
bring cloud;
let queue = new cloud.Queue();
new cloud.OnDeploy(inflight () => {
queue.push("hello");
queue.push("world");
});
```
This style of API would have more merit if it's something we could provided an optimized implementation for, but it doesn't appear there are dedicated Terraform resources available that represent AWS SQS messages or Google PubSub items. `OnDeploy` also offers more flexibility since it allows the user to dynamically calculate the queue's initial messages based on the results of other inflight …
=> feat(sdk)!: remove cloud.Queue initialMessages

libs/wingc/src/ast.rs, libs/wingc/src/lifting.rs, libs/wingc/src/type_check/symbol_env.rs, libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap
This is a tiny fix removing dead capturing code. For some reason there's code that tries to capture the parent class of a inflight class in the irrelevant case that we're inside an inflight context. In this case the code is dead because an inflight class within an inflight class generates inlined code.
The PR also adds some coloring improvements to the env printing I used to debug this and fixed a comment related to parent class capturing.
=> fix(compiler): remove some dead capturing code

.github/workflows/tf-aws-test.yml
From the few runs I looked into, it seems like the reason for failure is either a network error installing wing (is it blocked by NPM in any way?) or occasional fails in the tests themselves...
I added a retry option to make them more stable:
https://github.com/winglang/wing/actions/runs/5818534372 
=> chore(sdk): adding auto retry to the sdk gh workflow

docs/docs/04-standard-library/01-cloud/counter.md
doc updated in wrong area
Reverts winglang/wing#3633
=> revert(docs): added “distributed” to the counter title

libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/website.test.ts.snap, libs/wingsdk/test/util.ts
Fixing the source_hash in the sdk snapshots to be a string and not a path
=> fix(sdk): fix website source_hash

apps/wing-console/console/server/src/index.ts, libs/wingsdk/src/testing/simulator.ts
Fixes #3492 
* Happened because of un-handled SIGINT termination
* Prevented the simulator from being started twice (perhaps more work is needed- for stopping compilation from happening twice)
* Changed the error to a warning while cleaning resources- to be able to clean later resources if one fails
Here is the result:
https://www.loom.com/share/56bddc36c7724d3589a23aebf1141f7a
=> fix(sdk): kill all redis zombies

libs/wingsdk/src/shared-aws/queue.inflight.ts, libs/wingsdk/test/shared-aws/queue.inflight.test.ts
Added error handling for invalid messages in `Queue.push()` following [AWS documentation](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html).
=> feat(sdk): `queue.push()` can now handle invalid messages for aws targets

docs/docs/src/examples/function-upload-to-bucket/wing.js
The comparison to other solution pages shows `hello.js` file with wing code inside.
I believe it's by mistake and it should by `hello.w`
=> fix(docs): wing filename in comparison pages

.mergify.yml
idk why I thought the `@` was part of the interpolation syntax
=> chore(repo): typo in mergify queue message

examples/tests/valid/std_containers.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/std_containers.w_compile_tf-aws.md
Fixes #3883
Removed a function that didn't really do much, added some comments, and generally tweaked the type-checking for literals
=> fix(compiler): unable to create array of valid heterogeneous values

docs/docs/04-standard-library/01-cloud/queue.md, libs/wingsdk/src/cloud/queue.md
Show in the `cloud.Queue` example that you can push multiple messages at once if you want.
=> chore(docs):  add push batch to `cloud.queue` example in the docs

apps/wing-console/console/ui/src/ui/edge-metadata.tsx
Edge metadata panel  is not showing the correct background color.
vs
=> feat(console): improve vs-code theme sync

apps/wing-console/console/app/demo/index.w, apps/wing-console/console/ui/src/Console.tsx
Fixes clipboard actions (copy, paste, select-all) for Console inside VS Code.
There is an open issue in vscode repo https://github.com/microsoft/vscode/issues/129178 talking about same problem.
solves https://github.com/winglang/wing/issues/3904
=> fix(console): capture keydown events to handle clipboard actions inside vs-code

.github/workflows/pull-request-lint.yml
I removed synchronize since it didn't make sense at first, the PR title didn't change so why rerun? Well now I know the answer is because otherwise a new status won't be created for the new commit.
=> chore(repo): pr title linter must run on synchronize

.github/workflows/build.yml
Seems the array was not being expanded properly and instead of iterating over each element it was treated as a single string. This syntax does work is zsh shells but probably is not bash compliant. This fix hopefully fixes the issue of only sdk package being uploaded to npm.
=> fix: publish job not publishing all npm packages

apps/wing-console/console/ui/src/layout/layout-provider.tsx
Removes the theme toggle from the footer for the playground layout.
Before
After
=> feat(console): remove theme toggle for playground

docs/docs/02-concepts/01-preflight-and-inflight.md, docs/docs/03-language-reference.md, examples/tests/error/utilities.w, libs/wingc/src/ast.rs, libs/wingc/src/lib.rs, libs/wingc/src/lsp/snapshots/completions/call_struct_expansion.snap, libs/wingc/src/lsp/snapshots/completions/call_struct_expansion_partial.snap, libs/wingc/src/lsp/snapshots/completions/empty.snap, libs/wingc/src/lsp/snapshots/completions/only_show_symbols_in_scope.snap, libs/wingc/src/lsp/snapshots/completions/struct_literal_value.snap, tools/hangar/__snapshots__/test_corpus/valid/debug_env.w_test_sim.md
> Don't panic! Stay cool...
This minor breaking change was staring at me for too long - better remove `panic()` before anyone starts using it.
Closes #2055
=> chore(compiler)!: remove panic built-in method

examples/tests/valid/optionals.w, libs/tree-sitter-wing/grammar.js, tools/hangar/__snapshots__/test_corpus/valid/optionals.w_compile_tf-aws.md
@MarkMcCulloh, your review on PR #3888 made me realize that if I put more than one space between `if let`, it generates errors.
I've updated the `if let` to work even with extra spaces.
Closes #3959 
=> fix(compiler): error when more than one space is placed between `if` and `let`

libs/wingsdk/src/target-tf-aws/api.ts, libs/wingsdk/test/target-tf-aws/__snapshots__/tokens.test.ts.snap, tools/hangar/__snapshots__/test_corpus/sdk_tests/api/delete.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/api/get.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/api/options.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/api/patch.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/api/post.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/api/put.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/api.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/api_path_vars.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/api_valid_path.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/capture_tokens.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/captures.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/inference.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/issue_2889.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/website_with_api.w_compile_tf-aws.md
Makes the code simpler and doesn't require to build keep two identical versions of the openapi spec
=> fix(sdk): defer hash calculation of api spec to terraform

apps/wing-console/console/app/test/describe.ts, libs/wingsdk/src/target-sim/api.inflight.ts, libs/wingsdk/src/target-sim/website.inflight.ts
Fixes #3709
`.close()` keeps existing connections alive, and those connections prevent the node process from closing.
Misc:
- https://github.com/winglang/wing/pull/3964 Caused a failure in the playwright tests. I'm not sure why it would only fail sometimes, but I don't think there's a need to wait for the loading animation, regardless.
=> fix(sdk): connections are kept alive in api/website simulator

examples/tests/valid/bring_cdk8s.w, examples/tests/valid/package.json, libs/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap, libs/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap, libs/wingc/src/lsp/snapshots/completions/util_static_methods.snap, libs/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap, libs/wingc/src/type_check/jsii_importer.rs, pnpm-lock.yaml, tools/hangar/__snapshots__/test_corpus/valid/bring_cdk8s.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/bring_cdk8s.w_test_sim.md
Fixes #3716
The core of this change is to make sure that when importing an interface, the type itself is registered before importing the types that it extends. Previously it was the opposite way. 
I will say that I'm not sure why this works, the previous implementation makes more sense to me 🤷 
No tests were added because I was not able to replicate the issue in other JSII libs other than `cdk8s-plus-27` so I wasn't sure that it's worthwhile to add an additional package just to test this. We also don't have a fixture system for JSII testing.
Misc:
- Made sure the imported (actual) interfaces also get their extended properties. Not sure if this was intentionally left out before
*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud …
=> fix(compiler): missing extended struct fields for some imported JSII interfaces

apps/vscode-wing/syntaxes/wing.tmLanguage.json, docs/docs/03-language-reference.md, examples/proposed/counting-semaphore.w, examples/proposed/task-manager.w, examples/tests/error/utilities.w, examples/tests/invalid/throw_non_string.w, examples/tests/sdk_tests/util/wait-until.w, examples/tests/valid/dynamo.w, examples/tests/valid/dynamo_awscdk.w, examples/tests/valid/try_catch.w, libs/tree-sitter-wing/grammar.js, libs/wingc/src/ast.rs, libs/wingc/src/fold.rs, libs/wingc/src/jsify.rs, libs/wingc/src/lib.rs, libs/wingc/src/lsp/hover.rs, libs/wingc/src/lsp/snapshots/completions/call_struct_expansion.snap, libs/wingc/src/lsp/snapshots/completions/call_struct_expansion_partial.snap, libs/wingc/src/lsp/snapshots/completions/empty.snap, libs/wingc/src/lsp/snapshots/completions/only_show_symbols_in_scope.snap, libs/wingc/src/lsp/snapshots/completions/struct_literal_value.snap, libs/wingc/src/lsp/snapshots/hovers/builtin_in_inflight.snap, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, libs/wingc/src/visit.rs, tools/hangar/__snapshots__/error.ts.snap, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/sdk_tests/util/wait-until.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/debug_env.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/try_catch.w_compile_tf-aws.md
Changes the built-in function "throw" into a dedicated keyword. The rationale for this change (described in #2150) is that throwing is a primary operation that changes the control flow of your program - just like `if`, `while`, `return`, or `try`/`catch` - so it's more natural to have it as a dedicated statement. This means it will receive the same syntax highlighting treatment as `return` and `while` etc.
Closes #2150.
BREAKING CHANGE: `throw` is now a built-in keyword, instead of a global function. Use `throw "blah"` instead of `throw("blah")`
=> feat(compiler)!: `throw` becomes a keyword

Cargo.lock, libs/wingc/Cargo.toml, libs/wingc/examples/compile.rs, libs/wingc/src/file_graph.rs, libs/wingc/src/files.rs, libs/wingc/src/jsify.rs, libs/wingc/src/lib.rs, libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/document_symbols.rs, libs/wingc/src/lsp/goto_definition.rs, libs/wingc/src/lsp/hover.rs, libs/wingc/src/lsp/signature.rs, libs/wingc/src/lsp/sync.rs, libs/wingc/src/parser.rs, libs/wingc/src/test_utils.rs, libs/wingc/src/type_check.rs, libs/wingii/Cargo.toml, libs/wingii/src/lib.rs, libs/wingii/src/node_resolve.rs, libs/wingii/src/test.rs, libs/wingii/src/util.rs
A `str` or `String` in Rust represents a sequence of Unicode characters, while a `Path` or `PathBuf` in Rust represents a sequence of any bytes that represents a path. In practice though, non-Unicode paths are vanishingly uncommon, and there isn't a strong need to support them in Wing. (https://crates.io/crates/camino has some more details)
In this PR I've updated our Rust crates to use the `Utf8PathBuf` and `Utf8Path` types throughout. By doing so we're able to check that our paths are UTF-8 once, and then manipulate them as valid UTF-8 from there on, avoiding repeated lossy and confusing conversions like `path.to_str().unwrap()` and `path.display()`. …
=> chore(compiler): store paths with Utf8PathBuf

.github/workflows/build.yml
A regression from https://github.com/winglang/wing/pull/3791
=> chore(repo): quality gate must run even if e2e tests are skipped

.github/workflows/build.yml
`failure()` checks for failed steps within a job, not jobs within a workflow.
Sorry for testing in prod, workflows are hard 😢 
=> chore(repo): quality gate must fail if preceding jobs fail

docs/docs/03-language-reference.md
It took me a while to realise how to create a mutable variable - I feel like `let [var] <name>[: <type>] = [<type>] <value>;` is not enough, it is easy to not notice the `[var]`. I added a small note about it.
=> feat(docs): add note about variable mutability

docs/docs/03-language-reference.md, examples/tests/invalid/extern.w, examples/tests/invalid/extern_static.w, examples/tests/valid/dynamo.w, examples/tests/valid/dynamo_awscdk.w, examples/tests/valid/extern_implementation.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/extern_implementation.w_compile_tf-aws.md
It's not currently possible for extern method implementations to access class members (like fields, or other instance methods), yet it has still been possible to declare them both ways. This PR introduces an error message if you attempt to add a non-static extern method. In the future, this restriction can be lifted if the capability is supported through a new calling convention with extern JavaScript files or something like that.
=> fix(compiler)!: non-static extern methods are not supported

libs/tree-sitter-wing/turbo.json
Generating the .wasm for the grammar is only needed when running the tree-sitter playground, otherwise the rust build handles consuming the C files when targeting wasm32-wasi. Skipping this unnecessary work is much faster and removes a pretty big dependency from our core build path (docker, although it's still used in tests)
=> chore(build): no need to generate tree-sitter wasm as part of build

examples/tests/sdk_tests/api/path_vars.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/api/path_vars.w_compile_tf-aws.md
=> fix(sdk): fixing api tests

docs/docs/02-concepts/04-tests.md
Stumbled on it while reading the docs and think it reads a bit better without the additional "a".
=> chore(docs): remove double word from tests heading

examples/tests/sdk_tests/bucket/delete.w, examples/tests/sdk_tests/bucket/public_url.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/delete.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/public_url.w_compile_tf-aws.md
Updating the bucket tests following the same standard used in the other resources.
=> chore(sdk): improve bucket tests readability with `assertThrows`

.github/workflows/build.yml
Similar to https://github.com/winglang/wing/pull/4019, but I didn't realize the issue also applies to any jobs that also has dependencies whose dependencies are skipped.
=> chore(repo): ensure publish runs even when certain processes are skipped

apps/jsii-docgen/src/docgen/transpile/transpile.ts, apps/jsii-docgen/src/docgen/transpile/wing.ts, apps/jsii-docgen/test/docgen/view/__snapshots__/documentation.test.ts.snap, apps/jsii-docgen/test/docgen/view/__snapshots__/interface.test.ts.snap, apps/jsii-docgen/test/docgen/view/__snapshots__/markdown.test.ts.snap, docs/docs/04-standard-library/01-cloud/queue.md, docs/docs/04-standard-library/02-std/api-reference.md, libs/wingsdk/.projenrc.ts
closes [#3781](https://github.com/winglang/wing/issues/3781)
=> feat(docs): add variadic params to jsii docgen

libs/wingsdk/src/shared/bundling.ts
The bundling is configured for Node.js 16 (pointing to `aws-sdk` v2 as an external library), but we are configuring our functions on AWS with Node.js 18, which already includes `aws-sdk` v3.
Our entire implementation is using version 3 of `aws-sdk`, so I am updating the bundling to use Node.js 18 and marking `@aws-sdk` as an external library.
from this
to this
Close #4103 
=> fix(sdk): removing aws-sdk v3 from bundling

.github/workflows/build.yml
Fixes #4099
Waiting for https://github.com/nodejs/node/issues/49497 to be released
=> chore: pin node to 20.5.1 in ci

docs/docs/04-standard-library/01-cloud/counter.md, libs/wingsdk/src/cloud/counter.md
Adding example for using multiple keys with a `cloud.Counter` resource.
=> chore(docs): add missing example for `cloud.Counter`

docs/docs/04-standard-library/compatibility/compatibility.json
The target is called `awscdk`, not `aws-cdk`.
=> fix(docs): fix typo in compatibility matrix

apps/vscode-wing/src/console/index.ts, apps/wing-console/console/server/src/index.ts, apps/wing/src/commands/run.test.ts, apps/wing/src/commands/run.ts, libs/wingsdk/src/.gen/versions.json
Fixes #4119
Since wing itself is being run in a child process of vscode, it wasn't handling the kill signal. Detaching it allows it to have its own process tree and be killed more reliably. Special handling is needed for windows, of course.
This also ensures that any process spawned by `wing it` itself is terminated too.
=> fix: ensure wing process is killed from vscode

libs/wingsdk/src/shared/bundling.ts
Bundling aws-sdk v3 again, removing the library made the execution slower
Closes #4125 
=> fix(sdk): bundling aws-sdk v3 again

apps/wing-console/console/app/src/index.ts, apps/wing-console/console/server/src/expressServer.ts, apps/wing-console/console/server/src/index.ts
the console server now accepts an optional express app. useful for setting up authentication and other routes prior to the console routes
=> feat(console): optional express app for server 

apps/wing-console/console/app/playwright.config.ts, apps/wing-console/console/app/test/describe.ts, apps/wing-console/console/ui/src/layout/default-layout.tsx
Improve console tests to prevent CI timeouts caused by some tests randomly getting stuck.
resolves https://github.com/winglang/wing/issues/4153
=> fix(console): tests are causing ci timeouts

docs/docs/04-standard-library/01-cloud/queue.md, examples/tests/sdk_tests/queue/pop.main.w, libs/wingsdk/src/cloud/queue.md, libs/wingsdk/src/target-sim/queue.inflight.ts, libs/wingsdk/test/target-sim/__snapshots__/queue.test.ts.snap, libs/wingsdk/test/target-sim/queue.test.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/pop.main.w_compile_tf-aws.md
Related to https://github.com/winglang/wing/issues/3897
We have a flakey test in our CI that validates part of the functionality of `cloud.Queue`. It turns out, our test was assuming that the queue messages are received in FIFO order (first-in-first-out), which wasn't something we meant to guarantee (see the original issue about `queue.pop()` [here](https://github.com/winglang/wing/issues/1385)). This PR fixes the test, and updates the simulator implementation to reflect the fact that messages can be received out of order.
(Why not FIFO by default? For many distributed apps, the exact order of messages isn't critical, and relaxing this constraint makes it easier to handle higher throughputs of messages. That said, adding a `fifo` option to `cloud.Queue` would be reasonable as a future …
=> fix(sdk): cloud.Queue is not FIFO by default

docs/docs/04-standard-library/01-cloud/function.md, docs/docs/04-standard-library/05-aws/api-reference.md, examples/tests/valid/dynamo.main.w, examples/tests/valid/dynamo_awscdk.main.w, libs/wingsdk/src/cloud/function.md, libs/wingsdk/src/shared-aws/function.ts, libs/wingsdk/src/target-awscdk/bucket.ts, libs/wingsdk/src/target-awscdk/counter.ts, libs/wingsdk/src/target-awscdk/function.ts, libs/wingsdk/src/target-awscdk/queue.ts, libs/wingsdk/src/target-awscdk/secret.ts, libs/wingsdk/src/target-awscdk/topic.ts, libs/wingsdk/src/target-tf-aws/bucket.ts, libs/wingsdk/src/target-tf-aws/counter.ts, libs/wingsdk/src/target-tf-aws/function.ts, libs/wingsdk/src/target-tf-aws/queue.ts, libs/wingsdk/src/target-tf-aws/redis.ts, libs/wingsdk/src/target-tf-aws/secret.ts, libs/wingsdk/src/target-tf-aws/table.ts, libs/wingsdk/src/target-tf-aws/topic.ts
Resolves a small TODO we had in our SDK that we had from prior to the language having variadics. I also added some docs about how to use `aws.Function`.
BREAKING CHANGE: The parameter to `addPolicyStatements` on `aws.Function` is now variadic, so instead of calling `addPolicyStatements([policy1, policy2])` you must omit the array brackets, calling `addPolicyStatements(policy1, policy2)`.
=> fix(sdk)!: change addPolicyStatements to take variadic parameter

libs/wingcompiler/src/wingc.ts
Fixes #4196
Would be nice to find a better way to give the wasm side more file access (or avoid doing any fs ops in wasm at all https://github.com/winglang/wing/issues/1560)
=> fix: crash when root file isn't able to be `stat`ed

.github/workflows/canary.yml
Fixes an operational issue with our canary workflow where installing the latest version of Winglang fails because npm reports a new version as the "latest" before it's actually available for download. (see https://github.com/winglang/wing/actions/runs/6224395212/job/16892506244)
=> fix: flakey installation step in canary workflow

apps/vscode-wing/src/bin-helper.ts
Fixes #3980
https://github.com/winglang/wing/issues/3980#issuecomment-1724946053
> Why do we even attempt to call `resolvePath` if there's no `configuredWingBin`?
Good point :)
=> fix(vscode): default `wing.bin` fails if there is a wing file/dir in home directory

apps/wing-console/console/ui/src/shared/use-file-link.tsx
=> fix(console): missing brackets in console BSOD

.github/workflows/build.yml, tools/bump-pack/src/release-files.ts
- If a version is already published, will skip it instead of failing
- Use the latest version of git tag based on semver sort rather than date. This previously failed if a commit had more than one tag
=> chore: idempotent npm release and fix for git tag determination

.github/workflows/build.yml
`npm view` causes the task to fail if the version isn't found. We don't want that here
=> chore: publish script fix

docs/docs/03-language-reference.md, libs/wingc/src/parser.rs, tools/hangar/__snapshots__/invalid.ts.snap
=> chore(compiler): add support for `.test.w` entrypoints

docs/docs/04-standard-library/02-std/api-reference.md, examples/tests/sdk_tests/std/json.main.w, libs/wingc/src/lsp/snapshots/completions/json_statics.snap, libs/wingc/src/lsp/snapshots/completions/static_completions_after_expression.snap, libs/wingc/src/lsp/snapshots/completions/static_json_after_expression.snap, libs/wingc/src/lsp/snapshots/completions/static_json_after_expression_statement.snap, libs/wingsdk/src/std/json.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/std/json.main.w_compile_tf-aws.md
Brought up during Wingly, we can just return a struct that holds the key and value when calling Json.entries(). Also this does not need to be a macro function
=> fix(sdk)!: change Json.entries() to return Array<JsonEntry>

libs/tree-sitter-wing/src/scanner.c, libs/tree-sitter-wing/test/corpus/expressions.txt
=> fix: automatically semicolon incorrectly inserted into `as` and `in` expressions

examples/tests/invalid/json.main.w, examples/tests/valid/json.main.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/json.main.w_compile_tf-aws.md
Fixes #4185
Fixes #3231 (should be allowed to assign Map to Json, no need to change the error. Fixed specific bug which prevented this for `Json?`)
Most of the change here was in two areas:
- Made sure that collections of Json will always have the Json type data stored in them
- Extracted the json logic from validate_type_in to a new function because it needed some recursion. Heavily commented it now too. The overall logic is only slightly changed, though, to support nested collections.
You'll notice some duplication between the collection literals. If there is concern about it I'm cool with doing some consolidation in this PR, but I figured it could wait until https://github.com/winglang/wing/issues/3873
*By submitting this pull request, I confirm that my contribution is made under the …
=> fix(compiler): implicit structs don't work in collections

.github/workflows/build.yml
I feel like there is a bug in NPM or the registry behind [this issue](https://github.com/winglang/wing/actions/runs/6327139430/job/17183678513), but idk what to do so let's add some retry.
=> chore: add retry for npm publish

libs/wingc/src/lsp/hover.rs, libs/wingc/src/lsp/snapshots/hovers/inflight_init.snap
=> fix(vscode): hover doesn't work in inflight initializer

examples/tests/valid/struct_from_json.test.w, examples/tests/valid/subdir/structs_2.w, libs/wingc/src/jsify.rs, tools/hangar/__snapshots__/test_corpus/valid/struct_from_json.test.w_compile_tf-aws.md
Its a simple fix to make struct schemas available to non-entrypoint files. I have something more robust in a wip local (for another PR) but this should do for now.
(just emits struct schemas into library files)
Closes: https://github.com/winglang/wing/issues/4325
=> fix(compiler): support struct fromJson in non-entry files

docs/contributing/01-start-here/01-contributing-to-wing.md, docs/contributing/01-start-here/05-development.md, docs/contributing/01-start-here/07-wingsdk.md
Trying to re-organize and add a few things to contributor guide for clarity sake. 
(stems from slack conversations)
=> chore(docs): minor reorg tweeks of contributor guide

apps/wing/src/commands/compile.test.ts, libs/wingc/examples/compile.rs, libs/wingc/src/jsify.rs, libs/wingc/src/lib.rs, libs/wingc/src/lsp/sync.rs, libs/wingc/src/parser.rs, libs/wingc/src/test_utils.rs, libs/wingcompiler/src/compile.ts, tools/hangar/__snapshots__/test_corpus/valid/assertions.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/baz.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/store.w_compile_tf-aws.md, tools/hangar/src/generated_test_targets.ts
The wing toolchain now supports compiling directories. For example:
```
$ wing compile .
```
When a directory is compiled, no preflight code is executed (this only happens when an entrypoint file like `main.w` is passed to `wing compile`).
Required for https://github.com/winglang/wing/pull/3938
=> feat(cli): compile directories

apps/wing/src/commands/compile.ts
=> fix(cli): compile with DEBUG=1 shows wrong stack trace

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/feature.yml
Adding another field to issue templates, to indicate whether this issue is ready to start implementation or whether some further discussion is needed first.
=> chore(repo): ready for implementation field in issue templates

.github/workflows/build.yml, tools/hangar/src/benchmarking/cli.bench.ts, tools/hangar/src/benchmarking/compare.ts, tools/hangar/src/package.setup.ts
Now the benchmark runs twice: Once for the latest version and once for the PR. They run on the same machine in the same job, so there are less variables to worry about.
=> chore: rerun baseline benchmark as part of workflow

examples/tests/sdk_tests/function/env.test.w, libs/wingsdk/src/cloud/function.ts, libs/wingsdk/src/cloud/service.ts, libs/wingsdk/src/shared-tf/tokens.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/function/env.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/function/env.test.w_test_sim.md
If the same environment variable is added multiple times, and we know for sure that the values are identical, then repeated calls should be OK since the operations are commutative (addEnvironment method calls can still be safely reordered).
=> feat(sdk): allow re-adding environment variable value to function or service

apps/wing/package.json, apps/wing/src/cli.ts, apps/wing/src/commands/compile.test.ts, apps/wing/src/commands/compile.ts, apps/wing/src/commands/run.test.ts, apps/wing/src/commands/run.ts, apps/wing/src/commands/test.ts, docs/docs/06-tools/01-cli.md, pnpm-lock.yaml
Broke windows
Reverts winglang/wing#4257
=> revert(cli): introduce default entrypoints

.github/ISSUE_TEMPLATE/feature.yml
GitHub renders newlines in markdown...
=> chore: remove newlines from community note

.github/workflows/build.yml, .github/workflows/tf-aws-test.yml
Typically when a bad publish happens, it fails on the first one. Because the publish is in a loop, it does not exit the script properly on error (set -e doesn't matter cause bash is crazy).
Also, too many spec tests are happening at once.
=> chore: prevent publish job from partial publishing

apps/wing/src/commands/lsp.ts
=> feat(vscode): add underlined hints for error annotations

libs/wingc/src/lsp/hover.rs, libs/wingc/src/lsp/snapshots/hovers/class_init_this_field.snap, libs/wingc/src/lsp/snapshots/hovers/static_stdtype_method.snap
Hovering over assignments with references (e.g. `this.x = 2` and hovering over `this` or `x`) caused a panic.
=> fix(vscode): panic when hovering over references in assignment

examples/tests/invalid/inference.test.w, examples/tests/valid/inference.test.w, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/inference_visitor.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/inference.test.w_compile_tf-aws.md
Fixes #4438
Due to:
- breadth-first type checking
- simplistic inference
- no re-checking (good)
Currently, this works:
```
let f = (arg) => {
return arg.get("a");
};
if true {
let x = f({ a: true });
}
```
but this does not work:
```
let f = () => {
return { a: true };
};
if true {
let x = f().get("a");
//        ^^^ don't know what the return type is yet because the closure above hasn't be checked
}
```
Because when first implementing inference, the sub-scopes of a scope were checked in reverse order. I thought this heuristic was kinda neat and figured it had legs. Now I'm thinking that was wrong. 
With this PR, the scope will be checked in normal order. Now the second case will work and the first case above will **not** work. It will require explicit annotation on the argument:
```
let …
```
=> fix(compiler)!: unexpected heuristic for inference across scopes

libs/tree-sitter-wing/src/scanner.c
=> chore: format tree-sitter scanner and remove implicit switch fallthrough

docs/docs/03-language-reference.md, examples/tests/valid/casting.test.w, libs/wingc/src/ast.rs, libs/wingc/src/lib.rs, libs/wingc/src/lsp/snapshots/completions/call_struct_expansion.snap, libs/wingc/src/lsp/snapshots/completions/call_struct_expansion_partial.snap, libs/wingc/src/lsp/snapshots/completions/empty.snap, libs/wingc/src/lsp/snapshots/completions/only_show_symbols_in_scope.snap, libs/wingc/src/lsp/snapshots/completions/struct_literal_value.snap, tools/hangar/__snapshots__/test_corpus/valid/casting.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/casting.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/debug_env.test.w_test_sim.md
Fixes #4161
For situations where application code needs to interact with foreign interfaces, or where the compiler cannot infer all type information, most modern languages support some mechanism for "casting" or performing unsafe conversions between types ([1](https://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition/casting-between-types.html), [2](https://pkg.go.dev/unsafe#Pointer), [3](https://www.baeldung.com/java-type-casting), [4](https://docs.swift.org/swift-book/documentation/the-swift-programming-language/typecasting/)). Indeed, we've already identified some use cases in #4161 that require casting, like performing low-level escape hatches in CDK applications.
To that end, this PR introduces a global function named `unsafeCast` that allows …
=> feat: unsafeCast builtin function

.github/workflows/build.yml, .github/workflows/tf-aws-test.yml
Currently, there are plenty of tests in a single file of any std test, and our current test scope (which duplicates resources by the number of tests) isn't handling it well, so we often get timeouts and exceptions.
Since the std tests' code is identical both on aws and the sim (and tested in the sim via hangar) I think we can skip it until the [testing issue](https://github.com/winglang/wing/issues/3168) resolves.
link to test run: https://github.com/winglang/wing/actions/runs/6480615481
=> chore: skip std spec tests

apps/wing-console/console/design-system/src/attribute.tsx, apps/wing-console/console/design-system/src/tabs.tsx, apps/wing-console/console/ui/src/features/auto-updater.tsx, apps/wing-console/console/ui/src/features/console-logs-filters.tsx, apps/wing-console/console/ui/src/layout/use-layout.tsx, apps/wing-console/console/ui/src/services/use-api.ts, apps/wing-console/console/ui/src/services/use-explorer.tsx, apps/wing-console/console/ui/src/ui/api-interaction.tsx, apps/wing-console/console/ui/src/ui/bucket-metadata.tsx, apps/wing-console/console/ui/src/ui/counter-interaction.tsx, apps/wing-console/console/ui/src/ui/dynamodb-table-interaction.tsx, apps/wing-console/console/ui/src/ui/function-metadata.tsx, apps/wing-console/console/ui/src/ui/queue-metadata.tsx, apps/wing-console/console/ui/src/ui/table-interaction.tsx, apps/wing-console/packages/use-persistent-state/src/index.tsx
=> chore(console): address eslint warnings

libs/wingc/src/lsp/goto_definition.rs, libs/wingc/src/lsp/hover.rs, libs/wingc/src/lsp/snapshots/goto_definition/class_extends.snap, libs/wingc/src/lsp/snapshots/goto_definition/class_impl.snap, libs/wingc/src/lsp/snapshots/hovers/struct_decl_field.snap, libs/wingc/src/lsp/symbol_locator.rs
Fixes #4526
Tried to minimize the work done in SymbolLocator so that the base visitor can make sure to handle cases like this. It adds a small bit of redundant traversal at runtime but makes it harder to hit edge cases if SymbolLocator gets out of sync with the base visitor implementation.
Other Fixes:
- hover for interface and struct declaration fields. It's not super useful, but it also felt weird that it didn't work
=> fix(vscode): no symbol details for `extends` or `impl`

.github/workflows/mutation.yml
Double mutations are a waste of CI time. This should prevent that and alert the user that something is wrong with their PR.
=> chore(repo): prevent instable mutations from running multiple times in a row

libs/wingc/src/diagnostic.rs, libs/wingc/src/lsp/hover.rs, libs/wingc/src/lsp/snapshots/hovers/static_method_root.snap
A std type like `Json` is actually `std.Json` in the AST. That `std` part is not technically part of the file so it does not have an actual span. This panicked when comparing file_id in the merge function.
This change allows the span merge function to basically ignore default spans.
Sidenote: I'd really like to make WingSpan into an enum, but that change sounds like a lot of work to fix this panic.
=> fix(vscode): panic when hovering over std types

examples/tests/sdk_tests/external/fs.js, examples/tests/sdk_tests/website/website.test.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/website/website.test.w_compile_tf-aws.md
Following #4135, there's no more need for a fs `extern` module.
=> chore(sdk): remove fs `extern` module

apps/wing/src/analytics/scripts/detached-export.ts
Calling `await` at the top level isn't supported in Node.js, so the code in `detached-export.ts` (which is run in a child process) was silently failing. Reverting to the previous behavior (not using `await`) resolves the issue.
Fixes #4546
=> fix(cli): analytics error

scripts/setup_wasi.sh
This change improves the robustness of `binaryen` installation by making sure that all binaries are correctly installed.
=> chore(build): make `binaryen` installation more robust

libs/wingc/src/comp_ctx.rs, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap
There was a regression in the panic message where it sometimes did not show anything when a panic occurs. This basically reverts to the previous message
Misc change: wingc had a lint error regarding optional unwrapping
=> fix(compiler): missing message in panic

libs/wingc/src/lib.rs, libs/wingc/src/lsp/code_actions.rs, libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/document_symbols.rs, libs/wingc/src/lsp/goto_definition.rs, libs/wingc/src/lsp/hover.rs, libs/wingc/src/lsp/signature.rs, libs/wingc/src/lsp/sync.rs, libs/wingc/src/wasm_util.rs
Was tired of repeating the same function over and over again.
I considered a macro but IMO it didn't look much better and would actually add more duplicated code than necessary (thus making a bigger WASM file)
Also changed `ptr_to_string` into `ptr_to_str` to avoid unnecessarily copying the data we get into an owned String.
=> chore(compiler): remove lots of wasm boilerplate and remove redundant clone for WASM/Rust communication

libs/wingsdk/src/target-tf-aws/api.ts
The `onLift` method of the `cloud.Api` had an error message stating, `topics can only be bound by tfaws.Function for now.`
I changed `topics` to `apis`.
=> chore(sdk): fix error message

README.md
Fixed broken link to Gif in readme
=> fix(docs): readme gif link

libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/snapshots/completions/no_completion_wrong_builtin.snap, libs/wingc/src/lsp/snapshots/completions/type_parameter.snap, libs/wingc/src/lsp/symbol_locator.rs, libs/wingc/src/type_check.rs
Previously, text like `String.` would always show completions as if it were `str.`, which is incorrect. Additionally, I noticed that completions for types would not show up inside the brackets of types like `Array<>` so that's fixed as well.
=> fix(vscode): invalid completions for types that look like builtins

apps/wing/src/commands/test/results.ts
Before: 
unsupported:
error:
After: 
(errors look the same:)
=> fix(cli): fix unsupported color

libs/tree-sitter-wing/grammar.js, libs/tree-sitter-wing/test/corpus/statements/class_and_resource.txt
The `async` method modifier wasn't being used anywhere in the code and wasn't marked as  reserved word in parser.rs anyway.
The wing way is basically that everything inflight is `async` anyway and everything preflight isn't.
The only thing I'm not sure of is whether we should add `async` as a reserved word just as a space-holder. I think not.
This is a minor cleanup related to #3329.
=> fix(compiler): `async` method modifier never used

docs/docs/999-faq/040-alternatives/043-awscdk-vs-wing.md
Fixing a typo in the Wing vs ASW-CDK page
=> docs(docs): fix typo from "pulumi" to "ASW-CDK"

.github/workflows/pull-request-lint.yml
Want to title my Platforms PR with the scope of Platforms, need to merge this change first
=> chore(repo): add platforms as valid pr scope

libs/wingsdk/src/target-awscdk/counter.ts
I've noticed that `super.onLift()` is present on all other resources so I believe it must be missing.
=> fix(sdk): add missing `super.onLift()` for `awscdk` counter

libs/wingsdk/src/target-awscdk/bucket.ts, libs/wingsdk/test/target-awscdk/__snapshots__/bucket.test.ts.snap
When creating a public bucket, the `blockPublicAccess` property of the Bucket object was not being correctly filled.
Closes #4745 
=> fix(sdk): public bucket settings in awscdk

apps/wing/src/commands/test/test.test.ts, apps/wing/vitest.config.ts
Removing duplicate code and setting global timeout to `200_000` ms like the other wing projects.
=> chore(cli): tidy `wing test` tests

apps/wing/src/cli.ts, apps/wing/src/commands/compile.ts, docs/docs/02-concepts/03-platforms.md, tools/hangar/src/utils.ts
Requires multiple platforms to each be specified with their own option
I.E.
`wing compile --platform x y z` is now done as `wing compile --platform x --platform y --platform z`
=> fix(platforms): require platform flag multiple times

apps/wing/src/cli.ts, apps/wing/src/commands/compile.ts, tools/hangar/__snapshots__/test_corpus/valid/bucket_events.test.w_test_sim.md
Fix to make sure same default platform are used for any command using `collectPlatformVaridaic` 
=> fix(cli): make sim default platform for test command

apps/wing/src/analytics/collect.ts, apps/wing/src/analytics/collectors/cli-collector.ts, apps/wing/src/cli.ts
Fixes #4787
`wing lsp` does not have a platform, which broke analytics.
Analytics broke the whole program because we awaited a failing promise outside of our try/catch handling.
=> fix: lsp subcommand does not work

examples/tests/sdk_tests/bucket/copy.test.w
lengthen test sleep for stabilization, we're waiting many seconds in many tests- so those extra 5s won't make a negative difference (probably even a positive difference- since we won't need to re-run the tests)
=> fix(sdk): lengthen test sleep for stabilization

apps/vscode-wing/syntaxes/wing.tmLanguage.json, docs/docs/03-language-reference.md, examples/tests/valid/expressions_binary_operators.test.w, libs/tree-sitter-wing/grammar.js, libs/wingc/src/parser.rs, tools/hangar/__snapshots__/test_corpus/valid/expressions_binary_operators.test.w_compile_tf-aws.md
Add support for padding numeric literals with underscores or zeros. (inspired by Swift, Rust)
=> feat(compiler): support padding in number literals

docs/docs/03-language-reference.md
The current syntax for declaring sets in Wing uses curly braces, and allows the type annotation to be omitted if it can be inferred:
```js
let items = {1, 2, 3}; // Set<num>
let names = MutSet<str>{"alice", "bob", "charlie"};
```
This syntax matches the mathematical syntax for [sets](https://en.wikipedia.org/wiki/Set_(mathematics)) which also typically use curly braces, and it makes it convenient to create immutable set constants.
But the syntax has some drawbacks:
1. An empty set always requires a type annotation, or else `{}` will be interpreted as `Json` - this can be surprising to new users.
2. The set syntax collides with the desire for [punning in struct/Json literals](https://github.com/winglang/wing/issues/247), a feature many users have requested where the syntax `{ foo, bar }` …
=> rfc: set syntax proposal

.github/workflows/tf-aws-test.yml
The azure tests can take an extremely long time
=> chore: increased timeout for sdk spec tests

apps/wing-console/console/server/src/utils/compiler.ts
resolves: https://github.com/winglang/wing/issues/4882
also adjust the console watcher to watch all changes in the wing file parent directory except changes made in node_modules and target dirs
=> fix(console): can not run wing it when file path includes src

docs/docs/02-concepts/05-simulator.md
The link in the `Simulator` section (`platform provider`) is broken.  It has the wrong file path name target.
Also, the `unit tests` link can be shortened to match the `platform provider`.
=> fix(docs): link in the `simulator` section broken

libs/wingc/src/lsp/goto_definition.rs, libs/wingc/src/lsp/snapshots/goto_definition/goto_module_path.snap
Closes #4899
Logic is the same as the extern modifier.
The behavior for a directory is a bit awkward but I decided to leave it in. Ideally, it'd be nice if it just "revealed" the dir in the file explorer, but that'd have to be implemented on a per-editor basis and not part of the LSP.
=> feat(vscode): goto file in bring statement

libs/wingsdk/src/shared-aws/queue.inflight.ts
See https://github.com/winglang/wing/actions/runs/6853870493/job/18635846024
=> fix(sdk): popping queue in aws can sometimes throw

apps/wing-console/console/ui/src/layout/use-layout.tsx, apps/wing-console/console/ui/src/ui/elk-map.tsx, apps/wing-console/console/ui/src/ui/explorer.tsx, apps/wing-console/console/ui/src/ui/no-resources.tsx, apps/wing-console/console/ui/src/ui/no-tests.tsx
Resolves https://github.com/winglang/wing/issues/4868.
* Removes the loading indicator when the app is empty
* Removes the map background
* Adds a warning in the Explorer when the app is empty
=> fix(console): appears to be loading if the app is empty 

.github/ISSUE_TEMPLATE/bug.yml
- Removed the "component" section. 
- IMO it's not the responsibility of a bug reporter to know how maintainers categorize issues. This is better suited for labels at our discretion.
- Moved the "Anything Else" to be next to the rest of the actual bug report.
- This additional context is likely more useful than the version information and putting it before that increases the chances of it being filled in
- Removed `## Misc` since it didn't really matter without the "Anything Else"
- Added whitespace to make it consistent
- Fixed minor typo
=> chore: remove some ceremony from bug template

apps/wing-console/console/server/src/utils/compiler.ts
The Console Server triggers some compilations during the initialization of the watcher.
Also, it now ignores the `.git` directory.
=> fix(console): unnecessary compilations during init

apps/wing-console/console/ui/src/layout/layout-provider.tsx
Hides the console status bar when using the console inside wingcloud.
=> feat(console): add layout for wingcloud integration

.github/ISSUE_TEMPLATE/bug.yml
=> chore: make "expected" field optional in bug report

apps/wing-console/console/ui/package.json, pnpm-lock.yaml
Sets `react-markdown` as a dependency rather than a dev dependency, which means `tsup` will stop bundling `react-markdown` files.
Also, updates `react-markdown` to v9.
=> fix(console): ui package incorrectly bundles `react-markdown`

libs/wingsdk/src/platform/platform-manager.ts
CommonJS scripts can export via `exports` or `module.exports`. The latter was missing from the VM created by the platform manager.
=> fix(sdk): add missing `module` object to platform vm context

libs/wingsdk/src/std/resource.ts
Quick fix to use the _isApp hack for determining App node in tree
Closes: https://github.com/winglang/wing/issues/5028
=> fix(platforms): custom platform fails for wing test

examples/tests/sdk_tests/std/node.test.w
Chose not to `.replace("\\", "/")` to make the intention as explicit as possible
=> chore(sdk): fix node.test.w test on windows 

docs/docs/03-language-reference.md, docs/docs/07-examples/10-using-javascript.md
This PR contains two minor documentation updates.
- In **using-javascript** the docs now reflect that only static functions are supported and externs defualt to private access
- In the language reference, the Javascript example now has the **pub** modifier.
No tests required. I didn't open an issue for this. I hope that's okay.
=> docs(docs):  Update docs for calling extern function from Javascript

libs/wingsdk/src/target-sim/react-app.ts
See failing test here https://github.com/winglang/wing/actions/runs/6990660035/job/19020417470
Previous PR removed this as part of a larger effort to remove redundant ids (no functional reason to re-add your parents' id). This caused a test to fail, and I realized that in this case it is kinda useful to carry the name forward. So let's call this an exception.
=> fix(sdk): add (back in) scope id to react app

docs/docs/03-language-reference.md
Just a small mistake in the docs.
=> chore(docs): fix wrong syntax for maps

apps/wing/src/commands/test/test.test.ts, apps/wing/src/commands/test/test.ts
fixes `wing test -t @my-custom/platform main.w`, where `@my-custom/platform` extends the `tf-aws` platform. The error which occurred after `terraform apply`:
```
Cannot find module '@winglang/sdk/lib/undefined/test-runner.inflight'
```
=> fix(cli): load test runner for custom platform

libs/wingsdk/src/std/resource.ts
Fixes #5064
`instanceof` strikes again.
Technically hangar already tests the case that failed here, but the test did not fail in hangar. I don't actually have an answer for why this is. My guess is that the cwd hangar runs in affected the modules loaded.
I did not add any testing here because afaik we are not currently equipped to test this scenario properly (we need https://github.com/winglang/wing/issues/3390), so I only tested that this fix worked locally.
=> fix(sdk): external platforms may have error when lifting resources

examples/tests/valid/inheritance_interface.test.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/test_corpus/valid/inheritance_interface.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/inheritance_interface.test.w_test_sim.md
Fixes #5073 by setting inherited members to non static (it was a mistake I am assuming).
=> fix: cannot call methods from base interfaces

.github/workflows/new-pull-request-comment.yml
We decided we'd like to add a comment on each new PR opened.
This comment should contain the ownership on the different areas of our project.
See below what the comment looks like.
=> feat(repo): comment on each new pr with ownership table

.github/workflows/new-pull-request-comment.yml
The new PR comment introduced an ownership table. Owners are mentioned (using `@`) which is annoying when all of them get mentioned on every new PR whether it's relevant for them or not. Escaped `@` (that's the github markdown way).
=> chore(repo): unmention maintainers on new pr comment

libs/wingsdk/src/shared/sandbox.ts, libs/wingsdk/src/simulator/client.ts, libs/wingsdk/src/simulator/simulator.ts, libs/wingsdk/test/simulator/simulator.test.ts
I was debugging an error with @yoav-steinberg, and we had an issue while augmenting the lifting system to get the following code to work:
```js
let b = [new cloud.Bucket()];
test "foo" {
b.at(0);
}
```
We found that the generated JavaScript looked like this:
```js
await b.at(0);
```
Ordinarily this would no-op (since calling "await" on non-promises usually does nothing). But in the Wing simulator, the bucket client is a special proxy object that automatically translates all method calls into HTTP requests. When determining if a value is a promise or not, the JS runtime tries to call "then" on objects (see https://stackoverflow.com/questions/55262996/does-awaiting-a-non-promise-have-any-detectable-effect), and this ended up causing an error instead of the no-op behavior.
The first major …
=> fix(sdk): awaiting client object causes error in sim target

.github/workflows/tf-aws-test.yml
Follow-up to https://github.com/winglang/wing/pull/4608
Tests now need to run from the test directory in case a .env file is used
=> chore: run e2e cloud tests from test dir

.github/workflows/tf-aws-test.yml
I split the SDK spec tests to run this way- 
stable targets (currently tf-aws) tests will run during build- and fail release if there's an error, 
un-stable targets (currently tf-azure) tests will run after release- and won't fail the build if there's an error
=> fix(repo): unstable targets won't break build

docs/docs/04-standard-library/03-std/array.md, examples/tests/sdk_tests/std/array.test.w, libs/wingc/src/jsify/snapshots/no_capture_shadow_inside_inner_scopes.snap, libs/wingc/src/jsify/snapshots/no_lift_shadow_inside_inner_scopes.snap, libs/wingsdk/src/std/array.ts, tools/hangar/__snapshots__/test_corpus/valid/function_variadic_arguments.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/inference.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/inflight_class_inner_capture_mutable.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/mut_container_types.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/shadowing.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/std_containers.test.w_compile_tf-aws.md
Fixes issue in #5114 and closes #4836 
Attach updated array.ts file (has updated definition for .push() on MutArray to support variadic arguments) and update snapshots
Example Input:
let myList: MutArray<str> = MutArray<str> ["element1"];
myList.push("element2", "element3");
Example Output:
const myList = ["element1"];
((obj, args) => { obj.push(...args); })(myList, ["element2", "element3"]);
=> feat(sdk): support variadic arguments in MutArray.push (cont.)

apps/wing-console/console/server/src/router/app.ts
Remove redundant connections to a parent resource if there's already a connection to a child resource.
Closes #5176.
=> feat(console): hide unnecessary connections

apps/wing-console/console/server/src/router/app.ts
Some connections go from a node to a parent node, which isn't visually helpful.
=> feat(console): hide connections that go from a node to a parent

.github/ISSUE_TEMPLATE/feature.yml
Make the feature request issue template more focused on use cases and only *proposed* solution instead of leading with the solution.
=> chore(repo): refactor feature request issue template

docs/docs/01-start-here/02-installation.md
On the installation page it had a link for the VSCode extension which was suppposed to link to the below title, but the href was incorrect, so this fixes it. 
=> docs(docs): update 02-installation.md with correct local href link

docs/docs/04-standard-library/_category_.yml
Restore the `_category_.yml` file.
=> chore(docs): change "standard-library" to "Standard Library"

docs/docs/07-examples/13-api-gateway.md
The path parameters of the API routes are invalid (`{var}` instead of `:var`).
=> docs(examples): path parameters

apps/wing/src/commands/test/test.test.ts, apps/wing/src/commands/test/test.ts, libs/wingsdk/src/target-sim/api.inflight.ts, libs/wingsdk/src/target-sim/event-mapping.inflight.ts, libs/wingsdk/src/target-sim/event-mapping.ts, libs/wingsdk/src/target-sim/queue.inflight.ts, libs/wingsdk/src/target-sim/schedule.inflight.ts, libs/wingsdk/src/target-sim/topic.inflight.ts, tools/hangar/__snapshots__/test_corpus/valid/resource.test.w_test_sim.md
Fixes #5228
We discovered an issue where invalid errors were thrown in unit tests where a message is pushed to a queue and the queue had a consumer function. The problem occurred because a queue's simulation periodically processes messages, but this continued even after the queue consumer function is deleted during the simulator's cleanup. (I've shared some verbose test logs from the minimal repro in #5228 here: https://gist.github.com/Chriscbr/23fb248fb65d9e349da6e3347c90c866).
To fix this, I updated the EventMapping resource so it also removes the its function from the queue's subscribers when the EventMapping is cleaned up. By doing this, we guarantee the function is removed from the queue's subscribers before the function is cleaned up, so when the queue tries processing messages, it …
=> fix(sdk): no resource found with handle simulator error

apps/jsii-docgen/src/cli.ts, apps/wing-api-checker/src/index.ts, apps/wing-console/console/server/src/utils/format-wing-error.ts, apps/wing/.eslintrc.json, apps/wing/src/cli.ts, apps/wing/src/commands/compile.ts, apps/wing/src/commands/lsp.ts, apps/wing/src/commands/run.ts, apps/wing/src/commands/test/test.ts, libs/wingc/src/diagnostic.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/jsii_importer.rs, libs/wingsdk/src/simulator/simulator.ts, tools/hangar/__snapshots__/invalid.ts.snap
Before:
After:
Misc:
1. Adding this diagnostic uncovered an issue where if a diagnostic annotation references a span from a JSII library (for example, if you try accessing a protected member of a JSII class), then the CLI crashes since the spans don't point to real files on disk. To fix that, I've removed JSII spans from the compiler AST for now.
2. Adding this diagnostic also uncovered an issue where if too many compiler errors are emitted, then they might not all get printed because the CLI calls `process.exit()`, which forces the process to exit before all I/O operations finish (see https://stackoverflow.com/a/37592669/8605016). To fix this, I've changed several of these places in the code to set the process's exit code with `process.exitCode = 1`.
3. The changes in (2) uncovered an …
=> feat(compiler): enhance diagnostics for invalid access errors

apps/wing-console/console/app/src/index.ts, apps/wing-console/console/server/src/index.ts, apps/wing-console/console/server/src/utils/compiler.ts, apps/wing-console/console/server/src/utils/simulator.ts
it's now possible to start the console server with a specific state directory
=> feat: state dir prop for the console server

docs/contributing/01-start-here/06-pull-requests.md
The `platforms` scope was added to the workflow but not in the docs.
=> chore(docs): add missing PR scope

.github/workflows/build.yml, .github/workflows/mutation.yml, .github/workflows/tf-aws-test.yml
Upgrading GitHub Actions to [Artifacts v4](https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/) for performance improvements.
=> chore(build): upgrade github actions to artifacts v4

libs/wingsdk/src/target-tf-aws/function.ts, libs/wingsdk/test/target-tf-aws/function.test.ts, tools/hangar/__snapshots__/test_corpus/valid/redis.test.w_compile_tf-aws.md
If a function didn't have policy statements before, then the IAM statements required so that it can be added to the VPC are not added because `policyStatements` might be undefined.
The fix is to make sure `policyStatements` is either defined or an empty array.
=> fix(sdk): sometimes aws function cannot be added to vpc

libs/wingsdk/src/simulator/simulator.ts
=> chore(sdk): remove deprecated `fs.rmdir` from `Simulator`

apps/vscode-wing/.projenrc.ts, apps/vscode-wing/package.json, apps/vscode-wing/src/console/console-manager.ts, apps/vscode-wing/src/console/explorer-providers/EndpointsExplorerProvider.ts, apps/vscode-wing/src/console/services/client.ts, apps/wing-console/console/design-system/src/tree-item.tsx, apps/wing-console/console/server/src/router/endpoint.ts, apps/wing-console/console/server/src/router/index.ts, apps/wing-console/console/server/src/utils/createRouter.ts, apps/wing-console/console/ui/src/features/endpoints-tree-view.tsx, apps/wing-console/console/ui/src/layout/default-layout.tsx, apps/wing-console/console/ui/src/layout/layout-provider.tsx, apps/wing-console/console/ui/src/services/use-endpoints.ts, apps/wing-console/console/ui/src/shared/endpoint-item.ts, apps/wing-console/console/ui/src/ui/endpoint-tree.tsx, apps/wing-console/console/ui/src/ui/no-endpoints.tsx, libs/awscdk/src/website.ts, libs/wingsdk/src/cloud/endpoint.ts, libs/wingsdk/src/target-sim/api.ts, libs/wingsdk/src/target-sim/endpoint.ts, libs/wingsdk/src/target-sim/schema-resources.ts, libs/wingsdk/src/target-sim/website.ts, libs/wingsdk/src/target-tf-aws/api.ts, libs/wingsdk/src/target-tf-aws/website.ts, libs/wingsdk/test/target-sim/__snapshots__/api.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/domain.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/react-app.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/website.test.ts.snap
Adding a panel to list all `cloud.Endpoint` in the app
=> feat: endpoints panel in the console

apps/wing-console/console/server/src/index.ts, apps/wing-console/console/server/src/router/test.ts, apps/wing-console/console/server/src/utils/format-wing-error.ts
extracting TestRunnerClient TestResult error and adding to the console logger.
for example, the following TestResult error:
```
{
path: 'root/env0/test:hello',
pass: false,
error: 'AssertionError [ERR_ASSERTION]: Expected values to be strictly deep-equal:\n' +
'\n' +
'1 !== 2\n' +
'\n' +
'    at Util.equal (/var/folders/dy/sygfk8k13rlgxfgj6r3zkr1c0000gn/T/wing-bundles-6TowaX/index.js:7070:26)\n' +
'    at $Closure1.handle (/var/folders/dy/sygfk8k13rlgxfgj6r3zkr1c0000gn/T/wing-bundles-6TowaX/index.js:24:30)\n' +
'    at exports.handler (/var/folders/dy/sygfk8k13rlgxfgj6r3zkr1c0000gn/T/wing-bundles-6TowaX/index.js:7120:9)',
traces: [
{
data: [Object],
type: 'resource',
sourcePath: 'root/env0/test:hello/Handler',
sourceType: '@winglang/sdk.cloud.Function',
timestamp: …
```
=> fix(console): tests errors are not shown in the console

examples/tests/sdk_tests/util/sleep-helper.js, examples/tests/sdk_tests/util/sleep.test.w, examples/tests/sdk_tests/util/wait-until.test.w
=> chore(sdk): use `util.datetime` in more wing tests

examples/tests/sdk_tests/util/exec.test.w, libs/wingsdk/src/util/util.ts
My bash profile had an issue when running `wing test` for this file.
Ignoring the bash profile is probably better to reduce some variability for this test across machines anyway.
Also added usual `windowsHide` and `shell` options when using exec as I think that's the expected behavior.
=> chore: ignore bash profile in sdk tests

libs/wingsdk/src/util/util.ts
Aligning `util.shell()` to `util.exec()` and removing `shell: false` since that's the default value anyway.
=> fix(sdk): `util.shell` on windows displays the console window

libs/wingsdk/src/shared-aws/bucket.inflight.ts, libs/wingsdk/test/shared-aws/bucket.inflight.test.ts
Updating `bucket.exists()` to use `NotFound` error class for AWS targets and also removing some unneeded mock listeners from bucket inflight tests.
=> fix(sdk): switch to SDK for JS v3 error class for `bucket.exists()` on AWS targets

apps/wing-console/console/app/preview/Dockerfile
For each PR we create a new Console preview environment for internal testing. We forgot to disable analytics for this instance.
Updating our Dockerfile with the relevant env var
=> chore(console): disable analytics for console preview environments

libs/awscdk/test/util.ts, libs/wingsdk/test/target-sim/__snapshots__/immutable-capture.test.ts.snap, libs/wingsdk/test/util.ts
The code sanitizer had a faulty regex to detect absolute paths which swallowed multiple abs paths and other double quote strings when they were in the same line.
The result are fixed snapshots.
=> fix: invalid snapshots when removing multiple abs paths in same line

apps/wing-console/console/server/src/router/app.ts
The console server api can now respond with all nodes including those that are hidden in the tree
=> chore(console): include hidden nodes 

docs/docs/04-standard-library/aws/_category_.yml, docs/docs/04-standard-library/ex/_category_.yml, docs/docs/04-standard-library/expect/_category_.yml, docs/docs/04-standard-library/fs/_category_.yml, docs/docs/04-standard-library/http/_category_.yml, docs/docs/04-standard-library/math/_category_.yml, docs/docs/04-standard-library/regex/_category_.yml, docs/docs/04-standard-library/sim/_category_.yml, docs/docs/04-standard-library/std/_category_.yml, docs/docs/04-standard-library/ui/_category_.yml, docs/docs/04-standard-library/util/_category_.yml
Not all the sections in Standard Library were using "genereated-index" which was leading to a non uniform experience across the libraries. 
Also this prevents the docsite from defaulting to using README.md files which was mentioned in this thread: https://winglang.slack.com/archives/C047QFSUL5R/p1704035377312369
=> fix(docs): not all categories were using generated-index

libs/wingsdk/src/platform/platform-manager.ts
Since I was yanking out the callbacks for synth-hooks I needed to bind their associated instance to the callback's `this`
Closes: https://github.com/winglang/wing/issues/5131
=> fix(platforms): platforms cannot use "this" in hooks

libs/wingsdk/src/target-sim/service.inflight.ts, libs/wingsdk/test/target-sim/service.test.ts
Emit an error to log instead of crashing the simulator.
=> fix(sdk): `cloud.Service` crashes the simulator if initialization fails

apps/wing/src/commands/compile.test.ts, apps/wing/src/commands/pack.test.ts, apps/wing/src/commands/pack.ts, apps/wing/src/util.ts, libs/wingcompiler/src/compile.ts, libs/wingcompiler/src/util.ts, libs/wingsdk/src/shared/bundling.ts
Fixes #4988
When starting compilation, if there is already an existing synth directory, it will be renamed to "{dirname}.bak". Files that are not part of the generated output (e.g. terraform state files) will be copied from that backup before running the rest of the process.
To facilitate this, a new `.manifest` json file is created after compilation that lists all the files generated.
This PR looks like a bigger diff than it really is because I added a `try {} finally {}` block around most of the compilation process.
Couple thoughts:
- The current method will always replace a previous backup with a new one, regardless of whether the compilation failed or not. I went back and forth on whether this is important or not
- The main synth dir will no longer always be valid. I think it would be …
=> feat: use a single `.bak` instead of generating `.tmp` directories every time

examples/tests/invalid/optionals.test.w, libs/wingc/src/parser.rs, tools/hangar/__snapshots__/invalid.ts.snap
Optional functions missing a return type caused a crash.
note that optional function types are still not supported, this only adds an appropriate diagnostic instead of crashing the compiler.
see #4296 
=> fix(compiler): optional functions missing a return type caused a crash

docs/docs/03-language-reference.md, examples/tests/invalid/function_type.test.w, examples/tests/invalid/optionals.test.w, examples/tests/valid/optionals.test.w, libs/tree-sitter-wing/grammar.js, libs/tree-sitter-wing/test/corpus/expressions.txt, libs/tree-sitter-wing/test/corpus/references.txt, libs/tree-sitter-wing/test/corpus/statements/statements.txt, libs/wingc/src/lsp/completions.rs, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/optionals.test.w_compile_tf-aws.md
See #4296
We can now define optional function types via support for parenthesis around type annotations:
```wing
// Optional function type
var let fn: (():void)? = () => { };
fn = nil;
// Crazy parenthesis type annotation
let x: (((((((num))))))) = 1;
```
=> fix(compiler): can't define optional function types

apps/wing/src/commands/compile.test.ts, libs/wingcompiler/src/compile.ts
fixes #5477
This is basically a revert of https://github.com/winglang/wing/pull/5434, and goes further to remove any sort of logic regarding management of the target dir.
=> feat: replace files in target directory instead of partial copy/delete

apps/wing/src/commands/compile.test.ts, apps/wing/src/commands/compile.ts
=> fix: verbose preflight stacktrace does not contain anything useful

examples/tests/valid/inflight_handler_singleton.test.w
Following up on #5478 and [@Chriscbr's comment](https://github.com/winglang/wing/pull/5478/files#r1462456582), verify that inflight clients are not shared across two separate instances of a cloud function.
=> chore: test that inflight clients are not reused across functions

.github/workflows/build.yml, libs/compatibility-spy/package.json, libs/compatibility-spy/src/index.ts, libs/compatibility-spy/test/spy.test.ts, libs/compatibility-spy/tsconfig.json, libs/compatibility-spy/tsup.config.ts, libs/compatibility-spy/turbo.json, libs/wingsdk/.projen/tasks.json, libs/wingsdk/.projenrc.ts, tools/hangar/__snapshots__/compatibility-spy.ts.snap, tools/hangar/src/compatibility-spy.test.ts
The recent addition of the compatibility-spy lib broke fork workflows. This is because it was attempting to compile during the e2e matrix, but it fails because the e2e matrix is not actually meant to rebuild things. This accidentally works on PRs from winglang/wing because we use turbo remote caching, so the `turbo compile` command pulled from the remote cache.
This PR instead utilizes @winglang/compatibility-spy as a package in hangar, avoiding any re-compilation. While there I also cleaned up the tsconfig and changed it to use tsup (since it was installed anyways).
=> chore: compatibility-spy build fails on PRs from forks

apps/wing-console/console/ui/src/ui/zoom-pane.tsx
=> fix(console): preserve min and max zoom levels when running zoom to fit

examples/tests/valid/extern_implementation.test.w, examples/tests/valid/impl_interface.test.w, libs/wingc/src/dtsify/mod.rs, libs/wingc/src/dtsify/snapshots/declarations.snap, libs/wingc/src/parser.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/impl_interface.test.w_compile_tf-aws.md
Fixes #5454 by raising an error when interface methods are declared without return types.
In addition to requiring return types on interfaces, I also made them required on extern function statements.
The language reference is a ambiguous and doesn't explicitly say return types are optional on class methods. It's probably a good idea to require return types there as well, but I imagine this is more controversial since some might argue it's okay to omit them and let the compiler infer them from function bodies. To avoid controversy I've left the existing behavior as is.
BREAKING CHANGE: Interface methods now require return types. This was required in earlier versions of Wing (v0.18.x) but due to regressions it was not enforced, so out of caution this change has been labeled as potentially …
=> fix(compiler)!: interface methods can be declared with no return type

.github/workflows/canary.yml, apps/wing/project-templates/wing/empty/main.w, apps/wing/project-templates/wing/empty/package.json, apps/wing/src/cli.ts, apps/wing/src/commands/__snapshots__/init.test.ts.snap, apps/wing/src/commands/init.test.ts, apps/wing/src/commands/init.ts, docs/contributing/01-start-here/05-development.md
Adds a new template named `empty` that with a minimal cloud function resource (proposed by @eladb). 
Misc:
- Added canary testing for all templates so we'll get notified if there's an issue with installing dependencies etc.
- Added unit tests that run all templates in CI
- Added contributing guide blurb
=> feat(cli): empty template

.github/workflows/canary.yml
GitHub actions claims to support bash on Windows so let's try this
=> fix: broken canary on windows

libs/wingsdk/src/std/map.ts
Based on #5512
Modified the documentation of the `Map.get` method where it said `undefined` but returned an error when the key was not found.
=> docs(sdk): modify documentation to match behaviour of `Map.get()`

libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/snapshots/completions/dot_before_returning_struct.snap
fixes #5511
See the added comment for the how/why of this change
=> fix: returning a struct literal after an incomplete reference breaks lsp completions

apps/wing/src/commands/init.test.ts, apps/wing/src/util.ts
Duplicate template names were being listed if we supported more than 1 language
=> fix(cli): wing new showing duplicate template names

apps/wing/src/commands/compile.ts, apps/wing/src/commands/run.ts, apps/wing/src/commands/test/test.test.ts, apps/wing/src/commands/test/test.ts, docs/docs/06-tools/01-cli.md, libs/wingcompiler/package.json
fixes #4839, specifically implementing @Chriscbr's suggestion https://github.com/winglang/wing/issues/4839#issuecomment-1804447937
Other changes:
- .ts files are now also matched by default for run, compile, and test
- Fixed the `main` and `types` entry in `@winglang/compiler`, which was not written correctly and has been causing errors in my ide for a long time
=> feat: `wing test` recursively finds entrypoints by default, and simpler filename filtering

libs/@wingcloud/framework/turbo.json
Resolves the build failure from [wingcloud-framework-](https://github.com/winglang/wing/actions/runs/7738555901/job/21101794210)
=> chore: wrong cache location for @wingcloud/framework build output

libs/wingsdk/.projen/deps.json, libs/wingsdk/.projenrc.ts, libs/wingsdk/package.json, pnpm-lock.yaml
The current version had a transitive dep that caused an `Unsupported engine` warning.
=> chore: update `@azure/identity` to version that supports node20

examples/wing-fixture/store.w, libs/wingc/src/dtsify/mod.rs, libs/wingc/src/dtsify/snapshots/optionals.snap
wingc currently emits an optional type in functions/fields like this:
```ts
interface StructyGuy {
a: (str) | undefined
}
```
While this is technically correct for the purpose of the runtime, it doesn't allow you to completely omit `a`.
This PR generates it like this:
```ts
interface StructyGuy {
a?: (str) | undefined
}
```
This may seem verbose, but in wing the `?` on a type technically does mean both of these things. It's possible that in certain contexts we could simplify it to improve how it looks to users, but this behavior is still correct so I think it's fine to continue on this path.
=> fix: ts types for optional requires explicit `undefined`

.github/workflows/build.yml, examples/tests/error/turbo.json, examples/tests/invalid/turbo.json, examples/tests/sdk_tests/turbo.json, examples/tests/valid/turbo.json, examples/wing-fixture/turbo.json, tools/hangar/__snapshots__/test_corpus/sdk_tests/http/fetch.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/http/fetch.test.w_test_sim.md, turbo.json
Mutations for hangar have been broken since the update to Node20, because PRs have not been running Node20 with hangar by default.
Additionally, wing-fixture changes have not been picked up by hangar to do snap updates. Not sure if this pre-existed the above issue, but I simplified the "topo" thing to better catch changes regardless.
=> chore(repo): mutation for hangar broken and simplified turbo's "topo" handling for example projects

libs/wingc/src/lsp/snapshots/completions/incomplete_if_statement.snap, libs/wingsdk/src/std/map.ts
The `MutMap.get` method throws an error and does not return undefined.
=> fix(docs): incorrect returns for MutMap.get

libs/wingc/src/jsify/snapshots/entrypoint_this.snap, libs/wingc/src/jsify/snapshots/fails_when_referencing_this_from_static.snap, libs/wingc/src/jsify/tests.rs, libs/wingc/src/lib.rs
Fixes #5649
Added a simple test to the jsifier because it uses `main.w` as the filename.
=> fix: main.w files cannot use `this`

libs/wingsdk/src/target-tf-aws/api.ts, libs/wingsdk/src/target-tf-aws/function.ts, libs/wingsdk/src/target-tf-aws/platform.ts, libs/wingsdk/test/target-tf-aws/__snapshots__/api.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/bucket.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/counter.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/dynamodb-table.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/function.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/on-deploy.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/queue.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/schedule.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/table.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/topic.test.ts.snap, libs/wingsdk/test/target-tf-aws/api.test.ts, libs/wingsdk/test/target-tf-aws/function.test.ts
Supports deploying lamdbas and api gateways behind a vpc. also ensures that when API gateways are deployed behind vpcs that they use an VPC endpoint for invocation
to enable parameters `tf-aws/vpc_api_gateway` and `tf-aws/vpc_lambda` must be set
I tested the implementation in my own aws account as well:
Here we cannot hit the endpoint publicly
Here the lambda was able to invoke the API gateway
=> feat(sdk): support apig and lambda behind vpc

examples/tests/invalid/interface.test.w, libs/wingc/src/parser.rs, tools/hangar/__snapshots__/invalid.ts.snap
Fixes https://github.com/winglang/wing/issues/5663 by adding a compiler diagnostic when interface methods are defined without type annotations.
=> fix(compiler): interface method param types are required

examples/tests/invalid/class.test.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap
Fixes #1635
Fixing this required a bit of refactoring code around because even when there are member name conflicts, we want to make sure all of the code in the method still gets type checked. Type checking the body requires knowing the type signature of the method. But the method's correct type isn't available in the environment because of the name conflicts.
To solve this, I added some logic to keep track of a mapping of method name symbols to the method types within `type_check_class` (where `type_check_method` is called from). Since the keys of the map are symbols, and each symbol has a name and source location, the method types won't overwrite each other. …
=> fix(compiler): panic when method has same name as a field

docs/docs/01-start-here/02-installation.md
I accidentally removed this in my last PR, and it's causing a build error
=> chore: add missing metadata back into docs page

libs/@wingcloud/framework/src/internal.ts
Noticed that ts compilation tests were still timing out, wanted to partially address them.
Used https://www.totaltypescript.com/tsconfig-cheat-sheet as a good guide to build some out.
I suspect skipLibCheck will help a lot, and honestly it's probably a good thing to avoid the unnecessary .d.ts checks.
=> fix: tsconfig options in framework are slow

apps/wing/project-templates/typescript/private-api/wing.toml, apps/wing/project-templates/wing/private-api/wing.toml, libs/wingsdk/src/target-tf-aws/api.ts, libs/wingsdk/src/target-tf-aws/app.ts, libs/wingsdk/src/target-tf-aws/function.ts, libs/wingsdk/src/target-tf-aws/platform.ts, libs/wingsdk/src/target-tf-aws/redis.ts, libs/wingsdk/test/target-tf-aws/__snapshots__/redis.test.ts.snap, libs/wingsdk/test/target-tf-aws/platform.test.ts, tools/hangar/__snapshots__/test_corpus/valid/redis.test.w_compile_tf-aws.md
These changes support providing multiple subnets (public and private) to the tf-aws vpc that is used for resources that require vpcs.
=> fix(platforms): tf-aws vpc does not support multiple subnets

docs/contributing/01-start-here/05-development.md
The Markdown link to the project templates directory is malformed and does not render properly on https://www.winglang.io/contributing/start-here/development#-how-do-i-add-a-quickstart-template-to-the-wing-cli. This change fixes the link.
=> chore(docs): fix malformed markdown link on development page

apps/vscode-wing/src/lsp.ts, apps/wing/src/commands/lsp.ts
No real way to add tests for this, just did local testing
=> fix(vscode): editor.parameterHints.enabled option not respected

libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/snapshots/completions/new_expression_partial_namespace.snap
In parser contexts where we know something is a type but it has no `.`, completions were not working.
This is for situations like the text following `new`, `impl`, `extends`. Once you start typing after that, no completions would be available.
=> fix(vscode): missing completions for types (identifiers)

libs/wingsdk/src/shared/misc.ts, libs/wingsdk/src/target-sim/dynamodb-table.inflight.ts, libs/wingsdk/src/target-sim/redis.inflight.ts, libs/wingsdk/test/shared/misc.test.ts
Fixes #5674 and Fixes #5070 by ensuring that disallowed characters are removed from Docker container names before they are started.
- I considered leveraging https://github.com/winglang/wing/blob/main/libs/wingsdk/src/shared/resource-names.ts for this but realized the options are a bit overkill for what is required when naming Docker containers. However, I'd be happy to move/rewrite if you'd prefer a different solution!
- This affects both Redis and DynamoDB docker containers started by the simulator, but does not automatically extend to any future containers that the simulator might use. Given that I'm new to the project, I'm not sure how to best achieve that yet.
- Based on my testing, container names can be >1000 characters long, so length should not be a problem.
- I confirmed that …
=> fix(sdk): invalid characters in container names for redis and dynamo

libs/wingsdk/src/target-sim/api.inflight.ts, libs/wingsdk/test/target-sim/api.test.ts
While preparing a demo I noticed having ports shuffled every time you reload the simulator is annoying as a user. This implements a small fix so that the port previously used will be reused if it's still available after the simulator reloads.
=> feat(sdk): reuse ports for cloud.Api in simulator

examples/tests/sdk_tests/bucket/signed_url.test.w
As detailed [here](https://github.com/winglang/wing/issues/5348#issuecomment-1953275490), the `curl` command always returns with 0 exit status unless the `--fail` flag is provided, so there's no need to avoid throwing errors.
=> chore(sdk): remove unneeded option from test

libs/wingc/src/lsp/snapshots/goto_definition/class_init_this_field.snap, libs/wingc/src/lsp/snapshots/goto_definition/user_defined_type_reference_property.snap, libs/wingc/src/lsp/snapshots/hovers/builtin_instance_method.snap, libs/wingc/src/lsp/snapshots/hovers/class_init_this_field.snap, libs/wingc/src/lsp/snapshots/hovers/class_property.snap, libs/wingc/src/lsp/snapshots/hovers/multipart_reference_hover_middle.snap, libs/wingc/src/lsp/snapshots/hovers/static_method.snap, libs/wingc/src/lsp/snapshots/hovers/static_stdtype_method.snap, libs/wingc/src/lsp/snapshots/hovers/user_defined_type_reference_property.snap, libs/wingc/src/lsp/symbol_locator.rs
The link displayed under "goto definition" of a type/obj property reference included the entire reference instead of just the property:
Fixed the return span in these cases. Looks better now.
=> fix(vscode): wrong link under goto definition of object property

apps/wing-console/console/design-system/src/modal.tsx
Update z-index value for Sign In component to fix stacking order.
Fixes #5750.
=> fix(console): error screen stays on top of the sign in modal

apps/wing-console/console/server/src/router/endpoint.ts, apps/wing-console/console/ui/src/ui/endpoint-tree.tsx
The endpoints UI now looks like this:
=> feat(console): improve endpoints UI

apps/wing/src/commands/init.ts, apps/wing/src/commands/pack.ts
If a user's installation of wing somehow resulted in file the installation files not being owned by the user, there is a chance that the user running wing commands does not have full access to the template files. 
For example running `sudo npm install -g winglang` would result in all the package files being owned by root, which the default would mean other users have read access but not write. For template quickstarts we should not care if the user has `write` access the important bit is just `read` so this addresses that issue
Closes: https://github.com/winglang/wing/issues/5754
=> fix(cli): template X is not available in wing

libs/wingcompiler/src/compile.ts, tools/hangar/turbo.json, turbo.json
Fixes #5510
The awscdk platform was importing `registerTokenResolver()` directly from `@winglang/sdk/lib/core/tokens`. This was bypassing preflight logic to always force imports from the SDK to resolve from the same place because it was only checking for imports specifically from `@winglang/sdk` only. This caused it to load it as a different module which had a global that was unused by the rest of the SDK logic.
I was able to replicate the original issue and this fixed it in that same scenario.
Automated testing this is very difficult/slow because it requires a certain scenario that is very realistic: A global install of the SDK and a "local" install of a platform like awscdk. When you install `@winglang/platform-awscdk` it comes with its own copy of `@winglang/sdk`. In our hangar tests …
=> fix: unable to resolve tokens inflight from awscdk platform

.github/workflows/close-stale.yml
Seems like we review stale issues too often.
We decided to increase the number of days before an inactive issue becomes stale from 60 to 90 days.
=> chore(repo): increase days before issue turns stale

libs/wingsdk/src/target-sim/api.inflight.ts, libs/wingsdk/test/target-sim/api.test.ts
=> fix(sdk): error when cloud.Api port cannot be reused

apps/wing-console/console/ui/src/ui/zoom-pane.tsx
The changes in this commit restrict dragging the map using the space key. When the space key is pressed, the map becomes draggable and the user can move it around. The cursor also changes to a grab cursor when the space key is pressed. This provides a more intuitive way for users to interact with the map.
=> feat(console): restrict dragging the map when using the space key

.github/workflows/mutation.yml, .github/workflows/new-pull-request-comment.yml
Fixes #5115
The mutation workflow is using the wrong `head` for forks when the repo name is `wing` (which it usually is). This worked before, I suspect the API changed, but in any case this fixes things.
Also updated the initial PR comment workflow to work on forks.
Tested in https://github.com/MarkMcCulloh/wing-distributed-workflow
=> chore: mutation workflow and owner comment workflow broken on forks

examples/tests/invalid/immutable_container_types.test.w, examples/tests/invalid/json.test.w, examples/tests/invalid/json_static.test.w, examples/tests/invalid/primitives.test.w, examples/tests/invalid/structs.test.w, examples/tests/invalid/unknown_symbol.test.w, libs/wingc/src/jsify/snapshots/fails_if_referencing_unknown_field.snap, libs/wingc/src/jsify/snapshots/fails_when_referencing_this_from_static.snap, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/symbol_env.rs, tools/hangar/__snapshots__/invalid.ts.snap
Fixes #2769
A revisit of #5761 
`x_instance.unkonwn_prop` resulted in:
```
Unknown symbol "unkonwn_prop"
```
And now results in:
```
Property "unkonwn_prop" doesn't exist in "X"
```
=> fix(compiler): unknown property diagnostic is same as unknown symbol 

apps/wing-console/console/ui/src/ui/edge-item.tsx, apps/wing-console/console/ui/src/ui/elk-map-nodes.tsx
Map nodes in the Console will have their borders faded out in order to allow focusing on the selected node and their relevant connections.
=> feat(console): fade out node borders

apps/wing/project-templates/wing/private-api/main.w
I promise this is the last change for the Workshop tomorrow 😁 
Make the consumer functions only deploy if using `tf-aws` makes running this in the sim less confusing.
=> chore(cli): private-api template make consumers for tf-aws only

docs/docs/04-standard-library/cloud/api.md, examples/tests/valid/api_cors_custom.test.w, examples/tests/valid/website_with_api.test.w, libs/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap, libs/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap, libs/wingc/src/lsp/snapshots/completions/partial_type_reference_annotation.snap, libs/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap, libs/wingsdk/src/cloud/api.ts, libs/wingsdk/test/target-sim/api.test.ts, tools/hangar/__snapshots__/test_corpus/valid/api_cors_custom.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/website_with_api.test.w_compile_tf-aws.md
Fixes #5741
The `Access-Control-Allow-Origin` header must contain only one origin. If we provide an array with more than one origin, then the origins are joined with commas. This causes the CORS preflight to fail because the browser expects only one origin. The proper solution to this problem would be to select one of the origins from the list. However, as a temporary fix, I changed the type of `allowOrigin` from `Array<string>` to simply `string`. The expectation is that the developer should only provide one origin. This prevents the CORS preflight from failing. However, it also disallows developers from having more than one origin. …
=> fix: change the type of allowOrigin to string (#5741)

libs/wingsdk/test/target-sim/__snapshots__/bucket.test.ts.snap, libs/wingsdk/test/target-sim/bucket.test.ts
Fixes #5895
The goal of the test is to make sure we don't emit events for object creation twice. We can just avoid the problem of stopping the sim by doing it after getting the snapshot fails.
No matter what, the sim will be stopped due to the way the test SimApp works.
=> chore: fix nondeterministic bucket sim test

.github/workflows/mutation.yml
Fixes #5894
Not sure what the fundamental issue is, but this is a slightly reworked set of scripts that relies more on head branch rather than headSha. Also ensures the comment works better by using the PR number. Also has a smidge more logging.
Smoke test here https://github.com/MarkMcCulloh/wing-distributed-workflow/pull/7 although it's not a conclusive test
=> chore: fix mutation workflow comment and wrongly updating different PRs

libs/tree-sitter-wing/grammar.js
The regex flavor in tree-sitter is no longer disjunct between rust and js, it aligns with rust which requires escaping braces.
Generating fails in the latest cli release without this change.
@gshpychka @MarkMcCulloh
=> fix: escape braces in tree-sitter regex

apps/wing-console/console/server/src/router/app.ts, apps/wing-console/console/ui/src/ui/elk-map-nodes.tsx, apps/wing-console/console/ui/src/ui/resource-metadata.tsx
resolves: https://github.com/winglang/wing/issues/5939
```
bring cloud;
class A {
new() {
nodeof(this).title = "MyTitle";
nodeof(this).color = "violet";
}
}
class B {
new() {
}
}
new A();
new cloud.Bucket();
new B();
```
=> fix(console): custom resource title is not shown in console

libs/wingsdk/.projenrc.ts, libs/wingsdk/cdktf.json
AzureRM Terraform provider [v3.96.0](https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.96.0) adds Azure Functions Support for Node.js 20, resolving the problem with the deployment.
Closes #5623
=> fix(sdk): allow Node.js 20 for `cloud.Function` on `tf-azure` platform

apps/wing/project-templates/wing/react-vite/package.json
command was failing on windows
=> fix(cli): react vite template post install command

apps/wing/project-templates/wing/react-vite/package.json
Seems like a bug on Windows where using `--prefix` causes npm to use the wrong postinstall hook 🤷
=> fix: react-vite template fails to `npm install` on Windows

apps/vscode-wing/.projenrc.ts, apps/vscode-wing/package.json, docs/docs/06-tools/03-debugging.md, libs/wingsdk/src/shared/legacy-sandbox.ts, libs/wingsdk/src/shared/sandbox.ts, libs/wingsdk/test/simulator/simulator.test.ts, libs/wingsdk/test/util.ts
To support this, a change was made to the simulator to bundle inflights next to the entrypoint. This helps VSCode (and other debugger probably) to discover the file that's running.
=> feat(vscode): improved wing debugging and docs (breakpoints)

examples/tests/valid/optionals.test.w, libs/tree-sitter-wing/grammar.js, libs/tree-sitter-wing/test/corpus/expressions.txt, libs/wingc/src/parser.rs, tools/hangar/__snapshots__/test_corpus/valid/optionals.test.w_compile_tf-aws.md
Fixes #1875
This fixes the issue by updating the precedent rules so the operation is right-associative. For now, expressions like `a ?? b` or `a ?? b ?? c` still have to return a non-optional value (like Rust's unwrap_or), but we can consider making it more flexible / open in the way that C# or Swift allows if appropriate in the future.
=> fix(compiler): cannot chain ?? expressions

.github/workflows/build.yml, tools/hangar/src/platform.test.ts
The quality gate was succeeding if previous steps timed out
=> chore(repo): ensure quality gate fails if previous steps aren't successful

apps/wing/project-templates/wing/react-vite/backend/package.json
vite resource wasn't working windows
=> fix(cli): react vite template failed when running in windows

libs/wingc/src/lsp/sync.rs, libs/wingc/src/type_check.rs
Fixes #6004, I was able to replicate consistently and see that this change fixes it
Instead of attempting to reuse `Types`, let's just create a new one. This should cause all the existing types and symbol environments to be dropped, but that's okay because we immediately populate the new one with data.
No clue how to add a real test for this. The current rust-based tests don't have a multi-file system and I'm not sure this change is worth that effort to improve (as nice as it would be)
=> fix: language server occasionally duplicates types a fails compilation

examples/jsii-fixture/package.json, pnpm-lock.yaml
When running `pnpm build`, `turbo package` is run on all projects that have a "package" script. I noticed that this produced a .tgz that was not gitignored in jsii-fixture.
jsii-fixture is only ever used via a symlinked install, so producing a tgz is pointless afaik.
=> chore: remove package script from jsii-fixture

libs/wingsdk/src/target-sim/api.inflight.ts, libs/wingsdk/src/target-sim/bucket.inflight.ts, libs/wingsdk/src/target-sim/counter.inflight.ts, libs/wingsdk/src/target-sim/endpoint.inflight.ts, libs/wingsdk/test/target-sim/bucket.test.ts
Fixes #6010
The underlying issue is caused by state files only getting partially written to disk when the simulator host process is killed in the middle of its shutdown. Due to the weird sequencing of operations, an empty file would end up being written (instead of no file or a file with valid JSON). Using synchronous calls for saving state files should reduce these kinds occurrences.
No tests were added because there isn't really a reliable way to kill a process precisely in the middle of a asynchronous Node.js function call. 
There's still a bug lurking where the console isn't letting the simulator finish shutting down, but this extra resiliency shouldn't hurt. …
=> fix(sdk): unexpected end of JSON input error

.github/workflows/build.yml, examples/tests/sdk_tests/container/container.test.w
In our current CI, we can't run tests with containers on windows or mac
=> chore: skip container e2e tests on windows/mac

tools/compatibility-matrix-automation/src/matrix-automation.ts
preventing those "empty" PRs: 
https://github.com/winglang/wing/pull/6039
=> chore: add `\n` to matrix generation

.gitignore, docs/docs/04-standard-library/cloud/function.md, libs/wingsdk/src/cloud/function.md
Fix multiple errors in code sample of cloud.Function that doesn't compile.
=> fix(docs): code sample for cloud.Function that doesn't compile

apps/wing/package.json, apps/wing/src/commands/run.ts, apps/wing/src/util.before-shutdown.ts, pnpm-lock.yaml
Previously, the `wing it` didn't wait for the Console to close and release its resources.
=> fix(cli): handle shutdown events gracefully

.github/workflows/build.yml
=> fix: tunnels library is not published

apps/wing-console/console/server/src/utils/simulator.ts
This reverts commit 08ff90b4c9b2099f87d98ed848e16af5d8ee60ad.
The `cloud.Function`s don't get replaced after changing the source code of a wingfile.
=> revert(console)!: use `simulator.update()` (#6069)

docs/docs/04-standard-library/std/array.md, examples/tests/sdk_tests/std/array.test.w, libs/wingsdk/src/std/array.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/std/array.test.w_test_sim.md
=> feat(sdk): array.slice()

examples/tests/sdk_tests/bucket/get.test.w, libs/wingsdk/src/shared-aws/bucket.inflight.ts, main.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/get.test.w_test_sim.md
=> fix(sdk): can retrieve empty object from bucket on AWS platforms

examples/tests/valid/bring_extend_non_entry.test.w, examples/tests/valid/extend_non_entrypoint.w, libs/wingc/src/jsify.rs, tools/hangar/__snapshots__/test_corpus/valid/bring_extend_non_entry.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/bring_extend_non_entry.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/extend_non_entrypoint.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/inherit_stdlib_class.test.w_compile_tf-aws.md
**NOTE: ** This is really actually only a bandaid solution. It fixes half the problem.
There is a larger issue at hand described in: https://github.com/winglang/wing/issues/6093 
The real issue is that we need a way to pass App instance or Platform manager to non-entrypoint files to use methods like `typeForFqn` or `new` but theres a pretty nasty cyclical dependency issue. 
currently working on another pr, that will probably take more time, in the meantime this unblocks: https://github.com/winglang/wing/issues/4791
=> fix(compiler): unable to extend jsii classes in non-entrypoint

docs/docs/03-language-reference.md, examples/tests/error/inflight_stacktraces.test.w, libs/wingc/src/lsp/snapshots/completions/empty.snap, libs/wingc/src/lsp/snapshots/completions/hide_parent_symbols_defined_later.snap, libs/wingc/src/lsp/snapshots/hovers/builtin_in_inflight.snap, libs/wingc/src/lsp/snapshots/hovers/builtin_in_preflight.snap, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/error.ts.snap, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/debug_env.test.w_test_sim.md
This PR adds support for writing custom assertion messages with the built-in `assert()` function:
```js
let x = -3;
assert(x >= 0, "x must be non-negative");
```
=> feat: assert messages

examples/tests/valid/structs.test.w, tools/hangar/__snapshots__/test_corpus/valid/structs.test.w_compile_tf-aws.md
Closes #2648 
Self referential structs already work - just adding a test to make sure it keeps working.
=> chore(compiler): self referential struct

libs/wingsdk/src/simulator/simulator.ts, libs/wingsdk/src/target-sim/api.inflight.ts, libs/wingsdk/src/target-sim/bucket.inflight.ts, libs/wingsdk/src/target-sim/container.inflight.ts, libs/wingsdk/src/target-sim/counter.inflight.ts, libs/wingsdk/src/target-sim/domain.inflight.ts, libs/wingsdk/src/target-sim/endpoint.inflight.ts, libs/wingsdk/src/target-sim/event-mapping.inflight.ts, libs/wingsdk/src/target-sim/function.inflight.ts, libs/wingsdk/src/target-sim/on-deploy.inflight.ts, libs/wingsdk/src/target-sim/queue.inflight.ts, libs/wingsdk/src/target-sim/react-app.inflight.ts, libs/wingsdk/src/target-sim/redis.inflight.ts, libs/wingsdk/src/target-sim/schedule.inflight.ts, libs/wingsdk/src/target-sim/secret.inflight.ts, libs/wingsdk/src/target-sim/service.inflight.ts, libs/wingsdk/src/target-sim/state.inflight.ts, libs/wingsdk/src/target-sim/table.inflight.ts, libs/wingsdk/src/target-sim/test-runner.inflight.ts, libs/wingsdk/src/target-sim/topic.inflight.ts, libs/wingsdk/src/target-sim/website.inflight.ts, libs/wingsdk/test/simulator/simulator.test.ts
Fixes #6116 by allowing a simulator resource to determine it's update "plan" when new configuration arrives.
For now, both `cloud.Function` and `cloud.Service` always return "REPLACE" which means that these resources will always get updated. In a future commit we can be more granular about the update by calculating the bundle hash.
=> fix(sdk): functions and services are never updated in the simulator

libs/wingsdk/src/shared/sandbox.ts, libs/wingsdk/test/simulator/cleanup.test.ts
Fixes #6018
If the Wing Console is terminated by Ctrl + C, it gracefully waits for resources to be shut down (thanks to https://github.com/winglang/wing/pull/6051). However there's a latent bug since the kill signal is still propagated to child processes, like those running inflight code for cloud.Service. This changes the behavior so the kill signal is longer propagated, and the simulator will be fully responsible for shutting down its child processes.
If this doesn't solve all our issues (or runaway processes occur in some other ways), then we might need some kind of daemon for tracking processes created by the Wing simulator - but I'm hoping we might be able to avoid this kind of complexity for now.
*By submitting this pull request, I confirm that my contribution is made under the …
=> fix(sdk): cloud.Service shutdown code is ignored when Wing Console is stopped

docs/contributing/999-rfcs/2024-03-24-snapshot-tests.md
An RFC for https://github.com/winglang/wing/issues/5958.
A proposal for a feature that will capture a snapshot of the synthesis output from `wing test` to reduce regressions in cloud implementations.
=> rfc: cloud snapshot tests

apps/wing/src/commands/test/test.ts, libs/wingsdk/src/target-sim/container.inflight.ts, libs/wingsdk/src/target-sim/test-runner.inflight.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/container/container.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/function/invoke.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/function/invoke_async.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/http/fetch.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/service/http-server.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/service/minimal.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/service/stateful.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/inflight_handler_singleton.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/print.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/redis.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/resource.test.w_test_sim.md, tools/hangar/src/utils.ts
fixes: #4995 
I added Traces of type "log" to be included in the test result traces.
I haven't written a ts test since it's better to test via the snapshots
=> fix(sdk): `cloud.service` logs are not shown in cli simulator tests

apps/wing-console/console/server/src/index.ts, apps/wing-console/console/server/src/utils/simulator.ts
Simulator updates feature is not fully ready yet...
By default, open the Console without the new simulator update feature.
Enable users to use this feature by setting the following env var:
`ENABLE_SIM_UPDATES=true`
=> feat(console): hide simulator updates feature behind a feature flag

docs/docs/06-tools/03-debugging.md, libs/wingsdk/src/shared/sandbox.ts
During normal usage, when an unhandled exception occurs inflight we will prepare a stack trace for the user to show them where things went wrong. When debugging, the `throw` itself tells you it happened first. Since we were technically catching all inflight errors, the useful concept of "break on uncaught exception" didn't work.
With this change, the original errors remain uncaught and we can still communicate that error with the parent process.
=> fix: missing uncaught inflight exceptions when debugging

docs/contributing/01-start-here/07-wingsdk.md
**PR Summary**:
I noticed that a section in `docs/contributing/01-start-here/07-wingsdk.md` remained unchanged following updates in PRs such as #690, #4149, #4256, and #1576. This PR updates the documentation and resources locations to reflect those changes.
=> fix(docs): update the location of different resources

examples/tests/invalid/missing_return.test.w, examples/tests/valid/while_loop_await.test.w, libs/wingc/src/type_check/has_type_stmt.rs, tools/hangar/__snapshots__/invalid.ts.snap
Fixes #5481
Don't recurse into inner closures when searching for a return stmt for missing `return` diagnostics.
=> fix(compiler): no error when missing `return` and there's an inner closure that has a `return`

examples/tests/invalid/missing_return.test.w, libs/wingc/src/type_check/has_type_stmt.rs, tools/hangar/__snapshots__/invalid.ts.snap
Fixes #6172
This is take 2 of #5481. Now we ignore **all** inner function definitions (no just closures) when checking if a functions has a `returns` statement. Previously we didn't catch the case when there's an inner method with a `return` statement.
=> fix(compiler): no missing `return` error when there's an inner method with `return`

docs/docs/04-standard-library/cloud/domain.md, libs/wingsdk/src/cloud/domain.md
The parameter to `cloud.Domain` should be `domainName` and not `domain`.
And because of the additions of the platform parameters, it seems that it is not possible to use the parameters in the same way in the tests: https://github.com/winglang/wing/blob/main/libs/wingsdk/test/target-tf-aws/domain.test.ts
=> fix(docs): `cloud.Domain`

examples/tests/sdk_tests/queue/set_consumer.test.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/set_consumer.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/set_consumer.test.w_test_sim.md
Tested this with `wing test -t tf-aws` on my AWS account.
=> chore(sdk): add test case for queue setConsumer

apps/wing-console/console/ui/src/ui/elk-map-nodes.tsx, apps/wing-console/console/ui/src/ui/resource-metadata.tsx
resolves: https://github.com/winglang/wing/issues/5994
for the following code:
```
bring cloud;
class A {
new() {
nodeof(this).title = "MyTitle";
nodeof(this).color = "violet";
}
}
class B {
new() {
}
}
new A();
new cloud.Bucket() as "MyBucket";
new cloud.Bucket();
new B();
```
the console will display the following:
=> fix(console): node title ignores the user defined resource name

apps/wing/fixtures/invalid6/package.json, apps/wing/fixtures/invalid6/util.ts, apps/wing/fixtures/valid1/package.json, apps/wing/src/commands/pack.test.ts, apps/wing/src/commands/pack.ts
=> fix(cli): `wing pack` does not enforce using `peerDependencies`

.cargo/config.toml, Cargo.lock, libs/tree-sitter-wing/Cargo.toml, libs/tree-sitter-wing/bindings/rust/build.rs, libs/tree-sitter-wing/package.json, libs/tree-sitter-wing/turbo.json, libs/wingc/Cargo.toml, pnpm-lock.yaml
Turns out tree-sitter is releasing stuff much faster nowadays!
While doing this, I noticed we no longer need to hack the C build as much. Removed that the whole sysroot thing. I could remove the locked CC and AR but it has actually been pretty nice having that locked to not worry about what contributors have installed. I'd be nice to one day use zig instead.
This new tree-sitter version also seems to compile a litter faster, so that's a nice bonus.
=> chore: update tree-sitter to official version

apps/vscode-wing/.projenrc.ts, apps/vscode-wing/package.json, apps/vscode-wing/src/project/vscode_types.ts
Missed this change in https://github.com/winglang/wing/pull/6217
Now vscode will automatically use the builtin debugger when you have a wing file open instead of asking you to pick one
=> fix(vscode): wing debugger is not a default choice for .w files

Cargo.lock, apps/wing-console/console/app/package.json, apps/wing-console/console/server/package.json, apps/wingcli-v2/Cargo.toml, apps/wingcli-v2/src/cli.rs, libs/wingsdk/package.json, pnpm-lock.yaml
https://github.com/winglang/wing/security/dependabot/151
https://github.com/winglang/wing/security/dependabot/119
=> chore: update `express` and remove `atty` (for dependabot advisory)

libs/wingsdk/src/shared/sandbox.ts, libs/wingsdk/src/target-sim/function.inflight.ts, libs/wingsdk/test/target-sim/function.test.ts
hangar sometimes run into this:
`InvokeAsync (payload=undefined) failure. Error: Process exited with code null, signal SIGTERM`
I believe this can happen if InvokeAsync is running while it receive the SIGTERM cleanup. This should not be considered a failure, just a normal part of the cleanup process.
The test relies on a sleep so I'm open to better ideas, but it does replicate the issue on `main`
=> fix: invokeAsync can fail during simulator cleanup

apps/wing/src/commands/test/test.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/push.test.w_test_sim.md
When `wing test` is run against the simulator, logs are streamed to the CLI output. But for technical reasons not all logs are associated with tests. For example, there's a singleton class named `TestRunner` which can have an overridden implementation per target. This is a side effect of how we currently implement test isolation as construct subtrees.
As a small improvement, when events are emitted from these resources, this PR changes the current behavior so they're logged to standard output with the "(no test)" label instead of being ignored.
=> chore: improve log filtering

examples/tests/valid/indexing.test.w, libs/tree-sitter-wing/grammar.js, libs/tree-sitter-wing/src/grammar.json, libs/tree-sitter-wing/test/corpus/expressions.txt, tools/hangar/__snapshots__/test_corpus/valid/indexing.test.w_compile_tf-aws.md
Fixes #6276 by adding a precedence level for array access expressions. I inserted the precedence right below member access expressions, similar to JavaScript's operator precedence [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence#table).
=> fix(compiler): array access operator precedence

examples/tests/sdk_tests/queue/set_consumer.test.w, libs/wingsdk/src/target-sim/queue.inflight.ts, tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/set_consumer.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/set_consumer.test.w_test_sim.md
Fixes a regression from #6060 that prevented messages from being processed in parallel (we noticed this bug when it caused test failures in one of our winglibs: https://github.com/winglang/winglibs/actions/runs/8767429765/job/24060674878).
I confirmed the updated test (set_consumer.test.w) passes when ran on my AWS account using the `tf-aws` target.
=> fix(sdk): cloud.Queue does not send messages in parallel

docs/docs/055-platforms/awscdk.md, libs/awscdk/package.json, libs/awscdk/src/app.ts, libs/awscdk/test/platform.test.ts
In order to fix #6279, we need synthesis to be triggered by the CDK CLI instead of directly from the Wing CLI.
This is actually really easy to do. All you need is to create a `cdk.json` file (or use one from `cdk init`) and modify the `app` and the `output` options like so:
```json
{
"app": "CDK_STACK_NAME=MyStack wing compile --platform @winglang/platform-awscdk main.w",
"output": "target/main.awscdk"
}
```
Then, you can simply use `cdk deploy`, `cdk diff`, `cdk synth` as if it was a normal CDK app. No need to explicitly interact with the Wing CLI in this case.
To allow context lookups, we need to support specifying the stack's AWS environment (account/region), so two new environment variables have been added: `CDK_AWS_ACCOUNT` and `CDK_AWS_REGION`. These can be set together with …
=> fix(platforms): unable to perform awscdk context lookups

libs/wingsdk/src/shared/misc.ts, libs/wingsdk/src/target-sim/container.inflight.ts, libs/wingsdk/src/target-sim/container.md, libs/wingsdk/test/target-sim/container.test.ts, libs/wingsdk/test/target-sim/my-docker-image.mounted-volume/Dockerfile, libs/wingsdk/test/target-sim/my-docker-image.mounted-volume/index.js
To support retaining the state of `sim.Container` across separate Wing Console sessions, this PR adds the capability to reference the resource's state directory through the `WING_STATE_DIR` environment variable. This will be used by the `postgres` winglib to persist state through a mounted volume:
```js
let container = new sim.Container(
name: "postgres",
image: image,
env: {
POSTGRES_PASSWORD: "password"
},
volumes: ["$WING_STATE_DIR/pgdata:/var/lib/postgresql/data"],
containerPort: 5432
);
```
Related to #6284
=> feat(sdk): support mounting sim.Container to state directories

libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/snapshots/completions/call_struct_expansion.snap, libs/wingc/src/lsp/snapshots/completions/call_struct_expansion_partial.snap, libs/wingc/src/lsp/snapshots/completions/empty.snap, libs/wingc/src/lsp/snapshots/completions/hide_parent_symbols_defined_later.snap, libs/wingc/src/lsp/snapshots/completions/only_show_symbols_in_scope.snap, libs/wingc/src/lsp/snapshots/completions/struct_definition_types.snap, libs/wingc/src/lsp/snapshots/completions/struct_literal_value.snap, libs/wingc/src/lsp/snapshots/completions/struct_show_values.snap, libs/wingc/src/lsp/snapshots/completions/type_annotation_shows_struct.snap, libs/wingc/src/lsp/snapshots/completions/type_parameter.snap
=> fix: missing built-in types in LSP auto-completion

libs/wingsdk/src/platform/platform-manager.ts
Closes: https://github.com/winglang/wing/issues/6147
=> fix(platforms): confusing error message when unable to load platform

docs/contributing/999-rfcs/2024-03-14-explicit-lift-qualification.md
[rendered version](https://github.com/winglang/wing/blob/yoav/rfc-explicit_lift_qualification/docs/contributing/999-rfcs/2024-03-14-explicit-lift-qualification.md)
Related to #76, #5935
=> rfc: explicit lift qualification

.github/workflows/build.yml
Running `playwright install --with-deps` fails because it executes `apt update` in the background, which is failing on the `latest ubuntu-22.04` image release.
Related to [Issue #9733](https://github.com/actions/runner-images/issues/9733).
Thanks to the temporary fix provided [here](https://github.com/actions/runner-images/issues/9733#issuecomment-2074655660) 🙌.
=> fix(console): playwright install fails

examples/tests/valid/new_in_static.test.w, examples/tests/valid/new_in_static_lib.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/test_corpus/valid/new_in_static.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/new_in_static_lib.w_compile_tf-aws.md
Fixes #6188
The fix removes a check that was in place to prevent instantiating such classes. The test itself is buggy because of #6323, so it only worked on non-entry point files. The test can be safely removed since we now allow instantiating preflight classes in static methods (see #6040).
=> fix(compiler): can't instantiate preflight classes in static mehtods defined in non-enty files

examples/tests/sdk_tests/container/mount.test.w, libs/wingsdk/src/target-sim/container.inflight.ts, libs/wingsdk/src/target-sim/container.md, libs/wingsdk/test/target-sim/container.test.ts, libs/wingsdk/test/target-sim/my-docker-image.mounted-volume/index.js, tools/hangar/__snapshots__/test_corpus/sdk_tests/container/mount.test.w_test_sim.md
Another pass at solving #6284
The approach taken in https://github.com/winglang/wing/pull/6295 where we allow users to bind to the state directory is problematic because docker sometimes changes the permissions of directories on the user's file system after mounting them. This was causing `wing test` to fail (fixed in https://github.com/winglang/wing/pull/6320) and `wing pack` to fail as well.
This PR reworks the API so that data can be persisted via named volumes. Specifically, an anonymous docker volume can be specified, and Wing will automatically name it and reuse it across Wing Console runs. The change should fix the previous issues since named volumes are managed by docker.
The main downside of this approach is that deleting your `target` directory or the state files in `.state/` …
=> feat(sdk): reuse volumes for sim.Container

docs/docs/055-platforms/tf-aws.md
Fixes the name of the platform being referenced, updates from `tf-gcp` to `tf-aws`
=> fix(docs): fixing name of platform

apps/wing/src/cli.ts, apps/wing/src/commands/compile.ts, apps/wing/src/commands/pack.ts, apps/wing/src/commands/run.ts, apps/wing/src/env.ts, libs/wingsdk/src/target-sim/secret.inflight.ts
Closes: https://github.com/winglang/wing/issues/6346
- Removed the ability to specify command specific `.env` files
Basically just moves the loading of environment files to the subcommands. Previously this loading was happening for all commands, which really doesnt make sense since some commands like `lsp`, `docs`, `init` dont need to load those env files. 
Also I several subcommands call the compile subcommand (secrets, test, etc..) so having subcommand specific `.env` files is additional overhead that Im not sure what the usecase it solves is. If needed, its probably just easier to just use a `--env-file` flag …
=> fix(cli)!: .env file not loaded when compiling outside sourceDir

.github/workflows/tf-aws-test.yml, docs/docs/08-guides/02-ci-cd.md
Fixing warning thrown during tests:
```sh
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: azure/login@v1, aws-actions/configure-aws-credentials@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```
=> chore(build): upgrade deprecated github actions

apps/wing/src/commands/run.ts, apps/wing/src/util.before-shutdown.ts, libs/wingsdk/src/target-sim/function.inflight.ts
In my local testing this consistantly fixed my issue with [tsoa](https://github.com/winglang/winglibs/tree/main/tsoa) not killing child processes. I'm not sure which of these changes actually helped.
=> fix: `wing it` does not wait for process to cleanup

libs/wingsdk/src/target-sim/container.inflight.ts
This change uses `waitUntil` after the docker container is up and running to ensure that the `hostPort` is correctly retrieved, as there seems to be a small time window when the container is running but the host port is not specified.
Fixes #6371
=> fix(sdk): container does not listen to port

examples/jsii-fixture/src/index.ts, examples/tests/valid/bring_awscdk.test.w, examples/tests/valid/bring_jsii.test.w, libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/sync.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/jsii_importer.rs, libs/wingc/src/type_check/symbol_env.rs, libs/wingc/turbo.json, libs/wingii/src/fqn.rs, tools/hangar/__snapshots__/test_corpus/valid/bring_awscdk.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/bring_jsii.test.w_compile_tf-aws.md
Fixes #6285
Fixes #5507
JSII allows types to be defined in classes (kinda, moreso that a class can also be a namespace), i.e `assembly.class.interface`. Wing does not support defining or directly referencing types like this. Previously, the JSII importer would  not import these types and also would fail to import any types that come after these types in a given namespace. Some JSII libs, like aws-cdk-lib, make extensive use of these so a lot of types were not available.
Now, the JSII importer supports importing these types and other JSII types that reference them. Wing still cannot directly reference them in type annotations, but there are cases where it is used and type checked (e.g. implicit structs).
In addition, language server completion requests do a better job of eagerly importing …
=> fix: unable to import JSII classes with embedded types

apps/jsii-docgen/src/docgen/view/wing-filters.ts
This change doesn't actually do anything, I just wanted to bust the SDK docgen cache
=> chore: remove regex from docgen filter

libs/wingcompiler/preflight.shim.cjs, libs/wingsdk/src/shared/sandbox.ts
=> fix: can't use `setUncaughtExceptionCaptureCallback` with `domain` module

docs/docs/09-typescript/02-inflights.md
in this example in the TypeScript docs under "Permissions" I get an error unless the keyword "new" is included in front of the  cloud.Function
There was also a typo in the same doc.
```ts
import { main, cloud, lift } from "@wingcloud/framework";
main((root) => {
const bucket = new cloud.Bucket(root, "MyBucket");
new cloud.Function(
root,
"MyFn",
lift({ bucket })
.grant({ bucket: ["get"] })
.inflight(async ({ bucket }) => {
await bucket.put("hello.txt", "Wing!");
//           ^^^ Type error, no `put` permissions!
return "Wing!";
})
);
});
```
=> chore(docs): update typescript example and fix typo

libs/@wingcloud/framework/src/transformer.ts, libs/@wingcloud/framework/test/internal.test.ts, libs/wingsdk/src/core/inflight.ts
When the inflight() function was moved to the SDK, the special auto-import and extra validation provided by the ts framework stopped working. This PR makes the logic for detecting this special function slightly more rigorous by using jsdoc tags instead of relying on detecting the source module.
=> fix: inflight() features in @wingcloud/framework do not work

docs/docs/09-typescript/02-inflights.md
`cloud.Function` is missing the keyword `new`. Added to the code below.
```ts
import { main, cloud, inflight, lift } from "@wingcloud/framework"; 
import assert from "node:assert";
main((root, test) => {
const fn = new cloud.Function(
root,
"MyFn",
inflight(async () => {
return "Wing!";
})
);
test(
// name of the test
"MyFn returns 'Wing!'",
// inflight function to run as the test
lift({ fn }).inflight(async ({ fn }) => {
assert.equal(await fn.invoke(), "Wing!");
})
);
});
```
=> chore(docs): update TypeScript example in the `Testing` section

apps/wing-console/console/server/src/utils/format-wing-error.ts, apps/wing/src/commands/compile.ts, tools/hangar/__snapshots__/invalid.ts.snap
Currently when you get compile errors in the CLI (related to parsing or type checking), the error message appears twice:
```
error: Enum "SomeEnum" does not contain value "FOUR"
--> examples/tests/invalid/enums.test.w:5:21
|
5 | let four = SomeEnum.FOUR;
|                     ^^^^ Enum "SomeEnum" does not contain value "FOUR"
```
The repeated message can make errors look longer and doesn't add any information, so this PR removes the second occurrence of the error message.
=> chore(cli): improve error output

docs/docs/055-platforms/tf-aws.md, libs/wingsdk/src/target-tf-aws/app.ts, libs/wingsdk/test/target-tf-aws/__snapshots__/api.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/function.test.ts.snap, libs/wingsdk/test/target-tf-aws/__snapshots__/redis.test.ts.snap, libs/wingsdk/test/target-tf-aws/function.test.ts, libs/wingsdk/test/target-tf-aws/redis.test.ts, tools/hangar/__snapshots__/test_corpus/valid/redis.test.w_compile_tf-aws.md
Several resources require multi-az support, such as RDS clusters. This PR adds an additional private subnet to the VPC that is created implicitly for users using tf-aws platforms.
=> feat(platforms): `tf-aws` implicit platform now has 2 private subnets

docs/docs/09-typescript/index.md
Without declaring `cloud` in the import, an error is thrown.
```ts
import { main, cloud } from "@wingcloud/framework";
main((root) => {
// your app goes here!
new cloud.Bucket(root, "Bucket");
});
```
=> chore(docs): update TypeScript code + typo

apps/vscode-wing/language-configuration.json
Fixes #6452
No clue how to add a test for this, but here's a video
https://github.com/winglang/wing/assets/1237390/0e772e32-49a2-4a5a-9084-b91f13829472
=> feat(vscode): automatically add `///` to newlines after doc comment

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/example.yml, .github/ISSUE_TEMPLATE/feature.yml, .github/ISSUE_TEMPLATE/incident.yml, .github/workflows/close-stale.yml, .github/workflows/new-pull-request-comment.yml, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, apps/vscode-wing/README.md, apps/wing/README.md, apps/wing/src/analytics/disclaimer.ts, docs/contributing/01-start-here/01-contributing-to-wing.md, docs/contributing/01-start-here/02-help.md, docs/contributing/01-start-here/03-status.md, docs/contributing/01-start-here/07-wingsdk.md, docs/contributing/01-start-here/10-code-of-conduct.md, docs/contributing/02-maintainers/050-operations.md, docs/contributing/03-stories/story-04.md, docs/docs/01-start-here/06-learn-more.md, docs/docs/02-concepts/00-cloud-oriented-programming.md, docs/docs/04-standard-library/cloud/workload.md, docs/docs/08-guides/03-react-vite-websockets.md, docs/docs/08-guides/04-private-api-gateway-aws.md, docs/docs/999-faq/020-supported-clouds-services-and-engines/021-supported-clouds.md, docs/docs/999-faq/020-supported-clouds-services-and-engines/022-supported-services.md, libs/wingsdk/README.md, libs/wingsdk/src/cloud/workload.md
As part of our Discord migration, update docs, workflows and readme files with new Discord links instead of Slack
=> chore(docs): replace slack links with discord

examples/tests/invalid/json.test.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap
fixes #6448
stractural Json object assignment can only be assigned to wing maps or structs (not arrays).
Also fixes the diagnostic hint about using `fromJson` for dynamic json conversion to be shown only for actual dynamic jsons.
=> fix(compiler): compiler allows assigning a json object to a wing array

apps/wing-console/console/app/web/index.css, apps/wing-console/console/design-system/src/resource-icon.tsx, apps/wing-console/console/design-system/src/utils/icon-utils.ts, apps/wing-console/console/server/src/router/app.ts, apps/wing-console/console/ui/src/features/map-view.tsx
Update the display of node names in the MapView component to show the title if available, falling back to the id if not.
Fixes #6457.
=> fix(console): respect `node.title` in the map view

libs/wingsdk/.eslintrc.json, libs/wingsdk/.projenrc.ts, libs/wingsdk/turbo.json
Several parts of the SDK reference try to `require`/`require.resolve` `@winglang/sdk/lib/...` while inflight (e.g. for inflight clients). This directory only exists after the SDK has been compiled. This means the SDK tests depend on SDK itself being compiled first. This is unfortunate because we also compile parts of the SDK with tsc as the tests start up, and then vitest itself is also compiling/transpiling.
This PR is not doing anything to fix all that, but we at least need to ensure turbo is correctly modeling this dependency to avoid false test failures/successes.
As a side fix, I made eslint allow devDeps in test.config.mts to get rid of red squiggles in my IDE. …
=> chore: ensure wingsdk compiles before running tests

libs/wingsdk/src/shared/misc.ts, libs/wingsdk/test/misc.test.ts
The `isPath` utility didn't take into account `../` as an option. Meh!
=> fix(sdk): cannot use relative paths for container images

apps/vscode-wing/syntaxes/wing.tmLanguage.json, examples/tests/invalid/stringify.test.w, examples/tests/valid/stringify.test.w, libs/wingc/src/docs.rs, libs/wingc/src/dtsify/extern_dtsify.rs, libs/wingc/src/lsp/completions.rs, libs/wingc/src/lsp/snapshots/completions/empty.snap, libs/wingc/src/lsp/snapshots/completions/hide_parent_symbols_defined_later.snap, libs/wingc/src/lsp/symbol_locator.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/inference_visitor.rs, libs/wingc/src/visit_types.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/debug_env.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/stringify.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/stringify.test.w_test_sim.md
Adds support for directly logging stringable values without needing to create a interpolated string:
```
let x = 5;
// before
log("{x}");
// now
log(x);
```
To implement the feature, I had to add a new type to the compiler's type system for representing stringable values. At the moment it more or less behaves like `str | num | bool | ...`. For now it's not really something we have concrete plans to expose in userland (to let users write functions with stringable inputs) but it's something we can consider introducing in the future.
=> feat(compiler): support logging stringable values directly

libs/wingc/src/closure_transform.rs, libs/wingc/src/jsify/snapshots/closure_field.snap, libs/wingc/src/jsify/snapshots/lift_inside_preflight_method.snap, tools/hangar/__snapshots__/test_corpus/valid/calling_inflight_variants.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/capture_reassigable_class_field.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/doubler.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/inflight_class_definitions.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/inflight_closure_inside_preflight_closure.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/inflights_calling_inflights.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/mutation_after_class_init.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/symbol_shadow.test.w_compile_tf-aws.md
This is a small code cleanup as part of addressing #4925.
We only generate the `parent_this` variable used in generated closure classes when needed. If the inflight closure never accesses `this` then we don't generated `parent_this`. The code avoids traversing into inner classes inside the closure when searching for `this` accesses, making it a bit cleaner and more efficient.
This relates to #4925 because it solves the problem of accessing `this` (for assignment into `parent_this`) before the `super()` call in a ctor.
=> fix(compiler): closure transform generated `parent_this` even when not used

apps/wing-console/console/ui/src/ui/elk-map-nodes.tsx
Fixes https://github.com/winglang/wing/issues/5964
=> fix(console): wrong behaviour when clicking on a resource icon

libs/wingsdk/src/target-sim/api.ts, libs/wingsdk/src/target-sim/queue.ts, libs/wingsdk/src/target-sim/schedule.ts, libs/wingsdk/src/target-sim/topic.ts
Gives platforms a chance to override the default sim function
=> chore(sdk): use `cloud.Function` instead of `sim.Function`

apps/wing-console/console/ui/src/services/use-map.bridge-connections.test.ts, apps/wing-console/console/ui/src/services/use-map.bridge-connections.ts, apps/wing-console/console/ui/src/services/use-map.ts
This change resolves connections to hidden nodes upwards, meaning that the connection will be listed to its closest visible parent node.
Fixes #6523.
=> fix(console): resolve connections to hidden nodes upwards

docs/docs/01-start-here/02-getting-started.md
=> chore(docs): rename install to getting-started

libs/wingsdk/src/target-sim/api.ts, libs/wingsdk/test/target-sim/__snapshots__/api.test.ts.snap
This change makes `cloud.Api` endpoint functions visible in the Console's map view.
=> feat(sdk): show `cloud.Api` endpoint functions

docs/docs/02-concepts/02-application-tree.md, examples/tests/valid/inflight_closure_as_super_param.test.w, libs/wingc/src/jsify.rs, libs/wingc/src/lifting.rs, libs/wingc/src/lsp/symbol_locator.rs, libs/wingc/src/type_check.rs, libs/wingc/src/visit_context.rs, tools/hangar/__snapshots__/test_corpus/valid/inflight_closure_as_super_param.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/inflight_closure_as_super_param.test.w_test_sim.md
fixes #4925
Now you can pass inflight closures and also any `new PreflightClass()` as parameters to a `super()` call in a ctor.
What I did is detect these cases and made sure the implicit scope passed to the construct ctor is `$scope` and not `this` which isn't available before `super()` is called.
=> fix(compiler): can't pass inflight closure as parameter to `super()` call

libs/wingsdk/src/shared/bundling.ts, libs/wingsdk/src/shared/sandbox.ts, libs/wingsdk/src/target-sim/function.inflight.ts, libs/wingsdk/src/target-sim/resource.inflight.ts, libs/wingsdk/src/target-sim/service.inflight.ts, libs/wingsdk/test/sim-app.ts, libs/wingsdk/test/simulator/simulator.test.ts
Extends the changes made in https://github.com/winglang/wing/pull/6577 for reducing the time it takes for the simulator to update to cloud.Service and sim.Resource.
=> feat(sdk): fewer replacements for cloud.Service and sim.Resource

examples/tests/valid/function_optional_arguments.test.w, libs/wingc/src/fold.rs, tools/hangar/__snapshots__/test_corpus/valid/function_optional_arguments.test.w_compile_tf-aws.md
fixes #6559
The fold mechanism re-generated the IDs used to identify argument lists in the AST. This means that even though we currently detected implicitly optional arguments we lost that information after the closure transform forld operation. I fixed the default fold implementation not to regenerated these IDs, similar to how we preserve expresion IDs during folds, for example.
=> fix(compiler): implicit optional args not working (sometimes) for methods

libs/wingc/package.json, libs/wingc/scripts/postcompile.sh, libs/wingc/turbo.json
The `-O3` level optimization for wingc's wasm is pretty slow but worth keeping in for the final build.
For local dev it's still valuable to run wasm-opt with some optimization as it greatly reduces the size of the wasm file, which then improves performance when JS loads it. The base level optimization runs in like 500ms on my machine so it's not much of a problem.
=> chore: avoid full wasm optimizations in development

libs/wingc/turbo.json
Either I misunderstood the usage of `$TURBO_DEFAULT$` or it just doesn't work 🤷
https://turbo.build/repo/docs/reference/configuration#turbo_default
Regardless, adding specific inputs here isn't hard since there are so few
Fixes #6658
=> chore: remove usage of `$TURBO_DEFAULT$` in turbo.json

docs/docs/01-start-here/05-aws.md
Current links show nothing on GitHub, looks like the labels may have changed?
This PR fixes that and includes the correct GitHub labels so users can see Azure and GCP issues on GitHub.
=> docs(docs): azure and gcp links updated

docs/docs/06-tools/01-cli.md
Watching the [latest wing update](https://youtu.be/30DVoyAuwP0?si=plqoNGSMhEkNM-PA&t=478) it was great to see the new slack template, but from what I understand the docs don't explain or link to the templates.
I know we can see templates using the CLI, but this is just small change to help users find templates in other ways.
=> docs(docs): add link to wing templates

Cargo.lock, apps/wingcli-v2/Cargo.toml, apps/wingcli-v2/package.json, apps/wingcli-v2/src/main.rs, pnpm-lock.yaml
@hasanaburayyan reported an issue running the wingcli-v2 tests locally:
```
running 2 tests
Installing Wing SDK
test test::test_compile_sim ... FAILED
test test::test_compile_tfaws ... FAILED
failures:
---- test::test_compile_sim stdout ----
thread 'test::test_compile_sim' panicked at apps/wingcli-v2/src/main.rs:208:27:
Failed to install SDK: "Failed to install SDK. stdout: . stderr: npm ERR! code EUNSUPPORTEDPROTOCOL\nnpm ERR! Unsupported URL Type \"workspace:\": workspace:^\n\nnpm ERR! A complete log of this run can be found in: /Users/hasan/.npm/_logs/2024-06-12T16_06_47_837Z-debug-0.log\n"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
---- test::test_compile_tfaws stdout ----
thread 'test::test_compile_tfaws' panicked at …
```
=> fix: error running wingcli-v2 tests locally

docs/docs/09-typescript/02-inflights.md
I tried this: 
```ts
import { main, lift } from "@wingcloud/framework";
main((root) => {
const myInflight = inflight(async () => {
return "Wing!";
});
lift({ myInflight }).inflight(async ({ myInflight }) => {
return myInflight();
});
});
``` 
And got this: `Cannot find name 'inflight'`
=> chore: missing import in wing framework docs

apps/wing-console/console/ui/src/features/logs-pane/console-logs.tsx
Improves the Console logs section by separating and graying out the parents of the source of the log, and highlighting the resource name that emitted the log entry.
=> feat(console): improve logs source

libs/wingc/src/dtsify/mod.rs, libs/wingc/src/dtsify/snapshots/declarations.snap
Fixes #6600
Pragmatically, inflight classes can basically work like preflight classes.
This partially exposes an implementation detail, which can be cleaned up in the future to improve DX by removing these dummy classes.
=> fix(compiler): d.ts files missing inflight classes

examples/tests/sdk_tests/resource/no-stop.test.w
That started to fail on: https://github.com/winglang/wing/actions/runs/9534484207, I'll open an issue soon
+ running the full e2e to resolve the snapshots
=> fix: disable `resource/no-stop.test.w` test for non sim targets

.github/workflows/close-stale.yml
Do not check for staleness for issues marked with `roadmap`.
=> chore(repo): skip issues marked `roadmap` from stale checks

examples/tests/invalid/constructs.test.w, examples/tests/sdk_tests/std/array.test.w, examples/tests/valid/casting.test.w, examples/tests/valid/construct-base.test.w, examples/tests/valid/custom_obj_id.test.w, examples/tests/valid/dynamo.test.w, examples/tests/valid/dynamo_awscdk.test.w, examples/tests/valid/external_ts.extern.d.ts, examples/tests/valid/function_variadic_arguments.test.w, examples/tests/valid/resource.test.w, examples/tests/valid/this.test.w, libs/wingc/src/diagnostic.rs, libs/wingc/src/jsify/snapshots/fails_if_referencing_unknown_field.snap, libs/wingc/src/jsify/snapshots/fails_when_referencing_this_from_static.snap, libs/wingc/src/lib.rs, libs/wingc/src/type_check.rs, libs/wingc/src/type_check/symbol_env.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/casting.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/construct-base.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/construct-base.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/custom_obj_id.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/function_variadic_arguments.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/resource.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/this.test.w_compile_tf-aws.md
To avoid confusion between different APIs and different runtime behavior between the `std.Node` and `constructs.Node` types, we avoid exposing `constructs.Node` in the language where possible.
Fixes #5840
BREAKING CHANGE: `.node` is no longer a directly available field on preflight classes and `IConstruct` values. Use the global function `nodeof()` for accessing tree nodes instead.
=> fix(compiler)!: this.node and nodeof(this) have different behaviors

docs/docs/01-start-here/02-getting-started.md
Minor fix to docs. Things have been moved from Slack to Discord. The previous URL was directing to Discord so just changing this to reflect what is happening.
_I see docs are also over on https://github.com/winglang/docsite, which is the source of truth? I assume with the activity this one? Let me know if that's right 👍_
=> docs(docs): community url update

apps/wing-console/console/ui/src/features/hierarchy-pane/use-hierarchy.tsx
This feature was removed by accident 
[here](https://github.com/winglang/wing/pull/6696/files#diff-d0777fb1e9f89a098ae45c58c33cd7b13945106582d1e8c5ed8aef8258b6fa7cL89-L93)
=> feat(console): expand automatically when there is only one node

apps/wing-console/console/ui/src/features/logs-pane/console-logs-filters.tsx
The log levels indicator didn't show "All levels" even when every filter was selected.
=> fix(console): log levels indicator doesn't show "All levels"

docs/docs/03-language-reference.md, examples/tests/invalid/json.test.w, examples/tests/invalid/structs.test.w, examples/tests/valid/json.test.w, examples/tests/valid/structs.test.w, libs/tree-sitter-wing/grammar.js, libs/tree-sitter-wing/src/grammar.json, libs/wingc/src/parser.rs, libs/wingc/src/valid_json_visitor.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/json.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/structs.test.w_compile_tf-aws.md
Fixes #247
Support "punning" in struct and json literals
```wing
struct Bla {
a: num;
b: str;
}
let a = 1;
let b = "bla";
let x = Bla {a, b};
let y: Bla = Json {a,b};
```
=> feat(compiler): punning

examples/tests/sdk_tests/resource/call.test.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/resource/call.test.w_test_sim.md
The test named "resource.call times out if the method takes too long" has been flaking since we merged in https://github.com/winglang/wing/pull/6686. Specifically, it sometimes logs additional errors:
```
Resource is not running (it may have crashed or stopped)
Process exited with code null, signal SIGTERM
node:internal/modules/cjs/loader:1148
throw err;
^
Cannot find module 'D:/a/wing/wing/examples/tests/sdk_tests/resource/target/test/call.test.wsim/.wing/resource_c823d293.sandbox.cjs.bundle/index.cjs'
code: 'MODULE_NOT_FOUND',
requireStack: []
}
Node.js v20.14.0
```
I have a suspicion the test is already broken in some way because even when I try running the test on my local system, the test logs "Resource is not running (it may have crashed or stopped)" instead of an error saying that …
=> chore: disable flakey test on Windows

docs/docs/02-concepts/01-preflight-and-inflight.md
[This page](https://www.winglang.io/docs/concepts/inflights#combining-preflight-and-inflight-code) shows an example of a inflight class.
The example shows an inflight modifier in the class although the class it defined within an inflight closure.
Removing the modifier to clean up the example.
- [] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
=> fix(docs): remove inflight modifier to docs example

docs/docs/04-standard-library/http/api-reference.md, libs/wingc/src/lsp/snapshots/completions/namespace_inflight.snap, libs/wingsdk/src/http/http.ts, libs/wingsdk/test/http/http.test.ts
The CONNECT and TRACE methods were not added to the http module yet, as described in https://github.com/winglang/wing/issues/4818
=> feat(sdk): `http.connect()` and `http.trace()`

docs/docs/04-standard-library/aws/api-reference.md, docs/docs/04-standard-library/cloud/function.md, examples/tests/doc_examples/valid/function.md_example_5/main.w, examples/tests/doc_examples/valid/function.md_example_6/main.w, examples/tests/sdk_tests/function/aws-layer.test.w, libs/awscdk/src/function.ts, libs/wingsdk/src/shared-aws/function.ts, libs/wingsdk/src/target-tf-aws/function.ts, libs/wingsdk/test/target-tf-aws/__snapshots__/tokens.test.ts.snap, tools/hangar/__snapshots__/test_corpus/sdk_tests/function/aws-layer.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/function/aws-layer.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/function/function-ref.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/queue-ref.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/api.test.w_compile_tf-aws.md
=> feat(sdk): aws lambda layers

apps/wing-console/console/ui/src/Console.tsx
Puts any test-related HTTP operations out of the HTTP batch request, freeing all other requests from waiting for test results.
Fixes #6797
=> fix(console): console waits forever until a first successful compilation

docs/docs/01-start-here/02-getting-started.md, docs/docs/06-tools/02-wing-console.md, docs/docs/09-typescript/01-resources.md, docs/docs/09-typescript/index.md
Update to some broken links in the docs and some minor mdx component.
Required for docusuarus v3 migration to work (see https://github.com/winglang/docsite/pull/947).
- [x ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
=> chore(docs): fixed broken links

docs/docs/07-examples/05-optionality.md, docs/docs/07-examples/07-structs.md, examples/tests/doc_examples/valid/05-optionality.md_example_2/main.w, examples/tests/doc_examples/valid/05-optionality.md_example_6/main.w, examples/tests/doc_examples/valid/07-structs.md_example_2/main.w, examples/tests/invalid/nil.test.w, examples/tests/invalid/optionals.test.w, examples/tests/sdk_tests/function/invoke.test.w, examples/tests/sdk_tests/service/callbacks.test.w, examples/tests/sdk_tests/state/get.test.w, examples/tests/valid/nil.test.w, examples/tests/valid/optionals.test.w, examples/tests/valid/statements_if.test.w, libs/tree-sitter-wing/grammar.js, libs/tree-sitter-wing/src/grammar.json, libs/tree-sitter-wing/test/corpus/expressions.txt, libs/tree-sitter-wing/test/corpus/statements/statements.txt, libs/wingc/src/ast.rs, libs/wingc/src/jsify.rs, libs/wingc/src/parser.rs, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/nil.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/optionals.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/statements_if.test.w_compile_tf-aws.md
Closes https://github.com/winglang/wing/issues/5942
BREAKING CHANGE: The optional test syntax, `expr?` has been removed in favor of explicit checking against `nil`. Code can be updated by changing `expr?` to `expr != nil` and `!expr?` to `expr == nil`.
=> feat(compiler)!: remove optional test (x?) operator

apps/wing-console/console/server/src/index.ts, apps/wing-console/console/server/src/utils/simulator.ts
- The console didn't reload the simulator in certain occasions after an error
- The console fully reloads the simulator after a simulation error to avoid getting stuck
Fixes #5426.
=> fix(console): compilation doesn't recover from unresolved token errors

apps/wing/src/cli.ts
looks like oversight from when we moved `awscdk` to be external
=> chore(cli): remove `awscdk` from builtin

apps/wing/src/cli.ts
fixes #6763
Wing CLI currently supports `-V` and `--version`.
This adds the ability to `-v` to get the current version.
=> feat(cli): added -v support in cli to get version 

apps/wing-console/console/ui/src/features/explorer-pane/map-view.tsx, apps/wing-console/console/ui/src/features/hierarchy-pane/use-hierarchy.tsx, apps/wing-console/console/ui/src/features/inspector-pane/resource-panes/resource-metadata.tsx, apps/wing-console/console/ui/src/features/running-state-indicator/running-state-indicator.tsx
This change moves the running state indicator as an attachment of the resource icon for both the explorer and the inspector panels.
=> feat(console): improve running state indicator design

apps/wing-console/console/app/web/index.html, apps/wing-console/console/ui/src/Console.tsx
Prevent the default zoom behavior everywhere in the app.
Since the explorer panel handles the zoom manually, sometimes users may end up zooming the whole app by mistake and end up with the explorer panel covering the whole screen.
This is a big problem since users won't be able to zoom out of it.
=> fix(console): prevent default zoom behavior

apps/wing-console/console/design-system/src/text-highlight.tsx, apps/wing-console/console/ui/src/features/logs-pane/console-logs.tsx
Highlights JSON blobs in the logs section using a low fidelity, regex-based parser.
Fixes #6580.
=> fix(console): highlight json blobs in the logs

apps/wing-console/console/ui/src/features/logs-pane/console-logs.tsx
The commit 2860cad0f6acc523a19f5e66ab871c227382b94b introduced an error where long log lines are visualized with an empty space at the beginning.
=> fix(console): empty space at the start of long log lines

docs/docs/01-start-here/02-getting-started.md, docs/docs/08-guides/03-react-vite-websockets.md
Seems like the old -V got added back in due to docs refactor. This fixes that issue.
=> chore(docs): remove -V from docs and replaced with --version

apps/wing-console/console/server/src/router/app.get-hierarchichal-running-state.ts, apps/wing-console/console/server/src/router/app.ts, apps/wing-console/console/server/src/utils/constructTreeNodeMap.ts, libs/wingsdk/src/simulator/simulator.ts, libs/wingsdk/test/target-sim/api.test.ts, libs/wingsdk/test/target-sim/bucket.test.ts, libs/wingsdk/test/target-sim/function.test.ts, libs/wingsdk/test/target-sim/on-deploy.test.ts, libs/wingsdk/test/target-sim/queue.test.ts, libs/wingsdk/test/target-sim/redis.test.ts, libs/wingsdk/test/target-sim/schedule.test.ts, libs/wingsdk/test/target-sim/secret.test.ts, libs/wingsdk/test/target-sim/service.test.ts, libs/wingsdk/test/target-sim/table.test.ts, libs/wingsdk/test/target-sim/test.test.ts, libs/wingsdk/test/target-sim/topic.test.ts, libs/wingsdk/test/target-sim/website.test.ts
This changeset fixes the running state of constructs that don't have any kind of runtime code.
The Console UI now understands that some resources may not have a running state at all, and the Simulator sets the running state of new resources as `stopped`.
Fixes https://github.com/winglang/wing/issues/6858. Supersedes #6867.
=> fix(console): some resources are marked as started even though they are stopped

.github/workflows/matrix-update.yml, tools/compatibility-matrix-automation/README.md, tools/compatibility-matrix-automation/src/matrix-automation.ts
Fix for the [broken build](https://github.com/winglang/wing/actions/runs/9853241327/job/27205814936).
Includes the new path to the compatibility matrix location in the compatibility matrix tool.
=> chore(docs): compatibility matrix tool now points to correct doc location

apps/wing-console/console/ui/src/features/explorer-pane/map-view.tsx, apps/wing-console/console/ui/src/features/explorer-pane/use-raf-throttle.ts, apps/wing-console/console/ui/src/features/explorer-pane/zoom-pane.tsx
This changeset increases the explorer's threshold used by the "Out of bounds" alert, meaning that it will appear before losing track of the nodes in the explorer. Additionally, the viewport will never leave the rendered area completely, even after resizing the browser window or the panels.
Fixes #4699.
=> fix(console): improve explorer out of bounds experience

examples/tests/valid/namspaced-expr-in-index-expr.test.w, libs/wingc/src/type_check/type_reference_transform.rs, tools/hangar/__snapshots__/test_corpus/valid/namspaced-expr-in-index-expr.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/namspaced-expr-in-index-expr.test.w_test_sim.md
fixes #6661 
The `TypeReferenceTransformer` uses a fold visitor pattern to visit certain `InstanceMember` references and convert them into `TypeReference` if needed.
The other arm stopped the visiting recursion by just returning the node and not a call to the folder- therefore inner references were never visited. It was fixed by calling the fold visitor at all arms of the reference enum.
=> fix(compiler): compiler panic when calling namespaced function within index expression

apps/wing-console/console/app/scripts/dev.mjs
This changeset improves the `dev` script of the console so it closes the console server before shutting everything down.
Related to #5798.
=> chore(console): dev command now handles terminal signals

.github/workflows/sdk-spec-test.yml
=> chore: enabling gcp spec tests to run after release

apps/wing-console/console/ui/package.json, apps/wing-console/console/ui/src/features/blue-screen-of-death/blue-screen-of-death.tsx, apps/wing-console/console/ui/src/features/blue-screen-of-death/turn-ascii-colors-into-html.test.ts, apps/wing-console/console/ui/src/features/blue-screen-of-death/turn-ascii-colors-into-html.ts, apps/wing-console/console/ui/src/features/blue-screen-of-death/use-file-link.tsx, pnpm-lock.yaml
This changeset adds support for ASCII colors, normally used in the terminal, to the Console's Blue Screen Of Death.
Also, enables tests for the `@wingconsole/ui` package and improves the experience of using the cursor to copy the Blue Screen Of Death's error message.
Fixes #6582.
=> fix(console): add support for ascii colors in the blue screen of death

apps/wing-console/console/design-system/src/headless/tree-item.tsx, apps/wing-console/console/design-system/src/inspector-section.tsx, apps/wing-console/console/ui/src/App.tsx, apps/wing-console/console/ui/src/features/explorer-pane/zoom-pane.tsx, apps/wing-console/console/ui/src/features/inspector-pane/resource-panes/resource-metadata.tsx, apps/wing-console/console/ui/src/features/running-state-indicator/running-state-indicator.tsx
Adds smooth transitions for the inspector panel sections.
Also, sets a default transition duration of 1.5s, which is the default `tailwindcss` transition duration.
Lastly, fixes a small type issue inside the `@wingconsole/ui` package.
=> feat(console): animate inspector panel sections when opening and closing

examples/tests/valid/print-helpers.extern.d.ts, examples/tests/valid/print-helpers.js, examples/tests/valid/print.test.w, libs/wingcompiler/src/compile.ts, tools/hangar/__snapshots__/test_corpus/valid/print.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/print.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/valid/resource.test.w_test_sim.md
=> fix: process.stdout regression

libs/wingsdk/src/simulator/lockfile.ts, libs/wingsdk/src/simulator/simulator.ts
In some cases, the lockfile would try to update the lockfile utimes while it was being released due to the async nature of the implementation. This changeset refactors the implementation so it's purely sync.
=> fix(sdk): simulator lockfile race condition during release

apps/wing-console/console/server/src/router/app.ts
Some log messages end with a new line, so the console logs are presented with an expand chevron which does nothing but showing an additional empty line.
Trimming log messages fixes this issue.
=> fix(console): trim log messages

apps/wing-console/console/server/src/utils/simulator.ts, libs/wingsdk/src/simulator/lockfile.ts, libs/wingsdk/src/simulator/simulator.ts
This changeset adds the following behavior to the simulator lockfile:
- If the lockfile gets compromised, it will try to acquire the lock again
- If the lockfile gets compromised, the console will show a blue screen of death with an explanation
Fixes #6949.
=> fix(sdk): improve simulator lockfile implementation

apps/wing-console/console/server/src/utils/compiler.ts, apps/wing-console/console/server/src/utils/format-wing-error.ts, apps/wing/src/commands/compile.ts, libs/wingcompiler/src/compile.test.ts, libs/wingcompiler/src/compile.ts, tools/hangar/src/package-manager.test.ts
The `compile` function from the `@winglang/compiler` package throws even if the compilation was successful (e.g. the compiler emitted a warning). As result of that behavior, the console shows a blue screen of death when the compiler emits a warning.
This changeset refactors `compile` so it doesn't throw anymore, but returns the output directory (if possible) along with the diagnostics and any preflight errors.
=> fix(console)!: not all diagnostics are errors

tools/hangar/src/utils.ts
Resolve an issue currently causing snapshot mismatches on Windows (https://github.com/winglang/wing/actions/runs/10256182184/job/28374831039) that was missed in #6980
=> chore: fix windows snapshot sanitation

libs/wingc/src/docs.rs, libs/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap, libs/wingc/src/lsp/snapshots/completions/namespace_inflight.snap, libs/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap, libs/wingc/src/lsp/snapshots/completions/new_expression_nested.snap, libs/wingc/src/lsp/snapshots/completions/partial_type_reference_annotation.snap, libs/wingc/src/lsp/snapshots/completions/util_static_methods.snap, libs/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap, libs/wingc/src/lsp/snapshots/hovers/class_symbol.snap, libs/wingc/src/lsp/snapshots/hovers/inside_class_field.snap, libs/wingc/src/lsp/snapshots/hovers/static_method_root.snap
For visual brevity, the preview of a class shown by the LSP only shows a subset of the class's API. However, the preview makes it look like class methods have no parameters, even if they do / even if they're required:
This PR fixes that so if a method has arguments, it will be visually indicated by showing "..." in between the parentheses.
=> fix(compiler): lsp preview indicates methods have zero params

examples/tests/invalid/struct_json_conversion.test.w, examples/tests/valid/struct_from_json.test.w, libs/wingc/src/json_schema_generator.rs, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/struct_from_json.test.w_compile_tf-aws.md
Fixes #7004
For now, we're just working with the assumption that Wing enums are just a simple list of constants (if that changes in the future, this code would have to change).
=> fix(compiler): unable to define json structs with enums

examples/tests/valid/super_inflight_class.test.w, libs/wingc/src/jsify.rs, tools/hangar/__snapshots__/test_corpus/valid/inflight_init.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/super_inflight_class.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/super_inflight_class.test.w_test_sim.md
fixes: #6940
Compiled output of the `SuperClass` (slightly different class than the one in the example):
Test results:
=> fix(compiler): using `super()` in an inflight constructor compiles but fails at runtime

examples/tests/invalid/stringify.test.w, examples/tests/valid/stringify.test.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/stringify.test.w_compile_tf-aws.md, tools/hangar/__snapshots__/test_corpus/valid/stringify.test.w_test_sim.md
fixes: #6950
we can now log structs that all of their fields are stringable
=> feat(compiler): `log(struct)`

examples/tests/invalid/stringify.test.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap
Adds a hint so if it looks like the user might want to try concatenating a non-string value onto a string, the error will suggest using string interpolation to coerce the other value into a string.
In the future we should also support directly converting values to strings: https://github.com/winglang/wing/issues/741
=> fix(compiler): improve error diagnostic for invalid string concat

.github/workflows/build.yml, .github/workflows/matrix-update.yml, .github/workflows/mutation.yml, .github/workflows/sdk-spec-test.yml
Previously attempted [here](https://github.com/winglang/wing/pull/5230) and reverted [here](https://github.com/winglang/wing/pull/5257).
=> chore: upgrade github actions to artifacts v4

.github/workflows/sdk-spec-test.yml
Trying to work around a build error related to updating to the latest version of https://github.com/actions/upload-artifact
=> chore: skip artifact upload after cloud tests

docs/api/05-language-reference.md, examples/tests/invalid/class.test.w, examples/tests/invalid/enums.test.w, examples/tests/invalid/interface.test.w, examples/tests/valid/impl_interface.test.w, libs/wingc/src/type_check.rs, tools/hangar/__snapshots__/invalid.ts.snap, tools/hangar/__snapshots__/test_corpus/valid/impl_interface.test.w_compile_tf-aws.md
Closes #7035
Closes #5542
To encourage more readable code and reduce the number of edge cases we might have to handle in the compiler implementation, we add the constraint that that interfaces, enums, and any exported classes have to be defined at the top level. This requirement is already in place for structs.
It's a bit unclear whether we want to apply the same restriction to classes, since classes can have code inside of them (unlike interfaces, enums, and structs) and you can certainly find plenty of examples where folks define anonymous classes inside functions in other languages, so for now we're continue to allow them, though support for it isn't as rigorously tested. We only require that if you define a class in a local context, it must be private, since it wouldn't be possible to …
=> feat(compiler)!: interfaces, enums, and public classes must be defined at the top-level

examples/tests/sdk_tests/util/exec.test.w, libs/wingsdk/src/util/util.ts
=> fix(sdk): unable to use `util.exec` in preflight

apps/wing-console/console/ui/src/Console.tsx
The HTTP batch stream links in TRPC can resolve individually as soon as their responses finished streaming, making the batch stream faster than a normal batch.
=> feat(console): use http batch streams

docs/contributing/999-rfcs/2024-06-26-wing-docs-v2.md
RFC for documentation v2.
[Rendered document](https://github.com/winglang/wing/blob/6b3e25841b4d33328a00968f328cc7c7d9f644d9/docs/contributing/999-rfcs/2024-06-26-wing-docs-v2.md)
=> rfc: wing documentation v2

apps/wing/src/commands/diagnostics.ts, apps/wing/src/commands/generateDocs.test.ts, apps/wing/src/commands/generateDocs.ts, apps/wing/src/commands/pack.test.ts, libs/wingc/src/lib.rs
We noticed an unusual issue where in rare scenarios (depending on the user's file system structure), `wing gen-docs` can hang indefinitely. I believe the cause is related to passing a relative path to the WASI file loader. Using an absolute path as the entrypoint should fix this, though I am not certain.
=> chore: pass resolved path to generateDocs

apps/wing/project-templates/wing/react-vite/backend/main.w, apps/wing/project-templates/wing/react-vite/backend/utils.js
=> fix(cli): use dirname intrinsic in react-vite template

.github/workflows/canary.yml, .github/workflows/sdk-spec-test.yml
Missing changes from https://github.com/winglang/wing/pull/7063
=> chore: fix paths to examples in workflows

packages/@winglang/compatibility-spy/turbo.json, packages/@winglang/compiler/turbo.json, packages/@winglang/platform-awscdk/turbo.json, packages/@winglang/sdk/turbo.json, packages/@winglang/wingtunnels/turbo.json, wing-console/console/app/turbo.json, wing-console/console/design-system/turbo.json, wing-console/console/server/turbo.json, wing-console/console/ui/turbo.json
=> chore: fix references to dist/ folder in turbo.json

.github/workflows/sdk-spec-test.yml
Fixing a build error here: https://github.com/winglang/wing/actions/runs/10690020196/job/29633576179
I believe the issue is caused because we moved the tests from examples/tests/... to tests/... so some of the relative paths are invalidated.
=> chore: fix sdk-spec-test.yml workflow

docs/docs/04-winglibs/02-using-winglibs.md
The correct name of the library is `@winglibs/redis`, not `wing-redis`.
=> chore(docs): fix library name typo

packages/@winglang/wingc/src/lsp/completions.rs, packages/@winglang/wingc/src/lsp/snapshots/completions/hide_abstract_members.snap
=> fix: abstract classes appear are listed under `new ...` autocompletions

docs/api/04-standard-library/cloud/bucket.md, packages/@winglang/platform-awscdk/test/__snapshots__/schedule.test.ts.snap, packages/@winglang/platform-awscdk/test/schedule.test.ts, packages/@winglang/sdk/src/cloud/bucket.md, packages/@winglang/sdk/src/shared-aws/schedule.ts, packages/@winglang/sdk/test/target-tf-aws/__snapshots__/schedule.test.ts.snap, packages/@winglang/sdk/test/target-tf-aws/schedule.test.ts
Fixes #7115 
There was a bug where we were converting days of the week in the wrong way. The Unix cron format expects days of the week to range from 0-6, and AWS expects them to range from 1-7 (https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-scheduled-rule-pattern.html#eb-cron-expressions) so we need to add +1 to any dates that are found.
=> fix(sdk): parameter ScheduleExpression is not valid

packages/@winglang/sdk/src/cloud/bucket.ts, packages/@winglang/sdk/src/target-sim/bucket.inflight.ts, packages/@winglang/sdk/src/target-sim/bucket.ts, packages/@winglang/sdk/test/target-sim/__snapshots__/file-counter.test.ts.snap, packages/@winglang/sdk/test/target-sim/bucket.test.ts, tests/sdk_tests/bucket/signed_url.test.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/cors.test.w_test_sim.md, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/signed_url.test.w_test_sim.md
Fixes #7130
This PR updates the behavior in the simulator so when an unsupported inflight method is used in an app compiled to the simulator, the app will still compile, and an error will simply be thrown at runtime when the method is called.
`signedUrl` was the only method I could find from the `clodu` module that isn't supported in the simulator (?) so it's the only one I had to update.
=> fix(sdk): console stops working when operation is unsupported

packages/@winglang/sdk/src/shared-aws/bucket.inflight.ts, packages/@winglang/sdk/src/shared-azure/bucket.inflight.ts, packages/@winglang/sdk/src/shared-gcp/bucket.inflight.ts, packages/@winglang/sdk/src/target-sim/bucket.inflight.ts, packages/@winglang/sdk/test/shared-aws/bucket.inflight.test.ts, packages/@winglang/sdk/test/shared-azure/bucket.inflight.test.ts, packages/@winglang/sdk/test/target-sim/bucket.test.ts, tests/sdk_tests/bucket/public_url.test.w, tests/sdk_tests/bucket/signed_url.test.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/signed_url.test.w_test_sim.md
Closes #4143 
https://github.com/winglang/wing/pull/7137 added the main code structure for serving files through an express server when `cloud.Bucket` is locally simulated. However, existing code like the `publicUrl` method was still returning URLs to your file system instead of to the HTTP server. This fixes that bug.
Fixing this enables other use cases, for example allowing a web app redirect the URL from the signed URL of a file they uploaded to the actual file (if the bucket is public).
Misc:
- Removed the constraint that `publicUrl` can only return URLs to existing files. I'm not sure this is a necessary requirement - the URL structure is effectively part of the contract of `cloud.Bucket` (for all public clouds), and checking if the key exists only hurts performance when apps are …
=> fix(sdk): local bucket files can't be accessed in simulator

packages/@winglang/wingc/src/lib.rs, packages/@winglang/wingc/src/type_check.rs, tests/valid/subdir/bring_outer.main.w
Fixes a bug where the compiler can panic in certain situations when files from different directories are loaded. Specifically, the issue happens when a Wing file tries importing another Wing file from a directory that is not a sibling or in a sibling directory.
The issue is related to a facility of the compiler responsible for calculating a FQN (fully-qualified name) for every public type. To calculate the FQN for a public type like a class, we need to know where the file is relative to its package. For example, when a file like `/home/node_modules/@winglibs/dynamodb/aws/table.w` is type checked, the compiler needs to know that it belongs to the library named `@winglibs/dynamodb` and that the root of `@winglibs/dynamodb` is `/home/node_modules/@winglibs/dynamodb`. This way, types defined …
=> fix(compiler): unexpected StripPrefixError

docs/api/05-language-reference.md
Related to https://github.com/winglang/wing/issues/4106
Proposal for an extension to Winglang that adds support for type reflection. Examples and an implementation sketch is included.
=> rfc: preflight type reflection

wing-console/console/ui/src/features/inspector-pane/resource-panes/custom-resource-table.tsx
Fix for #7155. Added ability to refresh a table. 
Tests not added, as I can't see any tests for this custom resource componet? Are we missing them? Or maybe someone can direct me? I see we have tests for other resources? Just not the custom ones!?
=> feat(console): added ability to refresh data in table resources

packages/@winglang/wingc/src/docs.rs, packages/@winglang/wingc/src/lib.rs, packages/@winglang/wingc/src/lsp/hover.rs, packages/@winglang/wingc/src/lsp/snapshots/completions/hide_abstract_members.snap, packages/@winglang/wingc/src/lsp/snapshots/completions/hide_parent_symbols_defined_later.snap, packages/@winglang/wingc/src/lsp/snapshots/hovers/parent_class_docs_are_inherited_on_call.snap, packages/@winglang/wingc/src/lsp/snapshots/hovers/parent_class_docs_are_inherited_on_declaration.snap, packages/@winglang/wingc/src/lsp/snapshots/hovers/parent_class_docs_are_inherited_on_method_call.snap, packages/@winglang/wingc/src/lsp/snapshots/hovers/parent_class_docs_are_inherited_on_method_declaration.snap, packages/@winglang/wingc/src/lsp/snapshots/hovers/parent_class_docs_are_overridden.snap, packages/@winglang/wingc/src/lsp/snapshots/hovers/static_method.snap, packages/@winglang/wingc/src/lsp/snapshots/hovers/user_defined_type_annotation.snap, packages/@winglang/wingc/src/lsp/snapshots/hovers/user_defined_type_reference_type.snap, packages/@winglang/wingc/src/lsp/snapshots/hovers/user_defined_types.snap, packages/@winglang/wingc/src/type_check.rs, packages/@winglibs/testfixture/API.md
=> fix(compiler): inherit parent docstring in case no docstring was provided in child member

.github/workflows/sdk-spec-test.yml
Disable continuous cloud testing on Azure until we have more resources to invest in testing and maintaining this cloud provider.
=> chore: disable azure testing in pipeline

docs/by-example/30-reading-writing-files.md, docs/by-example/35-exec-processes.md, tests/doc_examples/valid/30-reading-writing-files.md_example_1/main.w, tests/doc_examples/valid/35-exec-processes.md_example_1/main.w
Some of the examples from our docs don't currently work on Windows, causing them to fail our CI. This PR makes some adjustments to the examples so they should work on both platforms.
One of the issues is a Windows-related bug - I've reopened an issue for tracking it: https://github.com/winglang/wing/issues/6915
=> fix: fs and util.exec examples do not work on windows

docs/api/04-standard-library/std/array.md, packages/@winglang/sdk/src/std/array.ts, tests/sdk_tests/std/array.test.w, tools/hangar/__snapshots__/test_corpus/sdk_tests/std/array.test.w_test_sim.md
Resolves #7139 
This PR adds `clear()` method for `MutArray`.
=> feat(sdk): add clear() method for MutArray

docs/api/04-standard-library/aws/api-reference.md, packages/@winglang/platform-awscdk/src/bucket.ts, packages/@winglang/sdk/src/shared-aws/bucket.ts, packages/@winglang/sdk/src/target-tf-aws/bucket.ts, tests/sdk_tests/bucket/aws-bucket.test.w, tests/sdk_tests/bucket/bucket-ref.test.w
=> feat(sdk): add bucketDomainName to IAwsBucket and BucketRef

packages/@winglang/wingc/CONTRIBUTING.md
=> chore: update discord link

docs/api/04-standard-library/cloud/bucket.md, packages/@winglang/platform-awscdk/src/bucket.ts, packages/@winglang/platform-awscdk/src/website.ts, packages/@winglang/platform-awscdk/test/__snapshots__/bucket.test.ts.snap, packages/@winglang/platform-awscdk/test/bucket.test.ts, packages/@winglang/sdk/src/cloud/bucket.ts, packages/@winglang/sdk/src/target-sim/bucket.ts, packages/@winglang/sdk/src/target-sim/schema-resources.ts, packages/@winglang/sdk/src/target-tf-aws/bucket.ts, packages/@winglang/sdk/src/target-tf-aws/website.ts, packages/@winglang/sdk/src/target-tf-azure/bucket.ts, packages/@winglang/sdk/src/target-tf-gcp/bucket.ts, packages/@winglang/sdk/test/core/__snapshots__/connections.test.ts.snap, packages/@winglang/sdk/test/target-sim/__snapshots__/bucket.test.ts.snap, packages/@winglang/sdk/test/target-sim/__snapshots__/file-counter.test.ts.snap, packages/@winglang/sdk/test/target-sim/bucket.test.ts, packages/@winglang/sdk/test/target-tf-aws/__snapshots__/bucket.test.ts.snap, packages/@winglang/sdk/test/target-tf-aws/bucket.test.ts, packages/@winglang/sdk/test/target-tf-azure/bucket.test.ts, packages/@winglang/sdk/test/target-tf-gcp/__snapshots__/bucket.test.ts.snap, packages/@winglang/sdk/test/target-tf-gcp/__snapshots__/counter.test.ts.snap, packages/@winglang/sdk/test/target-tf-gcp/__snapshots__/function.test.ts.snap, packages/@winglang/sdk/test/target-tf-gcp/__snapshots__/schedule.test.ts.snap, packages/@winglang/sdk/test/target-tf-gcp/bucket.test.ts, packages/@winglang/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap, packages/@winglang/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap, packages/@winglang/wingc/src/lsp/snapshots/completions/partial_type_reference_annotation.snap, packages/@winglang/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap, packages/@winglang/wingc/src/lsp/snapshots/signature/constructor_arg.snap
The forceDestroy property allows to delete a bucket that contains objects
=> feat(sdk): add support for the forceDestroy property on the bucket

docs/contributing/999-rfcs/2022-05-28-winglang-reqs.md, docs/contributing/999-rfcs/2022-06-14-polycons.md, docs/contributing/999-rfcs/2022-08-22-resource-naming.md, docs/contributing/999-rfcs/2023-01-20-wingsdk-spec.md, docs/contributing/999-rfcs/2023-01-21-wing-plugins.md, docs/contributing/999-rfcs/2023-03-08-wing-preview-environment.md, docs/contributing/999-rfcs/2023-04-16-website-resource.md, docs/contributing/999-rfcs/2023-06-12-language-spec.md, docs/contributing/999-rfcs/2023-10-01-workloads.md, docs/contributing/999-rfcs/2024-01-15-console-sign-in.md, docs/contributing/999-rfcs/2024-03-14-explicit-lift-qualification.md, docs/contributing/999-rfcs/2024-03-24-snapshot-tests.md, docs/contributing/999-rfcs/2024-03-31-wing-secrets-cli.md, docs/contributing/999-rfcs/2024-05-07-intrinsics.md, docs/contributing/999-rfcs/2024-06-02-ts-client.md, docs/contributing/999-rfcs/2024-06-26-wing-docs-v2.md, docs/contributing/999-rfcs/2819-stdlib.md, docs/contributing/999-rfcs/overview.md, docs/contributing/999-rfcs/template.md
Attempt to fix #7198, which should remove the RFCs from the search index on the docs site. Need to log into algolia to verify, will give some time for the site to reindex too.
=> chore(docs): removed rfcs from search on docs website

docs/by-example/37-duration.md
Closes #7103, added an example for `duration` with Wing.
=> chore(docs): added duration example to the wing by example docs

docs/docs/01-start-here/02-getting-started.md, docs/docs/01-start-here/_category_.yml
This removes Wing installation instructions from the docs (as we now have a new page). But this PR requires https://github.com/winglang/docsite/pull/1041 to be merged first.
=> chore(docs): removed install instructions from docs

packages/@winglang/platform-awscdk/src/function.ts, packages/@winglang/sdk/LICENSE, packages/vscode-wing/LICENSE, packages/wing-api-checker/LICENSE
The LogFormat used in AWS CDK for Lambda Functions is deprecated, and is being changed to LoggingFormat.
=> fix(sdk): logformat used in awscdk lambda functions is deprecated

packages/winglang/src/commands/test/test.ts
The Pull Request v0.79.13 changed the way the lambdas test ARNs are passed to the TestRunnerClient, unfortunately, it was not noticed that the target awscdk should also be changed. This change allowed the tests to be executed correctly.
Closes #7229
=> fix(sdk): test execution in aws-cdk

packages/vscode-wing/src/lsp.ts
Define `shell: true` in the options used to spawn the language server.
Fixes #7231.
=> fix(vscode): error connecting to lsp in windows

packages/@winglang/sdk/src/target-tf-aws/ecs-cluster.ts
I try to run this test whit the command `wing test --platform tf-aws minimal.test.w`
```w
bring cloud;
let s = new cloud.Service(inflight () => {
log("hello, service!");
return () => {
log("stopping!");
};
});
test "start and stop" {
assert(s.started());
s.stop();
assert(!s.started());
}
```
but I get this error
```shell
$ wing test --platform tf-aws minimal.test.w
✔ Compiling minimal.test.w to tf-aws...
✔ terraform init
✖ terraform apply
Command failed: terraform apply -auto-approve
╷
│ Error: creating ECS Cluster (Test.mfet8zI2Z4_cluster): InvalidParameterException: Cluster name must match ^[a-zA-Z0-9\-_]{1,255}$, but was Test.mfet8zI2Z4_cluster
│
│   with aws_ecs_cluster.Testmfet8zI2Z4_env0_Service_ECSCluster_1D77BD98,
│   on main.tf.json line 116, in …
```
=> fix(sdk): cloud.Service test when using tf-aws target

packages/winglang/src/commands/test/harness/api.ts, packages/winglang/src/commands/test/harness/awscdk.ts, packages/winglang/src/commands/test/harness/terraform.ts, packages/winglang/src/commands/test/test.ts, packages/winglang/src/commands/test/util.ts
Extract common logic across Terraform and AWS CDK targets when running tests. This is an initial step towards allowing custom platforms to provide test running capabilities.
=> chore: test harness interface

packages/@winglang/tree-sitter-wing/turbo.json, packages/@winglang/wingc/turbo.json
The `wingc`'s `lint` task depends on `tree-sitter-wing`'s `build:generate` task, but it wasn't specified in the turbo config. It was working due to the previous build workflow which ran a full build and provided the necessary assets through the cache.
=> fix(repo): test workflow failing due to bad turbo config

packages/@winglang/platform-awscdk/test/service.test.ts
The test was importing from the `src/` directory of one package, and while this works locally, in the CI setup there's no `src/` anymore but `lib/`.
=> fix: faulty test import

.github/workflows/build.yml
Removes the `TURBO_FORCE` environment variables from the CI workflows, which forced a cache miss on turbo, meaning that all tasks were always executed no matter what.
Additionally, restores `windows` as an image for the e2e runner.
=> fix: stop using turbo cache misses
