winglang/wing

docs/02-getting-started/06-simulator.md

Ensure user returns to the root of the project.

chore(docs): simulator guide doc improvement

---

rfcs/story10.md

chore: making story titles consistent

---

examples/tests/invalid/primitives.w
libs/wingc/src/parser.rs
libs/wingc/src/type_check.rs

fix: ensure span is available for type checking nested identifiers

---

docs/04-reference/wingsdk-api.md
libs/wingsdk/API.md
libs/wingsdk/src/cloud/function.ts
libs/wingsdk/src/core/resource.ts

chore(sdk): missing interface declarations

---

rfcs/story10.md

chore: update story10

---

.all-contributorsrc
README.md
docs/04-reference/wingsdk-api.md
libs/wingsdk/API.md
libs/wingsdk/src/cloud/counter.ts
libs/wingsdk/src/target-sim/counter.inflight.ts
libs/wingsdk/src/target-sim/counter.ts
libs/wingsdk/src/target-tf-aws/counter.inflight.ts
libs/wingsdk/src/target-tf-aws/counter.ts
libs/wingsdk/test/target-sim/counter.test.ts
libs/wingsdk/test/target-tf-aws/__snapshots__/counter.test.ts.snap
libs/wingsdk/test/target-tf-aws/counter.inflight.test.ts
tools/hangar/src/__snapshots__/cli.test.ts.snap

The peek method return the current value of counter
Closes #964 

feat(sdk): adding peek method to counter

---

docs/04-reference/wingsdk-api.md
libs/wingsdk/API.md
libs/wingsdk/src/cloud/counter.ts
libs/wingsdk/src/target-tf-aws/counter.ts
libs/wingsdk/test/target-tf-aws/__snapshots__/counter.test.ts.snap
libs/wingsdk/test/target-tf-aws/counter.test.ts

Fixing method peek policy statement

fix(sdk): peek policy statement

---

docs/04-reference/winglang-spec.md

chore(docs): fix typo

---

apps/wing/src/index.ts

chore(cli): update compile help message options

---

.github/workflows/build.yml
libs/wingsdk/test/sandbox/main.ts
tools/hangar/src/cli.test.ts

chore(build): renable e2e with node 19

---

docs/06-contributors/handbook.md

feat(docs): tip about showing stack traces in contribution guide

---

rfcs/story10.md
rfcs/story11.md
rfcs/story4.md
rfcs/story6.md
rfcs/story7.md

chore(repo): add status for stories

---

docs/02-getting-started/01-index.md

fix(docs): we are wingnuts not wingians

---

examples/tests/valid/primitive_methods.w
examples/tests/valid/statements_if.w
libs/tree-sitter-wing/grammar.js
libs/tree-sitter-wing/test/corpus/expressions.txt
tools/hangar/src/__snapshots__/cli.test.ts.snap

fix: ensure nested identifiers have high precedence

---

examples/tests/valid/capture_primitives.w
libs/wingc/src/capture.rs
tools/hangar/src/__snapshots__/cli.test.ts.snap

feat(compiler): adding captures within a binary operator

---

.github/workflows/build.yml

followup to https://github.com/winglang/wing/pull/1168

fix: ensure npm logged in to publish

---

.github/workflows/build.yml

chore: ensure wingsdk is public

---

docs/01-welcome.md

Add distributed computing support to "why you should consider Wing"

feat(docs): Add distributed computing as reason to use wing

---

README.md

Add a getting started and roadmap links in the top of the readme

feat(docs): add a getting started and roadmap links in the top of the readme

---

README.md

fix(docs): readme roadmap link

---

docs/06-contributors/troubleshooting.md

Add troubleshooting page to wing docs contributors section

feat(docs): add troubleshooting page

---

libs/wingsdk/.projen/deps.json
libs/wingsdk/.projen/tasks.json
libs/wingsdk/.projenrc.ts
libs/wingsdk/package-lock.json
libs/wingsdk/package.json
libs/wingsdk/test/target-tf-aws/__snapshots__/bucket.test.ts.snap
libs/wingsdk/test/target-tf-aws/__snapshots__/counter.test.ts.snap
libs/wingsdk/test/target-tf-aws/__snapshots__/function.test.ts.snap
libs/wingsdk/test/target-tf-aws/__snapshots__/queue.test.ts.snap
libs/wingsdk/test/target-tf-aws/__snapshots__/topic.test.ts.snap
libs/wingsdk/test/target-tf-azure/__snapshots__/bucket.test.ts.snap
tools/hangar/src/__snapshots__/cli.test.ts.snap

chore(sdk): upgrade to cdktf 0.15

---

docs/06-contributors/workflows.md

remove $ signs in the copy box
change the repository url
add nx before commands

fix(docs): update development workflows to make easier to follow

---

docs/06-contributors/workflows.md

fix(docs): trigger publishing of workflows

---

apps/wing-language-server/src/main.rs

I considered making this an option instead, but it isn't any more useful than the tree-sitter playground.
Fixes #886

fix(vscode): distracting debug ast on hover

---

examples/README.md

fix(docs): broken contributors handbook link for adding examples

---

docs/06-contributors/handbook.md

fix(docs): broken link in contribution guide

---

docs/06-contributors/workflows.md

fix(docs): workflows

---

.github/workflows/wingsdk-mutation.yml
tools/hangar/src/__snapshots__/cli.test.ts.snap

#1247 was merged prematurely, missing this snapshot update.
Mergify sees the "build" success from the SDK mutation job and attempts to merge, but that was not intentional. So we rename it here.

chore: missing snapshot and fix premature merging

---

CONTRIBUTING.md

fix(docs): broken links in contributing readme

---

docs/04-reference/winglang-spec.md

chore(docs): remove documentation style and sizeof from spec

---

examples/tests/valid/container_types.w
libs/wingc/src/parser.rs
tools/hangar/src/__snapshots__/cli.test.ts.snap

Leftovers from #1262 - support initialization of MutSet too.

fix(compiler): empty mutset initialization

---

docs/01-welcome.md

In addition to a change in our docs site repo, updated our root html file with the relevant open graph metadata.
Preview in now available in facebook, twitter, discord and linkedin

fix(docs): open graph preview

---

docs/01-welcome.md

fix(docs): welcome doc title

---

apps/wing/src/index.ts

trying to resolve https://github.com/winglang/wing/issues/635

fix(cli): remove wing upgrade command

---

docs/04-reference/wingsdk-spec.md

Following a discussion with @ekeren and @Chriscbr - updated the priorities for the resources we are going to build first.
The source of truth is the [SDK Roadmap](https://github.com/orgs/winglang/projects/3).

docs: updated priorities for sdk resources roadmap

---

examples/tests/invalid/for_loop.w
examples/tests/valid/for_loop.w
libs/wingc/src/type_check.rs
tools/hangar/src/__snapshots__/cli.test.ts.snap

feat(compiler): allow `for ... in ...` for primitive collection

---

examples/tests/valid/captures.w
libs/wingc/src/type_check/jsii_importer.rs
tools/hangar/src/__snapshots__/cli.test.ts.snap

fix(compiler): jsii fails to import primitive collections

---

apps/wing/src/commands/run.test.ts
apps/wing/src/commands/run.ts

fix: unable to `wing run` a file in a different directory

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

chore: add plugin, cli components to feature template

---

apps/wing-playground/imports.d.ts
apps/wing-playground/package-lock.json
apps/wing-playground/package.json
libs/wingsdk/project.json
package-lock.json
package.json

More attempts at https://github.com/winglang/wing/issues/1479
- Started by updating some packages, probably not helpful but hey why not.
- Added a .d.ts file for using the fancy bundler imports in wing-playground. Definitely not helping solve the problem, but improves DX in the playground.
- It took a while, but I eventually realized the errors associated with https://github.com/winglang/wing/issues/1479 actually make it seem like wingsdk is failing to build properly (but not outputting anything about it??). So the main change here is running pre-compile when building wingsdk. Note: did not add post-compile because it takes so dang long for docgen to run.
Again I will mention the error is not happening locally, so forgive me for throwing so much at the wall 🙇 
By submitting this pull …

chore: update packages and make sure sdk runs pre-compile patche in build

---

examples/tests/invalid/cloud_function_expects_inflight.w
libs/wingc/src/ast.rs

fix(compiler): errors do not show inflight in type name

---

docs/06-contributors/999-rfcs/000-stories/story-13.md

rfc: fix story 13 adding tasklist instance

---

libs/wingc/src/ast.rs
libs/wingc/src/jsify.rs
libs/wingc/src/lib.rs
libs/wingc/src/parser.rs
libs/wingc/src/type_check.rs
libs/wingc/src/type_check/jsii_importer.rs
tools/hangar/src/__snapshots__/invalid.test.ts.snap

fix(compiler): errors do not show inflight in type name (attempt 2)

---

examples/tests/valid/resource.w
libs/wingc/src/type_check/symbol_env.rs
tools/hangar/src/__snapshots__/compile.test.ts.snap
tools/hangar/src/__snapshots__/test.test.ts.snap

Adapted reosurce.w test to verify #1432.

chore: test user defined resources

---

libs/wingc/src/jsify.rs
tools/hangar/src/__snapshots__/compile.test.ts.snap
tools/hangar/src/utils.ts

fixing forward instead of reverting https://github.com/winglang/wing/pull/1528

fix: invalid inflight client for custom resources on windows

---

libs/wingc/src/lib.rs

fix: compiling with invalid file causes panic

---

docs/04-reference/winglang-spec.md

chore(docs): spec typo fix

---

examples/tests/invalid/unknown_symbol.w
libs/wingc/src/capture.rs
tools/hangar/src/__snapshots__/invalid.test.ts.snap

fix(compiler): unhandled panic with unknown symbol inside resource

---

libs/wingc/src/type_check.rs

Cloning usually introduces additional memory allocations (i.e. performance costs), and it doesn't seem to be necessary here.

chore: remove unnecessary clones

---

docs/06-contributors/999-rfcs/000-stories/story-14.md

chore(docs): update story name and date

---

apps/vscode-wing/project.json
apps/vscode-wing/syntaxes/wing.tmLanguage.json
apps/wing/src/wingc.ts
examples/tests/valid/bring_jsii_path.w
libs/wingc/src/ast.rs
libs/wingc/src/type_check.rs
libs/wingii/src/node_resolve.rs
libs/wingii/src/util.rs
tools/hangar/src/__snapshots__/compile.test.ts.snap
tools/hangar/src/__snapshots__/invalid.test.ts.snap
tools/hangar/src/__snapshots__/test.test.ts.snap

Kinda a mishmash, was working on the language server this came out of it
Fixes #1549
Fixes #1530
Fixes #1488

fix: unable to load jsii modules in vscode, missing highlights, and verbose diagnostics for certain types

---

libs/wingc/src/lib.rs
tools/hangar/src/__snapshots__/invalid.test.ts.snap

fix: links in console blue screen of death not working

---

tools/hangar/vitest.config.ts

chore(repo): reduce e2e test timeouts on windows

---

README.md
apps/vscode-wing/README.md
docs/02-getting-started/07-summary.md
docs/06-contributors/999-rfcs/000-stories/story-04.md
docs/06-contributors/999-rfcs/overview.md
examples/README.md

Fixing broken links
Another pull request will be submitted for making broken links an error instead of warning in the docsite repo

fix(docs): broken links

---

docs/02-getting-started/02-installation.md

chore(docs): add console windows support

---

libs/wingsdk/src/testing/index.ts
libs/wingsdk/src/testing/simulator.ts
libs/wingsdk/src/testing/tree.ts
libs/wingsdk/test/testing/__snapshots__/simulator.test.ts.snap
libs/wingsdk/test/testing/reload.test.ts
libs/wingsdk/test/testing/simulator.test.ts

feat(sdk): expose tree in simulator api

---

libs/wingsdk/src/testing/simulator.ts
libs/wingsdk/src/testing/tree.ts
libs/wingsdk/test/testing/__snapshots__/simulator.test.ts.snap

#1606 auto-merged before I could update these fixes. Investigating in #1608...

chore(sdk): fix missing docstrings

---

libs/wingsdk/project.json

Should fix #1608
Depends on #1607

fix(repo): pr merges even if self mutation fails

---

.github/workflows/build.yml

Regression from https://github.com/winglang/wing/pull/1601

chore: fix broken publish workflow

---

.mergify.yml

The main build name was recently changed, forgot to change it here

chore: mergify merge queue condition typo

---

docs/04-reference/wingcli.md

chore(docs): rename to cli user manual

---

libs/wingc/src/ast.rs
libs/wingc/src/parser.rs
libs/wingc/src/type_check.rs
tools/hangar/src/__snapshots__/compile.test.ts.snap

Recent built error: https://github.com/winglang/wing/actions/runs/4246558064/jobs/7383702993 I think this should prevent it from happening again

fix(compiler): nondeterministic js output

---

libs/wingc/src/type_check.rs
libs/wingc/src/type_check/jsii_importer.rs
libs/wingc/src/type_check/symbol_env.rs

chore: remove hidden namespace logic

---

.gitattributes
tools/hangar/vitest.config.ts

chore: stop gitattributes from treating everything as text and increase test timeout

---

docs/04-reference/wingsdk-api.md
libs/wingc/src/capture.rs
libs/wingc/src/jsify.rs
libs/wingsdk/API.md
libs/wingsdk/src/core/inflight.ts
libs/wingsdk/src/core/internal.ts
libs/wingsdk/src/testing/testing.ts
libs/wingsdk/test/target-sim/file-counter.test.ts
libs/wingsdk/test/target-sim/immutable-capture.test.ts
libs/wingsdk/test/target-sim/queue-consumer.test.ts
libs/wingsdk/test/target-sim/topic-producer.test.ts
libs/wingsdk/test/target-tf-aws/captures.test.ts
libs/wingsdk/test/target-tf-aws/counter.test.ts
libs/wingsdk/test/target-tf-azure/captures.test.ts
libs/wingsdk/test/testing/simulator.test.ts
tools/hangar/src/__snapshots__/compile.test.ts.snap

chore: simplify binding model in wingc/sdk

---

libs/wingc/src/type_check/jsii_importer.rs
libs/wingc/src/visit.rs
libs/wingii/src/lib.rs

See https://github.com/winglang/wing/pull/1684#discussion_r1121276429

chore(compiler): dedup interface collection code

---

.github/workflows/pull-request-lint.yml

Add "revert" as a valid commit message type

chore: update pull request linter

---

apps/wing/src/commands/compile.ts
tools/hangar/src/__snapshots__/test.test.ts.snap
tools/hangar/src/package.setup.ts

feat: support wingc output colors in wing cli

---

docs/04-reference/wingsdk-api.md
examples/tests/valid/json_bucket.w
libs/wingc/src/type_check.rs
libs/wingsdk/API.md
libs/wingsdk/src/cloud/bucket.ts
libs/wingsdk/src/target-sim/bucket.inflight.ts
libs/wingsdk/src/target-sim/bucket.ts
libs/wingsdk/src/target-tf-aws/bucket.inflight.ts
libs/wingsdk/src/target-tf-aws/bucket.ts
libs/wingsdk/src/target-tf-azure/bucket.inflight.ts
libs/wingsdk/src/target-tf-azure/bucket.ts
libs/wingsdk/test/target-sim/__snapshots__/bucket.test.ts.snap
libs/wingsdk/test/target-sim/bucket.test.ts
libs/wingsdk/test/target-tf-aws/bucket.inflight.test.ts
libs/wingsdk/test/target-tf-azure/bucket.inflight.test.ts
tools/hangar/src/__snapshots__/compile.test.ts.snap
tools/hangar/src/__snapshots__/invalid.test.ts.snap
tools/hangar/src/__snapshots__/test.test.ts.snap

Adds the `get_json` and `put_json` api to `cloud.Bucket`
Closes: https://github.com/winglang/wing/issues/1497
Screenshot:

feat(sdk): support bucket put json

---

libs/wingsdk/src/core/inflight.ts
libs/wingsdk/src/target-tf-aws/bucket.ts
libs/wingsdk/src/target-tf-aws/counter.ts
libs/wingsdk/src/target-tf-aws/function.ts
libs/wingsdk/src/target-tf-aws/logger.ts
libs/wingsdk/src/target-tf-aws/queue.ts
libs/wingsdk/src/target-tf-aws/schedule.ts
libs/wingsdk/src/target-tf-aws/topic.ts
libs/wingsdk/src/target-tf-azure/bucket.ts
libs/wingsdk/src/target-tf-azure/logger.ts
libs/wingsdk/src/target-tf-gcp/logger.ts
libs/wingsdk/test/target-tf-aws/__snapshots__/captures.test.ts.snap
libs/wingsdk/test/target-tf-aws/__snapshots__/counter.test.ts.snap
libs/wingsdk/test/target-tf-aws/__snapshots__/queue.test.ts.snap
libs/wingsdk/test/target-tf-azure/__snapshots__/captures.test.ts.snap

Small refactoring. May address #248 (needs testing)

chore(sdk): remove use of require.resolve

---

tools/hangar/package-lock.json
tools/hangar/package.json
tools/hangar/src/test.test.ts

@MarkMcCulloh please take a look and either approve or explain why not. Until then marking as `do-not-merge`.

chore: safely assume snapshot tests don't produce colored output (see #1723)

---

docs/06-contributors/030-pull-requests.md

chore: update contributing guide

---

docs/06-contributors/040-wingsdk.md

fix(docs): update wingsdk individual test document

---

docs/04-reference/wingsdk-api.md

For some reason, the author of the API SDK failed to include generated docs.

chore(docs): update generated api documents

---

docs/06-contributors/999-rfcs/000-stories/story-13.md

Updated story 13 to comply with the json API as appears in the language spec and in #1768
Please note - this story would still fail due to: #1762 

chore(docs): update story 13 to fit json api

---

.github/workflows/build.yml

https://github.com/nodejs/node/issues/47096
Causing build issue https://github.com/winglang/wing/actions/runs/4424274597/jobs/7758146053

chore: pin node19 in e2e tests to avoid regression

---

examples/proposed/replayable-queue.w

inspired by @Chriscbr , I've added `a curious reader` section

chore(examples): added curious reader section

---

docs/04-reference/winglang-spec.md
docs/04-reference/wingsdk-api.md
docs/06-contributors/999-rfcs/000-stories/story-15.md
examples/tests/valid/json_static.w
libs/wingsdk/API.md
libs/wingsdk/src/std/json.ts

Renamed as mentioned: https://github.com/winglang/wing/issues/1839

feat!: rename json static method to_str to stringify

---

docs/04-reference/winglang-spec.md

feat(docs): extern type model in spec

---

examples/tests/invalid/struct_expansion.w
examples/tests/valid/api.w
libs/wingc/src/ast.rs
libs/wingc/src/capture.rs
libs/wingc/src/jsify.rs
libs/wingc/src/parser.rs
libs/wingc/src/type_check.rs
libs/wingc/src/visit.rs
tools/hangar/__snapshots__/invalid.ts.snap
tools/hangar/__snapshots__/test_corpus/valid/api.w.ts.snap

fix(compiler): panics when struct fields are omitted

---

apps/vscode-wing/syntaxes/wing.tmLanguage.json
apps/wing/src/commands/lsp.ts
apps/wing/src/wingc.ts
libs/wingc/src/lsp/goto_definition.rs
libs/wingc/src/lsp/mod.rs

quick little nugget feature, was tired of switching tabs myself
https://user-images.githubusercontent.com/1237390/226689570-5aa9fe4f-2204-4a7a-9043-f5e669ac7eac.mp4

feat(vscode): goto extern file

---

examples/tests/valid/symbol_shadow.w
libs/wingc/src/type_check/symbol_env.rs
tools/hangar/__snapshots__/test_corpus/valid/symbol_shadow.w.ts.snap

Removed the code that prevented symbol shadowing, added test
(This is my first time rust PR, but you'll noticed I managed to not write a single rust line. )

fix(compiler): cant shadow symbols

---

.github/workflows/build.yml

chore: unclosed string typo in workflow

---

docs/06-contributors/999-rfcs/000-stories/story-14b.md

chore(docs): wrong story 14 description

---

docs/06-contributors/999-rfcs/000-stories/story-15.md

chore(docs): update story-15.md

---

docs/06-contributors/999-rfcs/000-stories/story-04.md
docs/06-contributors/999-rfcs/000-stories/story-10.md
docs/06-contributors/999-rfcs/000-stories/story-12a.md
docs/06-contributors/999-rfcs/000-stories/story-13.md

chore(docs): replacing print with logs on user stories

---

docs/04-reference/wingsdk-spec.md

chore(docs): camel case in sdk spec

---

.github/ISSUE_TEMPLATE/bug.yml

This section should help us understand the severity of issues reported. It also helps sharing knowledge of common workarounds for known issues.

chore(docs): workaround section in bug template

---

docs/02-getting-started/02-installation.md
docs/02-getting-started/04-console.md
docs/02-getting-started/05-aws.md

chore: fix docs

---

docs/06-contributors/999-rfcs/000-stories/story-15.md

Currently story 15 has these known issues to deal with before we can test it on the Wing Console:

chore(docs): story 15 workarounds for several issues

---

libs/wingc/src/ast.rs
libs/wingc/src/capture.rs
libs/wingc/src/jsify.rs
libs/wingc/src/parser.rs
libs/wingc/src/type_check.rs
libs/wingc/src/visit.rs

Another small AST simplification

chore(compiler): refactor optional test as unary operator

---

libs/wingsdk/src/shared-aws/bucket.inflight.ts
libs/wingsdk/test/shared-aws/bucket.inflight.test.ts

chore(sdk): upgrade s3 client list objects command to v2

---

docs/06-contributors/020-development.md
docs/06-contributors/090-troubleshooting.md

Based on this [slack thread](https://winglang.slack.com/archives/C04BBDQUWQP/p1680605002789779) by @fynnfluegge.

feat(docs): recommend `rustup`

---

libs/wingsdk/src/shared-aws/permissions.ts
libs/wingsdk/src/target-awscdk/app.ts
libs/wingsdk/src/target-awscdk/counter.ts
libs/wingsdk/src/target-awscdk/index.ts
libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap
libs/wingsdk/test/target-awscdk/counter.test.ts

feat(sdk): adding counter to awscdk target

---

libs/wingsdk/src/shared-aws/permissions.ts
libs/wingsdk/src/target-awscdk/app.ts
libs/wingsdk/src/target-awscdk/function.ts
libs/wingsdk/src/target-awscdk/topic.ts
libs/wingsdk/src/target-tf-aws/topic.ts
libs/wingsdk/test/target-awscdk/__snapshots__/topic.test.ts.snap
libs/wingsdk/test/target-awscdk/topic.test.ts

feat(sdk): adding topic to awscdk target

---

Cargo.lock
libs/wingii/Cargo.toml
libs/wingii/src/lib.rs
libs/wingii/src/test.rs

fix(compiler): unable to bring compressed jsii manifests

---

README.md

fix(docs): broken link in readme

---

docs/07-faq/020-supported-clouds.md
docs/07-faq/022-supported-provisioning-engines.md

chore(docs): fix faq headings

---

docs/04-reference/wingsdk-spec.md
docs/07-faq/020-supported-clouds.md
docs/07-faq/022-supported-provisioning-engines.md
docs/07-faq/030-who-is-behind-wing.md

Updating the sdk spec with links to the github issue for each sdk resource.
Also in this PR - a few typos in the docs/faq section

chore(docs): sdk spec - links to github issues added

---

apps/wing/package-lock.json
apps/wing/package.json
apps/wing/src/commands/compile.test.ts
apps/wing/src/commands/compile.ts
apps/wing/src/commands/docs.test.ts
apps/wing/src/commands/docs.ts
apps/wing/src/commands/run.test.ts
apps/wing/src/commands/run.ts
apps/wing/src/wingc.ts
apps/wing/vitest.config.ts

Reverts winglang/wing#2083
We had to revert because this created a p0 #2086

fix: revert 2083: fix: unable to resolve extern depending on cwd

---

apps/wing-playground/package-lock.json
examples/tests/valid/api.w
libs/wingc/src/type_check/jsii_importer.rs
tools/hangar/__snapshots__/test_corpus/api.w/compile/tf-aws/clients/Foo.inflight.js
tools/hangar/__snapshots__/test_corpus/api.w/compile/tf-aws/preflight.js

fix(compiler): wing thinks `api.url` is reassignable

---

.github/ISSUE_TEMPLATE/bug.yml

chore(build): update bug template - fix bug label

---

.github/workflows/build.yml

Why do you hurt me in this way, YAML?

chore: typo in github action

---

apps/wing/package.json
docs/04-reference/wingsdk-api.md
libs/wingsdk/src/cloud/api.ts
libs/wingsdk/src/target-sim/api.ts
libs/wingsdk/src/target-tf-aws/api.ts
libs/wingsdk/test/target-sim/__snapshots__/api.test.ts.snap

fixes: https://github.com/winglang/wing/issues/2132
+ fixes never ending build- the tests were on watch mode until now, so they would never be done if there were any failed tests.

fix(sdk): internal route validation

---

apps/wing/package.json
docs/04-reference/wingsdk-api.md
examples/tests/valid/inflight-subscribers.w
libs/wingsdk/API.md
libs/wingsdk/src/cloud/topic.ts
libs/wingsdk/test/target-tf-aws/topic.test.ts
tools/hangar/__snapshots__/test_corpus/inflight-subscribers.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/inflight-subscribers.w_test_sim.md

extend function props on topicOnMessage interface (just like we do for queueAddConsumer) 
Closes: https://github.com/winglang/wing/issues/2218

fix(sdk): topic on message allows function props

---

.github/workflows/wingsdk-mutation.yml

Use `git add --all` otherwise changes in folders outside the working directory (like `docs`) are not picked up.

fix(repo): not all changes picked up by mutation job

---

docs/02-getting-started/06-simulator.md

Add a recommendation that users clean up the SDK to prevent future errors like #2280

fix(docs): add cleanup to getting started guide

---

docs/04-reference/wingsdk-api.md
libs/wingsdk/API.md
libs/wingsdk/src/cloud/table.ts
libs/wingsdk/src/shared-aws/table.inflight.ts
libs/wingsdk/src/target-sim/table.inflight.ts
libs/wingsdk/test/shared-aws/table.inflight.test.ts

Change the return of table.get from `any` to `Json`

fix(sdk): now table.get returns json

---

examples/tests/valid/bring_awscdk.w
examples/tests/valid/package-lock.json
examples/tests/valid/package.json
libs/wingc/src/jsify.rs
tools/hangar/__snapshots__/test_corpus/bring_awscdk.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/bring_awscdk.w_test_sim.md

fix(compiler): use camel case jsification of static methods from constructs

---

tools/hangar/project.json

chore: unable to run benchmarks through nx

---

README.md

fix(docs): improve readme "why a language"

---

.github/workflows/build.yml

*shakes fist at yaml syntax quirks"

chore: yaml typo in build workflow

---

apps/vscode-wing/src/extension.ts

Added a status bar icon for the wing version

fix: difficult to know which version is being used in vscode lsp

---

examples/tests/invalid/bring.w
libs/wingc/src/type_check.rs
tools/hangar/__snapshots__/invalid.ts.snap

fixes #1624
tbh I was just tired of seeing this issue at the top of the P1 list

fix(compiler): duplicate import causes panic

---

docs/07-faq/004-what-pains-wing-solves.md
docs/07-faq/010-good-fit.md
docs/07-faq/012-can-we-abstract-the-cloud.md
docs/07-faq/020-supported-clouds-services-and-engines/021-supported-clouds.md
docs/07-faq/020-supported-clouds-services-and-engines/022-supported-services.md
docs/07-faq/020-supported-clouds-services-and-engines/023-supported-provisioning-engines.md
docs/07-faq/020-supported-clouds-services-and-engines/_category_.yml
docs/07-faq/040-differences-from-other-solutions/047-difference-from-darklang.md
docs/07-faq/040-differences-from-other-solutions/_category_.yml
docs/07-faq/071-state-handling.md
docs/07-faq/093-secrets.md

Better file structure and namings

chore(docs): re-org faq

---

docs/04-reference/winglang-spec.md

*bangs my head on the keyboard*
fixes the changes as reviewed by @ShaiBer in #2416

chore(docs): revert some doc changes to the previous version

---

README.md
docs/07-faq/004-what-pains-wing-solves.md

chore(docs): add pains we solve to the readme + some benefits

---

docs/04-reference/compatibility/compatibility.json
libs/wingsdk/src/target-tf-aws/website.ts

I also opened a bug for not abling to connect CloudFront with a domain

chore(docs): adding website to matrix

---

libs/wingsdk/src/target-sim/topic.inflight.ts

chore(sdk): remove extra void

---

.github/workflows/pull-request-lint.yml

Because now we use camelCase...

chore: update pull request linter to allow upper case

---

docs/02-getting-started/02-installation.md
docs/02-getting-started/05-aws.md

chore(docs): moving prerequisites

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml
.github/workflows/pull-request-lint.yml
docs/06-contributors/030-pull-requests.md

chore(repo): add tutorial as an option to select in issue opening

---

apps/jsii-docgen/src/docgen/transpile/wing.ts
apps/jsii-docgen/test/docgen/view/__snapshots__/class.test.ts.snap
apps/jsii-docgen/test/docgen/view/__snapshots__/documentation.test.ts.snap
apps/jsii-docgen/test/docgen/view/__snapshots__/interface.test.ts.snap
apps/jsii-docgen/test/docgen/view/__snapshots__/markdown.test.ts.snap
apps/jsii-docgen/test/docgen/view/__snapshots__/parameter.test.ts.snap
apps/jsii-docgen/test/docgen/view/__snapshots__/property.test.ts.snap
apps/jsii-docgen/test/docgen/view/__snapshots__/static-function.test.ts.snap
apps/jsii-docgen/test/docgen/view/__snapshots__/struct.test.ts.snap
docs/04-reference/wingsdk-api.md
libs/wingsdk/API.md

Followup for #2468
Removed snake_case conversion in jsii-docgen

fix(docs): snake case removed from reference docs

---

libs/wingsdk/src/core/app.ts

chore(compiler): change error to indicate npm install -g is required

---

docs/04-resources/bucket.md
docs/04-resources/secret.md
libs/wingsdk/src/cloud/bucket.md
libs/wingsdk/src/cloud/secret.md

feat: cloud.Bucket readme docs

---

libs/wingsdk/src/shared/bundling.ts
libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap
libs/wingsdk/test/target-awscdk/__snapshots__/queue.test.ts.snap
libs/wingsdk/test/target-awscdk/__snapshots__/topic.test.ts.snap

Reverts winglang/wing#2687
Because of #2698

Revert "fix: build process cwd is wrong in the console"

---

docs/05-reference/wingsdk-spec.md

chore(docs): queue single consumer

---

examples/tests/invalid/optionals.w
examples/tests/valid/optionals.w
libs/wingc/src/type_check.rs
tools/hangar/__snapshots__/invalid.ts.snap
tools/hangar/__snapshots__/test_corpus/optionals.w_compile_tf-aws.md

Support option channing
Closes: https://github.com/winglang/wing/issues/436

feat(compiler): support optional chaining

---

docs/06-contributors/999-rfcs/2022-05-28-winglang-reqs.md

removed the broken link to https://github.com/winglang/wing/blob/main/docs/04-reference/winglang-spec.md)

fix(docs): fix broken link on 2022-05-28-winglang-reqs.md

---

libs/wingsdk/test/target-sim/file-counter.test.ts

Adds a delay between pushes.
Fixes #2716

chore: fix flakey test`file-counter.test.ts`

---

.github/workflows/build.yml

revert(build): skip publishing vscode extension if no changes

---

examples/tests/invalid/interface.w
libs/wingc/src/parser.rs
libs/wingc/src/type_check.rs
tools/hangar/__snapshots__/invalid.ts.snap

fix(compiler): panic when adding field to interface

---

docs/05-reference/compatibility/compatibility.json

Adding missing and recently implemented methods for bucket.

chore(docs): updating compatibility matrix

---

docs/05-reference/winglang-spec.md

Fixing docs as discussed in #2791.

fix(docs): fixing winglang spec

---

tools/hangar/src/utils.ts

fix: e2e test snapshots fail on windows

---

docs/06-contributors/99-maintainers/050-operations.md

Removed https://github.com/winglang/playground
(we have a link to https://play.winglang.io/)

chore(docs): update 050-operations.md

---

docs/06-contributors/999-rfcs/000-stories/story-04.md

https://github.com/monadahq/rfcs/blob/main/0044-winglang-requirements.md	 Replaced the above broken link with https://docs.winglang.io/contributors/rfcs/2022-05-28-winglang-reqs

chore(docs): update story-04.md

---

docs/03-concepts/02-inflight.md

Updated the broken link https://functionless.org/ with https://github.com/functionless/functionless

chore(docs): update 02-inflight.md

---

docs/07-faq/005-why-a-language.md

Updated broken link to https://github.com/functionless/functionless

chore(docs): update 005-why-a-language.md

---

libs/wingc/src/lsp/completions.rs
libs/wingc/src/lsp/snapshots/completions/undeclared_var.snap

fix(vscode): completions are shown for nonexistant variables/types

---

libs/wingcompiler/project.json

followup to https://github.com/winglang/wing/pull/2762

chore: fix race condition in workflow

---

examples/proposed/replayable-queue.w

Fixed replayableQueue example syntax 
- [z] Description explains motivation and solution

fix(docs): replyable queue

---

docs/05-reference/wingsdk-api.md
examples/tests/valid/json_static.w
libs/wingsdk/API.md
libs/wingsdk/src/std/json.ts
tools/hangar/__snapshots__/test_corpus/valid/json_static.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/json_static.w_test_sim.md

Static method that checks if the json object given has the given key.
closes #2373 

feat(sdk): has static method for json

---

examples/tests/valid/optionals.w
libs/wingsdk/src/std/resource.ts
tools/hangar/__snapshots__/test_corpus/valid/optionals.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/optionals.w_test_sim.md

Closes: https://github.com/winglang/wing/issues/2796

fix(sdk): no-op registering bind on undefined objects

---

libs/wingc/src/lsp/completions.rs
libs/wingc/src/lsp/snapshots/completions/util_static_methods.snap

fix(vscode): util completions

---

examples/tests/sdk_tests/util/sleep.w
tools/hangar/__snapshots__/test_corpus/sdk_tests/util/sleep.w_compile_tf-aws.md

verify that sleep work without guarantee precision

fix(sdk): std.utils.sleep() test

---

apps/vscode-wing/syntaxes/wing.tmLanguage.json

fix(vscode): resource keyword is obsolete

---

.github/workflows/build.yml

chore: wrong path to wing console tarballs

---

docs/999-contributors/999-rfcs/2819-stdlib.md

chore(docs): fix heading levels

---

CONTRIBUTING.md
docs/contributing/01-start-here/01-contributing-to-wing.md
docs/docs/02-concepts/03-compile-targets.md
docs/docs/03-language-guide/80-equality.md

chore(docs): fixing broken links in docs

---

tools/hangar/src/cli.bench.ts
tools/hangar/src/generated_test_targets.ts
tools/hangar/src/plugins.test.ts
tools/hangar/src/tree_json.test.ts
tools/hangar/src/utils.ts

fix: unable to see test failure output

---

examples/tests/valid/std_string.w
libs/wingc/examples/compile.rs
libs/wingc/src/jsify.rs
tools/hangar/__snapshots__/test_corpus/valid/std_string.w_compile_tf-aws.md

fix(compiler): multiline strings cause compiler error

---

docs/docs/02-concepts/04-tests.md

Adding tests docs to core concepts
fixes [#2192](https://github.com/winglang/wing/issues/2192)

feat(docs): test core concepts docs

---

docs/docs/999-faq/041-is-the-console-open-source.md

chore(docs): add FAQ about the console license

---

docs/docs/04-standard-library/01-cloud/api.md

fixes https://github.com/winglang/wing/issues/2652

feat(docs): add cloud.api usage example

---

docs/docs/04-standard-library/01-cloud/function.md

Fixes https://github.com/winglang/wing/issues/2655

feat(docs): cloud.Function usage docs

---

docs/docs/04-standard-library/01-cloud/queue.md

fixes  https://github.com/winglang/wing/issues/2656

feat(docs): cloud.Queue usage docs

---

.github/workflows/tf-aws-test.yml

chore(sdk): change sdk spec test gh workflow trigger to releasing a version

---

libs/wingsdk/src/cloud/api.md
libs/wingsdk/src/cloud/website.md

Fixes https://github.com/winglang/wing/issues/2662

feat(docs): cloud.website usage

---

libs/wingsdk/src/cloud/website.md

Testing workflow changes in https://github.com/winglang/wing/pull/3235

chore(docs): testing new workflow update

---

docs/docs/07-examples/02-primitives.md

Testing workflow changes in https://github.com/winglang/wing/pull/3235

chore(docs): minor change to test workflow

---

docs/docs/04-standard-library/01-cloud/api.md
docs/docs/04-standard-library/01-cloud/website.md
libs/wingsdk/src/cloud/website.md

chore(docs): testing workflow

---

.github/workflows/build.yml
.mergify.yml

chore: mergify should not ignore all md file

---

docs/docs/04-standard-library/01-cloud/schedule.md
libs/wingsdk/src/cloud/schedule.md

Fixes https://github.com/winglang/wing/issues/2657

feat(docs): schedule usage docs

---

docs/docs/04-standard-library/01-cloud/api.md
docs/docs/04-standard-library/01-cloud/bucket.md
docs/docs/04-standard-library/01-cloud/counter.md
docs/docs/04-standard-library/01-cloud/function.md
docs/docs/04-standard-library/01-cloud/queue.md
docs/docs/04-standard-library/01-cloud/schedule.md
docs/docs/04-standard-library/01-cloud/secret.md
docs/docs/04-standard-library/01-cloud/service.md
docs/docs/04-standard-library/01-cloud/topic.md
docs/docs/04-standard-library/01-cloud/website.md
libs/wingsdk/src/cloud/api.md
libs/wingsdk/src/cloud/bucket.md
libs/wingsdk/src/cloud/counter.md
libs/wingsdk/src/cloud/function.md
libs/wingsdk/src/cloud/queue.md
libs/wingsdk/src/cloud/schedule.md
libs/wingsdk/src/cloud/secret.md
libs/wingsdk/src/cloud/service.md
libs/wingsdk/src/cloud/topic.md
libs/wingsdk/src/cloud/website.md

fix(docs): broken link

---

.github/workflows/build.yml

Reverts winglang/wing#3277
Fixes #3276

chore: add build skip for docs

---

docs/docs/src/components/CodeComparison.jsx
docs/docs/src/examples/function-upload-to-bucket/platforms.js
docs/docs/src/examples/function-upload-to-bucket/wing.js

fix(docs): examples file loader

---

docs/docs/03-language-guide/_category_.yml
docs/docs/03-language-reference.md

chore(docs): language ref up one level in doc tree

---

docs/docs/03-language-reference.md

chore(docs): lang ref had a wrong section heading

---

apps/jsii-docgen/src/docgen/render/markdown-doc.ts
apps/jsii-docgen/src/docgen/render/markdown-render.ts
apps/jsii-docgen/src/docgen/schema.ts
apps/jsii-docgen/src/docgen/transpile/wing.ts
apps/jsii-docgen/src/docgen/view/class.ts
docs/docs/04-standard-library/01-cloud/api-reference.md
docs/docs/04-standard-library/02-std/api-reference.md
docs/docs/04-standard-library/03-http/api-reference.md
docs/docs/04-standard-library/04-util/api-reference.md
docs/docs/04-standard-library/05-ex/api-reference.md
libs/wingsdk/src/http/http.ts
libs/wingsdk/src/util/util.ts

fixes #3340
https://www.loom.com/share/91777606a38249d688a101a83f41284b?sid=b0ba92e2-9a0c-4ed8-ae30-98304b295375
* remove "Inflight client: true" and replace it with an inflight keyword in signature 
* remove "Util."
* bring classes section up above structs (improves readability in the HTTP and Utilities pages, the only place is affecting is in ex, but it looks good there too ) <img width="224" alt="image" src="https://github.com/winglang/wing/assets/39455181/a5327c59-f852-4596-9cfb-b87818cc1209">
* Rename Util class with the namespace (i.e Http)

feat(docs): small improvements 

---

docs/docs/04-standard-library/03-http/api-reference.md
libs/wingc/src/lsp/snapshots/completions/namespace_inflight.snap
libs/wingsdk/src/http/http.ts

fixes #3347
* specify the difference between `get` and `fetch`
* add comprehensive docs for other methods

chore(docs): docs for the http methods in `http.ts` sdk lib

---

docs/docs/01-start-here/05-aws.md

Add a cleanup step to our getting started guide by running `terraform destroy`.

chore(docs): getting started guide - cleanup

---

libs/wingsdk/.projen/tasks.json
libs/wingsdk/.projenrc.ts

* removing hardcoded resources from SDK documentation generation process.

fix(sdk): no hardcoded resources on sdk's projen

---

libs/wingc/project.json
libs/wingcompiler/package.json
libs/wingcompiler/tsup.config.ts
package.json
patches/wasi-js@1.7.3.patch
pnpm-lock.yaml

fix: missing transitive deps for wasi-js

---

apps/wing-console/console/app/src/analytics.ts

chore(console): lowercased analytics events

---

.github/workflows/build.yml
.mergify.yml

chore: infra for code freeze

---

docs/docs/01-start-here/01-getting-started.md
docs/docs/01-start-here/02-installation.md
docs/docs/01-start-here/03-hello.md
docs/docs/01-start-here/04-run-locally.md
docs/docs/01-start-here/05-aws.md
docs/docs/06-tools/02-wing-console.md

fix(docs): post code freeze small issues

---

.mergify.yml

fix: typo in mergify commit message

---

.mergify.yml

Trying this out 🤞 
Took out the title validation from the merge queue because that probably won't pass on whatever  temp PR mergify creates.

chore: enable speculative merges

---

docs/docs/08-guides/01-terraform-backend.md

This should save someone a StackOverflow lookup (https://stackoverflow.com/questions/51912072/invalidlocationconstraint-error-while-creating-s3-bucket-when-the-used-command-i)

chore(docs): update terraform backend guide

---

.github/workflows/canary.yml

Disabling analytics for canary job

chore(repo): disable analytics for canary

---

apps/wing-console/console/app/src/analytics.ts

chore(console): remove white spaces from analytics events

---

docs/docs/02-concepts/03-compile-targets.md

chore(docs): modified compiler target code example

---

docs/docs/07-examples/01-variable-declaration.md
docs/docs/07-examples/02-primitives.md
docs/docs/07-examples/03-functions.md

chore(docs): fix examples

---

docs/docs/01-start-here/01-getting-started.md

chore: tweaks to docs

---

docs/docs/02-concepts/01-preflight-and-inflight.md
docs/docs/03-language-reference.md
docs/docs/04-standard-library/01-cloud/api.md
docs/docs/04-standard-library/01-cloud/bucket.md
docs/docs/04-standard-library/01-cloud/counter.md
docs/docs/04-standard-library/01-cloud/queue.md
libs/wingsdk/src/cloud/api.md
libs/wingsdk/src/cloud/bucket.md
libs/wingsdk/src/cloud/counter.md
libs/wingsdk/src/cloud/queue.md

(manually backported to due self-mutation being skipped initially)

chore(docs): code sample fixes (backport #3469)

---

docs/docs/01-start-here/02-installation.md
docs/docs/01-start-here/03-hello.md
docs/docs/01-start-here/04-run-locally.md

chore: tweaks to getting started

---

README.md
apps/wing/README.md

fix(docs): link to cloud library documentation is incorrect

---

docs/docs/01-start-here/01-getting-started.md

fix(docs): broken inflight link

---

apps/wing-console/console/app/src/analytics.ts

take 2
resolves: https://github.com/winglang/wing/issues/3598

fix(console): segment offline crash

---

apps/wing-console/console/app/package.json
apps/wing-console/console/app/src/analytics.ts
pnpm-lock.yaml

take 3
use the same segment node library as in wing
All previous fixes worked locally while being offline (this one as well)... hopefully this one will do it.

fix(console): segment fail offline

---

apps/wing-console/console/app/web/index.tsx
apps/wing-console/console/server/src/expressServer.ts
apps/wing-console/console/server/src/index.ts
apps/wing-console/console/server/src/router/app.ts
apps/wing-console/console/server/src/types.ts
apps/wing-console/console/server/src/utils/createRouter.ts
apps/wing-console/console/server/src/utils/simulator.ts

Also, fixes inconsistencies with the `Trace` type.

fix(console): server websocket connection

---

README.md
apps/wing/README.md

chore(docs): update contribution license in readme

---

libs/wingsdk/src/shared-aws/bucket.inflight.ts

fix(docs): fixing bucket jsdoc for shared-aws

---

docs/docs/04-standard-library/04-util/api-reference.md
libs/wingsdk/src/util/util.ts

chore(docs): base64 docs small fixes

---

Cargo.lock
libs/wingc/Cargo.toml
libs/wingsdk/.projen/deps.json
libs/wingsdk/.projenrc.ts
libs/wingsdk/package.json
libs/wingsdk/test/target-sim/service.test.ts
libs/wingsdk/test/util.ts
pnpm-lock.yaml

chore: remove unused deps

---

docs/docs/999-faq/040-alternatives/042-pulumi-vs-wing.md

chore(docs): changed title to "pulumi vs. wing [main differences]"

---

docs/docs/999-faq/040-alternatives/047-darklang-vs-wing.md

chore(docs): changed title to "darklang vs. wing [main differences]"

---

docs/contributing/999-rfcs/2022-05-28-winglang-reqs.md
docs/contributing/999-rfcs/2022-06-14-polycons.md
docs/contributing/999-rfcs/2022-08-22-resource-naming.md
docs/contributing/999-rfcs/2023-01-20-wingsdk-spec.md
docs/contributing/999-rfcs/2023-01-21-wing-plugins.md
docs/contributing/999-rfcs/2023-04-16-website-resource.md
docs/contributing/999-rfcs/2023-06-12-language-spec.md
docs/contributing/999-rfcs/2819-stdlib.md
docs/contributing/999-rfcs/overview.md

Organize the RFC section a little bit.
1. Add issue numbers and stage to each RFC
2. Change title of "Overview" to "RFC Workflow"

chore: organize RFCs topic

---

libs/wingsdk/src/cloud/function.ts
libs/wingsdk/src/shared-aws/function.inflight.ts
libs/wingsdk/src/shared-aws/function.ts
libs/wingsdk/src/target-awscdk/function.ts
libs/wingsdk/src/target-tf-aws/function.ts
libs/wingsdk/test/shared-aws/function.inflight.test.ts
libs/wingsdk/test/target-awscdk/__snapshots__/bucket.test.ts.snap
libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap
libs/wingsdk/test/target-awscdk/__snapshots__/function.test.ts.snap
libs/wingsdk/test/target-awscdk/__snapshots__/queue.test.ts.snap
libs/wingsdk/test/target-awscdk/__snapshots__/schedule.test.ts.snap
libs/wingsdk/test/target-awscdk/__snapshots__/topic.test.ts.snap

Fixes #3710
Previous changes to `cloud.Function` were causing issues for API Gateways because they started returning an object that wrapped the payload instead of a plain payload. To fix this I'm proposing an implementation that avoids the payload wrapping problem.

fix(sdk): cloud.Api doesn't work on AWS

---

examples/tests/sdk_tests/website/two_websites.w
libs/wingsdk/src/target-tf-aws/website.ts
libs/wingsdk/test/target-awscdk/__snapshots__/counter.test.ts.snap
libs/wingsdk/test/target-tf-aws/__snapshots__/website.test.ts.snap
tools/hangar/__snapshots__/test_corpus/sdk_tests/website/two_websites.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/website/two_websites.w_test_sim.md
tools/hangar/__snapshots__/test_corpus/valid/website_with_api.w_compile_tf-aws.md

fix(sdk): fixing website oac naming

---

docs/docs/03-language-reference.md

Makes the side bar name look better and not so wordy and fit better

chore(docs): give language reference shorter nav name

---

examples/tests/valid/function_variadic_arguments.w
libs/wingc/src/type_check/jsii_importer.rs
tools/hangar/__snapshots__/test_corpus/valid/function_variadic_arguments.w_compile_tf-aws.md

fix(compiler): cannot use variadic functions from jsii libraries

---

docs/docs/04-standard-library/01-cloud/counter.md

chore(docs): added “distributed” to the counter title

---

docs/docs/06-tools/01-cli.md
docs/docs/06-tools/03-plugins.md

Some more title changes based on SEO recommendations.
See: https://github.com/winglang/wing/issues/3164

chore(docs): title changes in tools section

---

docs/docs/999-faq/040-alternatives/041-terraform-vs-wing.md
docs/docs/999-faq/040-alternatives/043-awscdk-vs-wing.md
docs/docs/999-faq/040-alternatives/044-cdktf-vs-wing.md

Some of the main differences docs were already updated for better SEO this PR just gets the rest of them.
See: https://github.com/winglang/wing/issues/3164

chore(docs): finish changing titles to use vs. docs

---

libs/wingsdk/test/target-sim/__snapshots__/queue.test.ts.snap
libs/wingsdk/test/target-sim/queue.test.ts

chore(sdk): queue batch test can't use snapshots because execution order is not guaranteed

---

examples/tests/sdk_tests/queue/pop.w
tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/pop.w_compile_tf-aws.md

Updating the test with the `nil` type and `Queue.push()` variadic argument instead of for loop.

chore(sdk): update `queue.pop()` sdk test

---

docs/docs/03-language-reference.md

Following #3840 - updated the language reference with `if let var`.

chore(docs): update language ref with `if let var`

---

docs/docs/04-standard-library/02-std/api-reference.md
examples/tests/sdk_tests/std/array.w
libs/wingsdk/src/std/array.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/std/array.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/std/array.w_test_sim.md

feat(sdk): add `mutarray.insert()` to std library

---

pnpm-lock.yaml

PNPM defaults to single quotes, so it should probably stay that way. This PR does not solve the root issue to prevent this from switching but should temporarily help with thrashing

chore(repo): switch back to single quotes for pnpm lockfile

---

apps/wing-console/console/ui/src/layout/default-layout.tsx
apps/wing-console/console/ui/src/layout/layout-provider.tsx

feat(console): remove rounded corners for playground and learn sites

---

.github/workflows/build.yml
apps/wing-console/console/app/turbo.json
tools/bump-pack/src/turbo-diff.ts

chore(repo): skip console preview if not needed

---

docs/docs/03-language-reference.md

Closes https://github.com/winglang/docsite/issues/586

fix(docs): broken link in strings section

---

docs/contributing/01-start-here/01-contributing-to-wing.md
docs/docs/02-concepts/03-compile-targets.md
docs/docs/999-faq/020-supported-clouds-services-and-engines/022-supported-services.md

fix(docs): broken links fixed

---

docs/contributing/999-rfcs/2022-06-14-polycons.md

chore(docs): update polycons RFC disclaimer

---

apps/vscode-wing/.projen/deps.json
apps/vscode-wing/.projen/tasks.json
apps/vscode-wing/.projenrc.ts
apps/vscode-wing/package.json
pnpm-lock.yaml

Fixes https://github.com/winglang/wing/security/dependabot/130

chore: dependabot fix for vscode

---

apps/wing/src/cli.ts

chore(cli): show global options in wing cli

---

docs/contributing/01-start-here/05-development.md

I was searching for that and thought that was helpful to have in the contrib docs.

chore(docs): disable turbo cache with `--force`

---

docs/docs/07-examples/06-json.md

Fixing some typos and updated doc with implemented feature (struct from json)

chore(docs): update json examples

---

libs/wingsdk/src/.gen/versions.json

It snuck back in passed the gitignore. (why??)

chore(build): re-delete cdktf version json

---

libs/wingsdk/src/shared-aws/table.inflight.ts
libs/wingsdk/src/target-tf-aws/table.ts

fix(sdk): fixing table methods

---

examples/tests/valid/json.main.w
libs/wingc/src/type_check.rs
tools/hangar/__snapshots__/test_corpus/valid/json.main.w_compile_tf-aws.md

Fixes #3894
Not sure if it was explicitly left out for a reason. For literals, it obviously looks a little ugly, but there's no logical issue as far as I can see.

feat(compiler): allow map to be valid json

---

turbo.json

chore(repo): tell turbo to watch tsx files

---

apps/vscode-wing/syntaxes/wing.tmLanguage.json

chore(vscode): highlight `pub` keyword

---

examples/tests/sdk_tests/dynamodb-table/transaction.main.w

fix: unable to run dynamodb tests on non linux CI

---

apps/wing-console/console/app/demo/main.w
libs/wingsdk/src/target-sim/service.ts

fixes https://github.com/winglang/wing/issues/4234

fix(sdk): cloud service on stop function title

---

apps/wing-console/console/server/src/index.ts
apps/wing-console/console/ui/src/features/dynamodb-table-interaction-view.tsx
apps/wing-console/console/ui/src/services/use-dynamodb-table.ts
docs/docs/04-standard-library/06-ex/api-reference.md
examples/tests/sdk_tests/dynamodb-table/query.main.w
libs/wingsdk/src/ex/dynamodb-table.ts
libs/wingsdk/src/target-tf-aws/dynamodb-table.ts
libs/wingsdk/test/target-sim/dynamodb-table.test.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/dynamodb-table/query.main.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/dynamodb-table/query.main.w_test_sim.md

Adds the DynamoDBTable query command, and changes the scan command as well.
BREAKING CHANGE: the response of the DynamoDBTable scan command now returns an object that contains the items (and other stuff) instead of returning the items directly

feat(sdk)!: improve dynamodb table resource

---

apps/wing-console/console/ui/src/layout/default-layout.tsx

fix(console): panels gap color with custom theme

---

libs/wingsdk/src/util/util.ts
libs/wingsdk/test/target-tf-aws/website.test.ts

Removing some comments that don't need to be part of the project

chore(sdk): removing unnecessary comments

---

libs/wingsdk/src/.gen/versions.json
libs/wingsdk/src/target-tf-azure/bucket.inflight.ts
libs/wingsdk/test/target-tf-azure/bucket.inflight.test.ts

added publcUrl inflight method for tf-azure target
Fixed #1805

feat(sdk): added publicUrl for tf-azure target

---

docs/contributing/01-start-here/07-wingsdk.md
docs/contributing/999-rfcs/overview.md
libs/wingsdk/README.md

chore(docs): remove outdated references to polycons

---

docs/contributing/999-rfcs/2023-03-08-wing-preview-environment.md

chore: move preview environments rfc to contributing section

---

apps/wing/src/commands/compile.test.ts
libs/wingc/examples/compile.rs
libs/wingc/src/jsify.rs
libs/wingc/src/lib.rs
libs/wingc/src/lsp/sync.rs
libs/wingc/src/parser.rs
libs/wingc/src/test_utils.rs
libs/wingcompiler/src/compile.ts
tools/hangar/__snapshots__/test_corpus/valid/assertions.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/baz.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/store.w_compile_tf-aws.md
tools/hangar/src/generated_test_targets.ts

Reverts #4342 due to windows e2e failure https://github.com/winglang/wing/actions/runs/6357417861/attempts/1

revert(cli): compile directories

---

README.md
apps/vscode-wing/README.md
apps/wing/README.md

chore(docs): remove alpha references

---

libs/wingsdk/src/target-awscdk/queue.ts
libs/wingsdk/src/target-tf-aws/queue.ts
libs/wingsdk/test/target-awscdk/__snapshots__/queue.test.ts.snap
libs/wingsdk/test/target-sim/__snapshots__/queue.test.ts.snap
libs/wingsdk/test/target-sim/queue.test.ts
libs/wingsdk/test/target-tf-aws/__snapshots__/captures.test.ts.snap
libs/wingsdk/test/target-tf-aws/__snapshots__/queue.test.ts.snap
tools/hangar/__snapshots__/plugins.ts.snap
tools/hangar/__snapshots__/test_corpus/sdk_tests/queue/set_consumer.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/captures.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/file_counter.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/hello.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/inflight-subscribers.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/redis.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/resource.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/while_loop_await.test.w_compile_tf-aws.md

tests are passing now
tf-aws:
awscdk:
(also fixes: #1526)

fix(sdk): fixing queue setconsumer cloud function timeout

---

.github/workflows/tf-aws-test.yml

chore: fix permissions in spec workflow

---

examples/tests/invalid/ambiguous_api_paths.test.w
tools/hangar/__snapshots__/invalid.ts.snap
tools/hangar/src/utils.ts

leftover from this task: https://github.com/winglang/wing/pull/4352

chore: add ambiguous paths invalid tests and sanitize output

---

examples/tests/sdk_tests/website/react-website/build.js
examples/tests/sdk_tests/website/react-website/package.json
libs/wingsdk/src/target-sim/react-app.inflight.ts

Needed a cross-platform build script

fix: react sdk test fails on windows

---

docs/docs/04-standard-library/02-ex/dynamodb-table.md
libs/wingsdk/src/ex/dynamodb-table.ts
libs/wingsdk/src/target-tf-aws/dynamodb-table.ts
libs/wingsdk/test/target-sim/dynamodb-table.test.ts

Also:
- Add links to the official AWS DynamoDB documentation
- Add missing policy statements for some inflights

feat(sdk): add DynamoDB Table batchGetItems inflight method

---

docs/docs/04-standard-library/01-cloud/function.md
libs/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap
libs/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap
libs/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap
libs/wingsdk/src/cloud/function.ts

`Function.invokeAsync()` still hasn't been implemented: #1387

fix(docs): fix `Function.invoke()` docs

---

apps/wing-console/console/server/src/utils/format-wing-error.ts
apps/wing/src/commands/compile.ts
tools/hangar/__snapshots__/error.ts.snap

fix(cli): broken link in error message

---

libs/wingsdk/src/target-tf-aws/website.ts

Fixes #4319
e2e tests are not possible since we don't deploy to AWS via windows. This would also be solved via https://github.com/winglang/wing/issues/4288

fix: cloud.Website in AWS does not escape Windows path for assets

---

apps/wing/src/commands/test.test.ts

Adding missing test for `wing test` that checks if the command can correctly pick up files matching the default entrypoint.

chore(cli): add test for `wing test` default entrypoint

---

examples/tests/valid/resource.test.w
libs/wingc/src/fold.rs
tools/hangar/__snapshots__/test_corpus/valid/resource.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/tree_json.ts.snap

fix(compiler): panic in `in scope` expression when using type reference

---

apps/wing-console/console/app/demo/main.w
apps/wing-console/console/design-system/src/utils/icon-utils.ts

A key icon seems more appropriate for representing a secret.

chore: change `cloud.Secret` icon to a key icon

---

libs/wingsdk/src/target-tf-aws/api.ts

Refactoring of http methods from `cloud.Api`

chore(sdk): removing duplicated code from tf-aws cloud.Api

---

docs/docs/04-standard-library/compatibility/compatibility.json

Updating the compatibility matrix with latest changes.

chore(docs): update compatibility matrix

---

apps/jsii-docgen/.projenrc.ts
apps/jsii-docgen/package.json
docs/docs/05-libraries.md
examples/wing-fixture/package.json
libs/wingsdk/.projenrc.ts
libs/wingsdk/package.json

Following #4591 - removing the note from https://www.winglang.io/docs/libraries
Also changed ping@monada.co => ping@wing.cloud

chore(docs): remove note from libraries doc

---

docs/docs/04-standard-library/compatibility/compatibility.json

Upon checking, there's more stuff that's already implemented.

chore(docs): update bucket in compatibility matrix

---

.github/workflows/build.yml
examples/tests/sdk_tests/table/try_get.test.w
libs/wingsdk/src/target-tf-aws/table.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/table/try_get.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/table/try_get.test.w_test_sim.md

Misc: the fly.io preview app now needs an org argument as we have more than one

fix(sdk): table tryGet permissions are missing

---

README.md

chore(docs): changing wording of README

---

.github/workflows/build.yml
.github/workflows/canary.yml
.github/workflows/tf-aws-test.yml

Release notes: [v4.0.0](https://github.com/actions/setup-node/releases/tag/v4.0.0)

chore(build): upgrade to `setup-node@v4` in workflows

---

docs/contributing/999-rfcs/2022-05-28-winglang-reqs.md
examples/README.md

chore(docs): updated the name of Twitter to X

---

apps/wing-console/console/app/demo/main.w

resolves: https://github.com/winglang/wing/issues/4718

fix(console): remove cloud.Secret from console demo app

---

CONTRIBUTING.md

there were typo errors in the contributing.md file

chore(docs): grammatical errors

---

libs/wingsdk/src/shared-aws/bucket.inflight.ts
libs/wingsdk/src/target-tf-aws/bucket.ts

Aligning the code to [what did](https://github.com/winglang/wing/pull/4656#discussion_r1369996394) for `tf-gcp` and replacing generic error with AWS error class.

chore(sdk): small tweaks to `tf-aws` bucket

---

apps/wing-console/console/ui/src/services/use-tests.ts
apps/wing-console/console/ui/src/tests-context.tsx
apps/wing-console/console/ui/src/ui/map-controls.tsx
apps/wing-console/console/ui/src/ui/no-tests.tsx
apps/wing-console/console/ui/src/ui/test-tree.tsx

resolves: https://github.com/winglang/wing/issues/4066

fix(console): show tests button is visible when there are no tests

---

examples/tests/valid/optionals.test.w
libs/wingc/src/parser.rs
tools/hangar/__snapshots__/test_corpus/valid/optionals.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/optionals.test.w_test_sim.md

Closes: https://github.com/winglang/wing/issues/4754

fix(compiler): elif let statements uknown symbols

---

docs/docs/04-standard-library/01-cloud/workload.md
docs/docs/999-faq/020-supported-clouds-services-and-engines/025-kubernetes-support.md
libs/wingsdk/src/cloud/workload.md

The experimental `Workload` resource is now available via the `@winglibs/containers` library. This pull request adds documentation for this resource so it is discoverable.
Fixes #4519
Fixes #2319
Related #678

feat: containerized workloads

---

apps/wing-console/console/design-system/src/scrollable-area.tsx
apps/wing-console/console/ui/src/layout/default-layout.tsx
apps/wing-console/console/ui/src/layout/use-layout.tsx
apps/wing-console/console/ui/src/widgets/logs.tsx

Fixes #4354.
Does some additional refactoring of the Logs component.

fix(console): new log messages always scroll down the view

---

apps/wing-console/console/ui/src/features/map-view.tsx
apps/wing-console/console/ui/src/services/use-explorer.tsx
apps/wing-console/console/ui/src/ui/elk-map.tsx

feat(console): remove references to root node

---

.github/workflows/tf-aws-test.yml

fix(repo): fixing spec test target param

---

apps/wing-console/console/ui/src/ui/elk-map.tsx
apps/wing-console/console/ui/src/widgets/logs.tsx

fix(console): logs don't scroll to the bottom initially

---

apps/wing/src/commands/test/test.ts

I've noticed that there's an existing function in util library so better use that to make code more clean.

chore(cli): small tweak for test command

---

docs/contributing/01-start-here/09-troubleshooting.md

chore(docs): troubleshooting for pnpm install error

---

docs/docs/04-standard-library/03-std/api-reference.md
examples/tests/sdk_tests/std/struct.test.w
libs/wingc/src/lsp/snapshots/completions/struct_static.snap
libs/wingsdk/src/std/json_schema.ts
libs/wingsdk/src/std/struct.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/std/struct.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/std/struct.test.w_test_sim.md

Introduces the `parseJson` and `tryParseJson` methods on Wing Structs
Closes: https://github.com/winglang/wing/issues/4811

feat(sdk): support Struct.parseJson()

---

docs/docs/01-start-here/04-run-locally.md

docs: fix minor typo in "run locally"

---

libs/wingsdk/src/target-tf-azure/app.ts
libs/wingsdk/test/target-tf-azure/__snapshots__/captures.test.ts.snap
libs/wingsdk/test/target-tf-azure/__snapshots__/function.test.ts.snap
libs/wingsdk/test/target-tf-azure/captures.test.ts
libs/wingsdk/test/target-tf-azure/function.test.ts

chore(sdk): migrate Azure Application Insights from classic mode to workspace-based mode

---

examples/tests/sdk_tests/topic/no_blocking.test.w

fix: no_blocking.test.w flaking

---

docs/docs/04-standard-library/02-ex/dynamodb-table.md
libs/wingsdk/src/ex/dynamodb-table.ts

docs(docs): dynamodb-table.ts has wrong description for updateItem

---

apps/wing-console/console/design-system/src/theme-provider.tsx

resolves: https://github.com/winglang/wing/issues/4934

fix(console): can not toggle console theme

---

apps/wing-console/console/app/demo/main.w
apps/wing-console/console/server/src/utils/compiler.ts
apps/wing-console/console/server/src/utils/format-wing-error.ts

The Console server is currently logging unnecessary stuff.

fix(console): remove unused CLI logs

---

docs/docs/02-concepts/03-platforms.md

Oops forgot to add when I implemented it.

chore(docs): add newInstance to the platforms docs

---

libs/wingsdk/src/shared-aws/bucket.inflight.ts
libs/wingsdk/src/target-sim/bucket.inflight.ts
libs/wingsdk/src/target-tf-azure/bucket.inflight.ts

Switching method to have less verbose code.

chore(sdk): code linting in `tf-azure` bucket

---

apps/wing-console/console/ui/src/features/console-logs.tsx

resolves: https://github.com/winglang/wing/issues/5003

fix: long log messages overflow the console log container

---

examples/tests/valid/platforms/local-package/a-relative-platform.js
examples/tests/valid/platforms/local-package/index.js
libs/wingsdk/src/platform/platform-manager.ts
tools/hangar/src/platform.test.ts

fix(sdk): relative imports for external platforms

---

apps/wing-console/console/server/src/router/test.ts

Resolves https://github.com/winglang/wing/issues/5049

fix(console): wrong number of passed tests in logs

---

apps/wing-console/console/design-system/src/theme-provider.tsx

chore(console): console theme-provider useEffect missing dependency

---

README.md
tools/hangar/__snapshots__/test_corpus/valid/inheritance_interface.test.w_compile_tf-aws.md

chore: fix build by updating snapshots

---

docs/docs/07-examples/80-singletons.md

Triggering doc publish, because there was previously a github outage.
Fixes #5085

chore(docs): small doc change to trigger publish

---

docs/docs/04-standard-library/03-std/api-reference.md
libs/wingsdk/src/std/node.ts

Docs were broken due to unintended html tags missing closing tags
https://github.com/winglang/docsite/pull/708
https://github.com/winglang/docsite/actions/runs/7034089517/job/19141315335?pr=708

chore(docs): docs are broken

---

docs/docs/04-standard-library/03-std/api-reference.md
examples/tests/sdk_tests/std/string.test.w
libs/wingc/src/lsp/snapshots/completions/partial_reference_call.snap
libs/wingsdk/src/std/string.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/std/string.test.w_test_sim.md

Adding this method since I needed it and I think it's useful.

feat(sdk): add `String.replaceAll()`

---

libs/wingsdk/src/shared-azure/function.inflight.ts
libs/wingsdk/src/shared/bundling.ts
libs/wingsdk/src/target-tf-azure/app.ts
libs/wingsdk/src/target-tf-azure/bucket.inflight.ts
libs/wingsdk/src/target-tf-azure/bucket.ts
libs/wingsdk/test/target-tf-azure/__snapshots__/captures.test.ts.snap
libs/wingsdk/test/target-tf-azure/bucket.inflight.test.ts
libs/wingsdk/test/target-tf-azure/function.inflight.test.ts

Fixes: https://github.com/winglang/wing/issues/5087
it should fix: #5080 too
I noticed that we're not reporting the error message when the test fails #5111

fix(sdk): azure test should fail on error

---

apps/wing-console/console/app/src/index.ts
apps/wing-console/console/server/src/index.ts
apps/wing-console/console/server/src/utils/compiler.ts

Supporting custom platforms when starting the console server through the console package

feat: start console server with custom platform

---

apps/wing-console/console/server/src/index.ts

fix(console): remove ANSI characters from test logs

---

apps/wing-console/console/server/src/router/app.ts

feat(console): hide connections from API to its endpoints

---

apps/wing-console/console/server/src/router/app.ts
apps/wing-console/console/ui/src/ui/edge-item.tsx

Dashed strokes have a big performance impact when there's many resources. Let's use solid strokes for now.

fix(console): remove dashed strokes

---

docs/contributing/01-start-here/05-development.md

Small note to help others stuck in potential same issue as me with multiple rust installs 
https://winglang.slack.com/archives/C048QCN2XLJ/p1702038281891739 

chore: add docs about conflicting rust installs

---

docs/docs/06-tools/01-cli.md

fix(docs): awscdk platform instructions

---

libs/wingsdk/src/shared/misc.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/dynamodb-table/aws-dynamodb.test.w_test_sim.md
tools/hangar/__snapshots__/test_corpus/valid/redis.test.w_test_sim.md

fix(sdk): unnecessary stderr from `docker inspect`

---

.github/ISSUE_TEMPLATE/feature.yml

chore: add Libraries option to feature category dropdown

---

docs/contributing/03-stories/story-16.md

User story for the initial version of Wing for TypeScript.

chore: story 16 - wing for typescript

---

docs/docs/04-standard-library/µ-winglang_support_metrix.mdx

chore: fix "Compatibility Matrix" title in docs

---

apps/wing-console/console/app/src/index.ts

chore(console): remove resource specific analytics events

---

apps/wing-console/console/ui/src/features/map-view.tsx
apps/wing-console/console/ui/src/layout/default-layout.tsx
apps/wing-console/console/ui/src/ui/explorer.tsx
apps/wing-console/console/ui/src/widgets/logs.tsx

- The Console will show the logs even when there's an error during compile
- The Console won't block the hierarchy, the explorer and the logs while the Simulator is compiling

fix(console): stop blocking the ui unnecessarily

---

.github/workflows/build.yml
.github/workflows/mutation.yml
.github/workflows/tf-aws-test.yml

Reverts winglang/wing#5230
See failure here https://github.com/winglang/wing/actions/runs/7261765480/job/19783678482

revert(build): upgrade github actions to artifacts v4

---

docs/docs/07-examples/04-flow-controls.md

Hi!
I encountered two examples for which I could not find documentation on the site (even [here](https://www.winglang.io/docs/language-reference#26-for)), I think it is important to mention them at least in the examples

docs(examples): add important examples to for-loop

---

apps/wing-console/console/server/src/index.ts
libs/wingsdk/src/target-sim/dynamodb-table.inflight.ts

fixes #4901 
we didn't clean up the test simulator, apparently 

fix(console): kill dynamo zombies

---

apps/wing-console/console/server/src/router/test.ts

fix(console): can't see test logs

---

libs/wingii/src/util.rs

fix: panic when handling malformed package.json

---

docs/docs/08-guides/01-terraform-backend.md

fix(docs): outdated tf-backend plugin

---

libs/awscdk/src/website.inflight.ts
libs/awscdk/src/website.ts

Removing unused code from the cloud.Website for the awscdk and adding website.inflight.ts to awscdk

chore(sdk): cloud.Website awscdk cleaning

---

libs/wingsdk/src/std/test-runner.ts
libs/wingsdk/test/target-sim/test-runner.test.ts
libs/wingsdk/test/target-tf-aws/test-runner.test.ts

fix(sdk): fixing test matches parsing

---

apps/wing/src/cli.ts
apps/wing/src/commands/pack.test.ts
apps/wing/src/commands/pack.ts

fix(cli): `wing pack` does not respect `-o` for custom output filename

---

README.md
apps/wing-console/console/ui/src/ui/no-resources.tsx
apps/wing/README.md
docs/contributing/998-archived/01-compile-targets.md
docs/contributing/999-rfcs/2023-06-12-language-spec.md
docs/docs/01-start-here/06-learn-more.md
docs/docs/03-language-reference.md
docs/docs/04-standard-library/ex/react-app.md
docs/docs/999-faq/010-good-fit.md
docs/docs/999-faq/020-supported-clouds-services-and-engines/022-supported-services.md
libs/wingsdk/src/ex/react-app.md

The Algolia tool notified us of some broken links in our documentation. This PR fixes those links.

chore(docs): fixing broken links in the docs

---

docs/contributing/01-start-here/07-wingsdk.md
docs/docs/02-concepts/03-platforms.md

chore(docs): fix typos

---

apps/wing-console/console/server/src/router/app.ts
apps/wing-console/console/ui/src/ui/resource-metadata.tsx

If exists, add a resource description to the resource metadata
resolves: https://github.com/winglang/wing/issues/5300

feat(console): show resource description

---

docs/docs/04-standard-library/compatibility/compatibility.json

Both #4333 and #1805 got closed, so reflecting the change on the compatibility matrix.

chore(docs): update compatibility matrix for `tf-azure` platform

---

docs/docs/07-examples/10-using-javascript.md

fix: docs(typo's)

---

examples/tests/sdk_tests/dynamodb-table/global-secondary-index.test.w

Fix (skip) failing test on mac following #5266

fix: skip ddb tests on mac/win because no docker support in env

---

libs/compatibility-spy/src/index.ts
tools/hangar/__snapshots__/compatibility-spy.ts.snap

reading lifted ops from `onLift` method's args

fix(platforms): fixing usage report

---

docs/docs/04-standard-library/compatibility/compatibility-table.jsx
docs/docs/04-standard-library/compatibility/compatibility.json

- refactoring the matrix spacing (so when we update the content for real we can see what changed)
- hiding issue numbers when an operation is implemented.

chore(docs): formatting small changes to the matrix logic

---

apps/wing-console/console/ui/src/ui/zoom-pane.tsx

Devices with touchpads can move the map around with the usual scrolling gestures (typically, using two fingers), but devices with keyboard and mouse need an alternative way to easily move the map around. This feature allows clicking on the map with a mouse and moving it around, in addition to the recent two-finger gesture.
Solves #5446.

feat(console): allow dragging the map with the mouse

---

apps/wing-console/console/app/demo/main.w
apps/wing-console/console/server/src/router/app.ts

resolves: https://github.com/winglang/wing/issues/5506

fix(console): hidden resources relationships are not shown in console

---

examples/tests/valid/anon_function.test.w
libs/wingc/src/jsify.rs
libs/wingc/src/jsify/snapshots/capture_from_inside_an_inflight_closure.snap
libs/wingc/src/jsify/snapshots/capture_in_keyword_args.snap
libs/wingc/src/jsify/snapshots/func_returns_func.snap
libs/wingc/src/jsify/snapshots/two_identical_lifts.snap
libs/wingc/src/jsify/snapshots/wait_util.snap
tools/hangar/__snapshots__/test_corpus/valid/anon_function.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/anon_function.test.w_test_sim.md
tools/hangar/__snapshots__/test_corpus/valid/calling_inflight_variants.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/capture_reassigable_class_field.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/function_returns_function.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/mutation_after_class_init.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/redis.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/valid/while_loop_await.test.w_compile_tf-aws.md

fix(compiler): bundling error when using computed struct value inflight

---

docs/docs/04-standard-library/cloud/function.md
libs/wingsdk/src/cloud/function.md

docs: fix cloud.Function typo

---

apps/wing/src/cli.ts
apps/wing/src/commands/run.test.ts
apps/wing/src/commands/run.ts

feat(cli): adding platform to wing run command

---

tools/hangar/__snapshots__/test_corpus/valid/bring_wing_library.test.w_compile_tf-aws.md

fix snapshot which was missing in #5604

chore: fix snapshot which was missing in #5604

---

apps/wing-console/console/ui/src/layout/sign-in.tsx

chore(console): update sign in dialog message to be more informative

---

apps/wing/src/commands/test/__snapshots__/test.test.ts.snap
libs/wingsdk/src/util/enhanced-error.ts
libs/wingsdk/test/util/enhanced-error.test.ts
tools/hangar/__snapshots__/error.ts.snap
tools/hangar/__snapshots__/invalid.ts.snap
tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/signed_url.test.w_test_sim.md
tools/hangar/src/unsupported.test.ts

The term "runtime" can be confusing in the context of Wing because people might be thinking this is inflight.

chore: change "runtime error" to "error"

---

apps/wing-console/console/server/src/router/endpoint.ts

resolves: https://github.com/winglang/wing/issues/5505

fix(console): console seems to hang on compiler error

---

apps/wing-console/console/design-system/package.json
pnpm-lock.yaml

fix(console): missing dependency when importing console ui

---

libs/wingsdk/src/platform/parameter-registrar.ts

Fixes https://github.com/winglang/wing/issues/5650

chore: remove leftover log

---

apps/wing-console/console/ui/src/layout/sign-in.tsx

resolves: https://github.com/winglang/wing/issues/5654
https://github.com/winglang/wing/assets/2538825/7ee6dec1-545a-4de4-9676-29729bbada1f

fix(console): sign in to wing console has no loading indication

---

docs/docs/06-tools/02-wing-console.md

docs: broken link in the `Wing Console` section

---

apps/wing/project-templates/wing/private-api/main.w
apps/wing/project-templates/wing/private-api/package.json
apps/wing/project-templates/wing/private-api/wing.toml

Leaving in draft until: https://github.com/winglang/wing/pull/5659 merges

feat(cli): add private-api template

---

libs/@wingcloud/framework/test/internal.test.ts

Created https://github.com/winglang/wing/issues/5676 to track this terrible performance

chore: increase test timeout for typescript compiler

---

examples/tests/invalid/inference.test.w
examples/tests/valid/inference.test.w
libs/wingc/src/type_check/inference_visitor.rs
tools/hangar/__snapshots__/invalid.ts.snap
tools/hangar/__snapshots__/test_corpus/valid/inference.test.w_compile_tf-aws.md

fix(compiler): inference fails for optional function argument

---

examples/tests/sdk_tests/function/invoke.test.w
libs/wingsdk/src/shared-aws/function.inflight.ts
libs/wingsdk/src/target-tf-aws/function.ts

aws tests https://github.com/winglang/wing/actions/runs/7891384592
(passed running `wing test -f tf-aws` locally)

fix: invoke(nil) fails on aws for cloud.Function

---

docs/docs/02-concepts/03-platforms.md
libs/wingcompiler/src/compile.ts

check for default values file if one is not provided

fix(cli): no default values files is used

---

docs/docs/03-language-reference.md

docs: remove references to outdated issues in language reference

---

docs/docs/06-tools/01-cli.md

Add npm init step when using `awscdk` platform

chore(docs): update usage for awscdk platform

---

apps/wing/project-templates/typescript/private-api/main.ts
apps/wing/project-templates/typescript/private-api/package.json
apps/wing/project-templates/typescript/private-api/wing.toml
apps/wing/project-templates/wing/private-api/main.w
apps/wing/project-templates/wing/private-api/wing.toml

This pr:
- Adds more interesting example to private-api template
- Adds more comments about what the code does
- Adds typescript version

chore(cli): make private-api template more interesting

---

apps/jsii-docgen/turbo.json
examples/ts-fixture/turbo.json
package.json
pnpm-lock.yaml
tools/hangar/turbo.json
turbo.json

The newer version finally has improved output (stops mangling stuff, like weird spacing and missing colors)! Also looks like they have been adding fixes for the daemon, which I've personally been having issue with.

chore: update turbo to 1.12.4

---

docs/docs/08-guides/03-react-vite-websockets.md

fix(docs): vite guide fixes

---

docs/docs/08-guides/03-react-vite-websockets.md

chore(docs): vite guide bit and bites

---

docs/docs/08-guides/03-react-vite-websockets.md

chore(docs): vite guide small fix

---

.github/workflows/pull-request-lint.yml

Fixes #4650
Also updated the action and added a couple scopes

chore(repo): disable title checker for merge queue PRs

---

.github/workflows/build.yml
.github/workflows/close-stale.yml
.github/workflows/delete-console-preview.yml
.github/workflows/issue-backlogger.yml
.github/workflows/matrix-update.yml
.github/workflows/mutation.yml
.github/workflows/tf-aws-test.yml
docs/docs/08-guides/02-ci-cd.md

Went over all actions and checked their release notes. Intentially left out one update, updated the rest. More coarsely pinned certain deps. I look forward to pinning deps by `sha` when we get around to using renovatebot

chore(repo): update several github actions

---

docs/docs/08-guides/03-react-vite-websockets.md

This PR updates the React Vite WebSockets tutorial by correcting typos and enhancing punctuation for better readability and clarity.

fix(docs): correct typos and enhance punctuation in React Vite WebSockets tutorial

---

apps/wing-console/console/ui/src/ui/elk-map.tsx
apps/wing-console/console/ui/src/ui/zoom-pane.tsx

The previous behavior highlighted nodes when they were hovered, which created lots of visual noise when moving the mouse around. Now, nodes are highlighted when selected.
Also, nodes can be deselected when clicking the background of the map view.

feat(console): highlight nodes when they are selected instead of hovered

---

apps/wing-console/console/ui/package.json
apps/wing-console/console/ui/src/ui/edge-item.tsx
apps/wing-console/console/ui/src/ui/elk-map.tsx
apps/wing-console/console/ui/src/ui/zoom-pane.tsx
pnpm-lock.yaml

- Fade edges based on the selected node
- Fix node highlighting
- Add a background pattern

feat(console): improve map view

---

apps/wing-console/console/app/preview/Dockerfile

chore: disable sign in in console preview environment

---

apps/wing-console/console/ui/src/ui/edge-item.tsx

Edge color and stroke width has been adjusted for better visibility.

feat(console): update map edge strokes

---

apps/wing/project-templates/typescript/private-api/wing.toml
apps/wing/project-templates/wing/private-api/wing.toml
docs/docs/02-concepts/03-platforms.md

fix(docs): missing s in private_subnet_id wing.toml configuration

---

.github/workflows/new-pull-request-comment.yml

Changing the examples ownership from Sebastian to Hasan.

chore(repo): change examples ownership

---

apps/wing-console/console/ui/src/layout/websocket-state.tsx

fix(console): text color of the connection lost modal in dark mode

---

apps/wing-console/console/app/demo/main.w
apps/wing-console/console/server/src/router/app.ts
apps/wing-console/console/ui/src/ui/elk-map.tsx
apps/wing-console/console/ui/src/ui/resource-metadata.tsx

- Add support for `bring ui` components
- Fix map crashing when nodes with connections are hidden
Supersedes #4915.

feat(console): support `bring ui`

---

apps/wing/project-templates/wing/private-api/main.w

I made a few tweaks to this template for the Workshop on 3/6

chore(cli): update private-api template

---

apps/wing/project-templates/wing/private-api/main.w

I goofed up and forgot to change the CONSUMER-PUT to use post request when I updated API 😁 silly me

fix(cli): private-api template consumer-PUT doesnt work

---

apps/wing-console/console/server/src/router/app.ts

Sometimes, the Console would show relationships that don't make sense. This was due to inconsistent connection manipulation in the Console server.

fix(console): hide invalid, unrelated or duplicated node relationships

---

docs/docs/08-guides/03-react-vite-websockets.md

chore: tweaks to vite workshop

---

docs/docs/08-guides/03-react-vite-websockets.md

chore: another tweak to vite workshop

---

docs/docs/08-guides/03-react-vite-websockets.md

chore(docs): fix react vite workshop ui rendering issue

---

docs/docs/08-guides/03-react-vite-websockets.md

Missing link failed publishing...

chore: more tweaks to vite workshop

---

docs/docs/055-platforms/sim.md

chore: fix bad link in `sim` docs

---

docs/docs/08-guides/03-react-vite-websockets.md

chore(docs): align react vite workshop code samples

---

apps/wing/src/commands/init.ts

resolves: https://github.com/winglang/wing/issues/5912

fix(cli): failed to create a template

---

apps/wing-console/console/app/test/cloud.api/index.test.ts
apps/wing-console/console/app/test/cloud.bucket/index.test.ts
apps/wing-console/console/app/test/cloud.counter/index.test.ts
apps/wing-console/console/app/test/cloud.function/index.test.ts
apps/wing-console/console/app/test/cloud.queue/index.test.ts
apps/wing-console/console/app/test/cloud.topic/index.test.ts
apps/wing-console/console/app/test/cloud.website/index.test.ts
apps/wing-console/console/app/test/ex.dynamodb-table/index.test.ts
apps/wing-console/console/app/test/ex.redis/index.test.ts
apps/wing-console/console/app/test/ex.table/index.test.ts
apps/wing-console/console/app/test/health/health.test.ts
apps/wing-console/console/app/test/health/main.w
apps/wing-console/console/ui/src/layout/status-bar.tsx

Resolves https://github.com/winglang/wing/issues/5925

fix(console): add sanity test

---

apps/wing/src/commands/init.ts

resolves: https://github.com/winglang/wing/issues/5936

fix(cli): confusing template instructions in cli

---

apps/wing-console/console/server/src/utils/createRouter.ts
apps/wing-console/console/ui/src/layout/default-layout.tsx
apps/wing-console/console/ui/src/layout/layout-provider.tsx

Usage: `http://localhost:5174/?layout=6`

feat(console): add map layout

---

libs/wingsdk/src/shared/sandbox.ts

This specifically fixes usage with vscode's js debugger. It's a hack but until we have a more robust answer to debugging it's probably worthwhile.
It's worth noting that you can also directly use `--inspect`, but you have to do it with `--inspect=0` because each inflight will need its own port. However, now that we're using child processes, vscode's debugging is the only one I've gotten to attach correctly (because it inserts a `--require` hook to start the inspector instead)
Fixes #5863

fix: unable to debug wing inflights

---

examples/tests/sdk_tests/counter/initial.test.w
tools/hangar/__snapshots__/compatibility-spy.ts.snap

fixes https://github.com/winglang/wing/issues/5897

chore(sdk): add `counter.initial` to test

---

examples/tests/sdk_tests/api/get.test.w
examples/tests/sdk_tests/api/path_vars.test.w
tools/hangar/__snapshots__/test_corpus/sdk_tests/api/get.test.w_test_sim.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/api/path_vars.test.w_test_sim.md

chore: consolidate api sdk tests

---

docs/docs/08-guides/03-react-vite-websockets.md

Adding short explanation on how to create the react-vite project template

feat(docs): adding short explanation about the react-vite project template

---

docs/docs/055-platforms/awscdk.md

chore(docs): missing char on awscdk doc

---

libs/tree-sitter-wing/.gitattributes
libs/tree-sitter-wing/.gitignore
libs/tree-sitter-wing/src/grammar.json

Fixes #6043
Grammar updates aren't happening too frequently, so this hopefully shouldn't cause much trouble.

chore: commit grammar.json in tree-sitter-wing

---

docs/docs/07-examples/80-singletons.md

Temporary note in our docs to work around #6049

fix(docs): singleton - add workaround for #6049

---

apps/wing-console/console/server/src/utils/simulator.ts

Closes https://github.com/winglang/wing/issues/6068

feat(console)!: use `simulator.update()`

---

docs/docs/04-standard-library/aws/api-reference.md
examples/tests/sdk_tests/function/function-ref.test.w
libs/wingsdk/src/shared-aws/function.ts
libs/wingsdk/src/shared-aws/util.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/function/function-ref.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/function/function-ref.test.w_test_sim.md

Reference an existing lambda function with `aws.FunctionRef`

feat(sdk): `aws.FunctionRef`

---

apps/wing-console/console/server/src/utils/simulator.ts

Reintroduce #6069 after it was reverted by #6076 due to #6116 which was fixed by #6117.
(This reverts commit 0a5a27de3758cca14c719e6b5bef51696cfb5c68.)

feat(console)!: use simulator.update()

---

apps/wing-console/console/ui/src/ui/api-interaction.tsx

fix(console): api resource having multiple routes sharing the same name

---

apps/wing-console/console/design-system/src/theme-provider.tsx
apps/wing-console/console/ui/src/App.tsx

fix(console): theme mode is not load after a refresh

---

apps/wing-console/console/app/demo/main.w

If you click on one of the Wing Console previews that appears as a comment on pull requests, there is a compilation error in the file. This should fix it

chore: fix demo app for Wing Console previews

---

libs/wingtunnels/src/index.ts

fix: wing cloud endpoints url is incorrect 

---

libs/wingc/src/lsp/completions.rs
libs/wingc/src/lsp/snapshots/completions/struct_literal_empty_nospace.snap

fix(vscode): missing completions in empty implicit struct literal

---

docs/contributing/999-rfcs/2024-03-31-wing-secrets-cli.md

RFC for creating application secrets via the Wing CLI
Demo of POC
https://www.loom.com/share/967b0047ae834442a32226cc3794fb84

rfc: wing secrets through cli

---

libs/tree-sitter-wing/src/scanner.c
libs/wingc/src/lsp/completions.rs
libs/wingc/src/lsp/snapshots/completions/forin_before_return_type_ref.snap
libs/wingc/src/lsp/snapshots/completions/if_before_return_type_ref.snap

Fixes #6233
Fixes #6180
Primary goal was to fix the above completions issues, but all that was needed was to improve the parser so that the language server has better information to work with.
Before
After

fix: cascading parser errors from incomplete block statements (`if`/`for`/etc.)

---

docs/docs/04-standard-library/sim/api-reference.md
libs/wingsdk/src/target-sim/container.inflight.ts
libs/wingsdk/src/target-sim/container.ts
libs/wingsdk/src/target-sim/schema-resources.ts
libs/wingsdk/test/target-sim/container.test.ts
libs/wingsdk/test/target-sim/my-docker-image.volume/Dockerfile
libs/wingsdk/test/target-sim/my-docker-image.volume/index.js

Allows defining volume mount points for the container.

feat(sdk): add `volumes` prop to `sim.Container`

---

libs/wingsdk/src/shared-aws/bucket.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/bucket/bucket-ref.test.w_compile_tf-aws.md

feat: `BucketRef` file explorer

---

apps/wing-console/console/server/src/utils/terms-and-conditions.ts

Commit b7d87b788abe2064e9d454b4fe845e8a3a9a0902 introduced code that didn't correctly access the Console config file.

fix(console): config file is not correctly accessed

---

apps/wing-console/console/app/demo/main.w
apps/wing-console/console/ui/src/features/api-interaction-view.tsx
apps/wing-console/console/ui/src/ui/api-interaction.tsx
apps/wing-console/console/ui/src/ui/custom-resource-http-client.tsx

fix(console): tsoa ui http client is not maintaining state

---

examples/tests/sdk_tests/container/mount.test.w

Docker is only available on our Linux test runners (not our Mac or Windows test runners).

chore: fix test failure in CI

---

.github/ISSUE_TEMPLATE/example.yml

chore(repo): add "missing example" issue type

---

libs/wingsdk/src/shared-aws/secret.inflight.ts
libs/wingsdk/src/target-sim/secret.inflight.ts

chore(sdk): add hint to secret.inflight value() methods

---

apps/wing-console/console/app/demo/main.w
apps/wing-console/console/ui/src/ui/custom-resource-item.tsx
apps/wing-console/console/ui/src/ui/custom-resource-ui-field.tsx

feat(console): linkable `ui.Field`

---

docs/docs/04-standard-library/util/api-reference.md
examples/tests/sdk_tests/util/env.test.w
libs/wingc/src/lsp/snapshots/completions/util_static_methods.snap
libs/wingsdk/src/util/util.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/util/env.test.w_test_sim.md

Closes #6413 
- [] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [] Description explains motivation and solution
- [] Tests added (always)

feat(sdk): `util.setEnv`

---

tools/hangar/src/benchmarking/compare.ts

Changed to using a flat percentage instead of standard deviations because it just seems like it would work better (I am a terrible statistician)

chore: only post benchmark comment for interesting result and change threshold of interest

---

package.json
pnpm-lock.yaml

We're behind a whole minor version, looks like several nice improvements

chore: update turbo to 1.13.3

---

apps/wing-console/console/server/src/router/app.ts
apps/wing-console/console/ui/src/services/use-explorer.tsx

resolves: https://github.com/winglang/wing/issues/6439

fix(console): unintended behavior when selecting a resource in the map

---

docs/docs/04-standard-library/sim/container.md
docs/docs/04-standard-library/sim/state.md
libs/wingsdk/scripts/docgen.mts

chore: fix missing docs for sim APIs

---

apps/wing-console/console/app/test/cloud.website/index.test.ts
apps/wing-console/console/design-system/src/attribute.tsx
apps/wing-console/console/ui/src/features/redis-interaction-view.tsx
apps/wing-console/console/ui/src/features/unsupported-interaction-view.tsx
apps/wing-console/console/ui/src/features/website-interaction-view.tsx
apps/wing-console/console/ui/src/ui/unsupported-interaction.tsx
apps/wing-console/console/ui/src/ui/website-interaction.tsx

resolves: https://github.com/winglang/wing/issues/6227

fix(console): open link icon does not work

---

docs/contributing/999-rfcs/2024-05-07-intrinsics.md

Fixes an error (https://github.com/winglang/docsite/actions/runs/9086814825/job/24973332143?pr=898) "Expected corresponding JSX closing tag for <identifier>"

chore: fix docsite build error

---

apps/wing/src/commands/test/test.test.ts

fix(cli): fix flaky `--parallel` tests

---

.mergify.yml

Also removed some fields that aren't actually valid in the mergify config.

chore: ignore draft PRs with mergify

---

docs/docs/055-platforms/awscdk.md

* Remove the `output` from `cdk.json`
* Move environment variables to `.env`

chore(docs): tweaks to awscdk platform docs

---

apps/wing-console/console/ui/src/ui/api-interaction.tsx

Fixes https://github.com/winglang/wing/issues/6525

fix(console): api gateway ui loose the endpoint while editing body

---

apps/wing-console/console/server/src/index.ts

resolves https://github.com/winglang/wing/issues/5613

feat(console): clear test status after reloading app

---

docs/docs/04-standard-library/cloud/api.md
examples/tests/sdk_tests/api/env.test.w
libs/awscdk/src/api.ts
libs/wingc/src/lsp/snapshots/completions/incomplete_inflight_namespace.snap
libs/wingc/src/lsp/snapshots/completions/namespace_middle_dot.snap
libs/wingc/src/lsp/snapshots/completions/partial_type_reference_annotation.snap
libs/wingc/src/lsp/snapshots/completions/variable_type_annotation_namespace.snap
libs/wingsdk/src/cloud/api.ts
libs/wingsdk/src/target-tf-aws/api.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/api/env.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/api/env.test.w_test_sim.md

It's now possible to set function props such as env vars for api handlers

feat(sdk): support api props

---

apps/wing-console/console/ui/src/ui/endpoint-interaction.tsx
apps/wing-console/console/ui/src/ui/endpoint-tree.tsx

Came as feedback from @andmoredev.

fix(console): "enpoint" -> "endpoint"

---

apps/wing-console/console/design-system/src/notification.tsx
apps/wing-console/console/server/src/utils/createRouter.ts
apps/wing-console/console/ui/src/layout/default-layout.tsx
apps/wing-console/console/ui/src/layout/layout-provider.tsx
apps/wing-console/console/ui/src/ui/blue-screen-of-death.tsx

Resolves https://github.com/winglang/wing/issues/2235

feat(console): add a button to copy the error in the blue screen

---

apps/wing-console/console/ui/src/layout/default-layout.tsx
apps/wing-console/console/ui/src/ui/blue-screen-of-death.tsx

* Remove the title (we know it's an error...)
* Change the text from "Copy error" to just "Copy"

chore(console): tweaks to blue screen of death

---

docs/docs/04-standard-library/ex/react-app.md

chore(docs): revert delete leftover ex.react doc

---

apps/wing-console/console/design-system/src/resource-icon.tsx
apps/wing-console/console/design-system/src/utils/icon-utils.ts
apps/wing-console/console/server/src/consoleLogger.ts
apps/wing-console/console/server/src/router/app.ts
apps/wing-console/console/server/src/utils/constructTreeNodeMap.ts
apps/wing-console/console/ui/src/features/map-view.tsx
apps/wing-console/console/ui/src/services/use-explorer.tsx
apps/wing-console/console/ui/src/ui/edge-metadata.tsx
apps/wing-console/console/ui/src/ui/explorer.tsx
apps/wing-console/console/ui/src/ui/resource-metadata.tsx
libs/wingsdk/src/core/tree.ts
libs/wingsdk/src/std/node.ts

Resolves https://github.com/winglang/wing/issues/6587

feat(console): icon for custom resources

---

apps/wing/project-templates/wing/slack/main.w
apps/wing/project-templates/wing/slack/package.json

feat(cli): add slack template

---

apps/wing-console/console/ui/src/layout/discord-button.tsx
apps/wing-console/console/ui/src/layout/discord-icon.tsx
apps/wing-console/console/ui/src/layout/status-bar.tsx
apps/wing-console/console/ui/src/layout/theme-toggle.tsx

feat(console): add discord button to the status bar

---

apps/wing-console/console/ui/src/layout/discord-button.tsx

fix(console): discord invite url

---

apps/wing-console/console/app/test/describe.ts
apps/wing-console/console/app/test/login/login.test.ts
apps/wing-console/console/app/test/login/main.w
apps/wing-console/console/design-system/src/modal.tsx
apps/wing-console/console/ui/src/layout/sign-in.tsx

part of: https://github.com/winglang/wing/issues/6337

feat(console): add tests for console sign in

---

apps/wing-console/console/ui/src/services/use-map.ts

Fixes a visual bug introduced by #6602 where strange connections would show floating around the map.

fix(console): strange map connections

---

docs/contributing/999-rfcs/2023-06-12-language-spec.md

chore: update set literal syntax in language spec

---

docs/docs/02-concepts/00-cloud-oriented-programming.md

Copied this code locally, unless I'm mistaken (high chance at the moment 😅), this inflight code does not return anything?
Copying the code shows errors in the IDE.
From what I understand nothing is returned, so I removed the return type in the example.

fix(docs): queue consumer inflight handler not supposed to have a return type

---

.github/workflows/periodic-azure-clean.yml

chore: periodic azure clean

---

libs/wingsdk/src/cloud/secret.md

chore(docs): add the link for storing secrets

---

docs/docs/04-standard-library/sim/api-reference.md
docs/docs/04-standard-library/sim/container.md
examples/tests/sdk_tests/container/container.test.w
examples/tests/sdk_tests/container/entrypoint.test.w
examples/tests/sdk_tests/container/my-docker-image/index.js
examples/tests/sdk_tests/container/network.test.w
libs/wingsdk/src/target-sim/container.inflight.ts
libs/wingsdk/src/target-sim/container.ts
libs/wingsdk/src/target-sim/schema-resources.ts
tools/hangar/__snapshots__/test_corpus/sdk_tests/container/container.test.w_test_sim.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/container/entrypoint.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/container/entrypoint.test.w_test_sim.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/container/network.test.w_compile_tf-aws.md
tools/hangar/__snapshots__/test_corpus/sdk_tests/container/network.test.w_test_sim.md

feat(sdk): network and entrypoint options for `sim.Container`

---

examples/tests/sdk_tests/container/network.test.w
libs/wingsdk/src/target-sim/container.inflight.ts

fix(sdk): container port token is resolved as a number

---

apps/wing-console/console/ui/src/features/layout/default-layout.tsx
apps/wing-console/console/ui/src/features/logs-pane/console-logs-filters.tsx

feat(console): improve logs filters responsiveness

---

examples/tests/sdk_tests/resource/no-stop.test.w

Fixes https://github.com/winglang/wing/issues/6714

fix: resource no-stop test should not run in the cloud

---

apps/wing-console/console/ui/src/App.tsx
apps/wing-console/console/ui/src/features/layout/default-layout.tsx

The Console's error screen appears behind the logs due to an error introduced during a previous refactor.

fix(console): blue screen of death is hidden behind the logs

---

libs/wingsdk/.projen/deps.json
libs/wingsdk/.projenrc.ts
libs/wingsdk/package.json
libs/wingsdk/src/target-tf-azure/bucket.ts
pnpm-lock.yaml

try to see if bucket tests are now passing (passing locally after installation)

fix: update `@azure/storage-blob`

---

libs/wingsdk/.projen/deps.json
libs/wingsdk/.projenrc.ts
libs/wingsdk/package.json
libs/wingsdk/src/target-tf-azure/bucket.ts
pnpm-lock.yaml

for some reason it fails in main build (and passes in local and manual dispatch of the SDK spec tests action...)

fix: skip all azure bucket tests

---

libs/wingsdk/src/target-sim/counter.inflight.ts
libs/wingsdk/src/target-sim/resource.ts
libs/wingsdk/test/target-sim/__snapshots__/counter.test.ts.snap
libs/wingsdk/test/target-sim/__snapshots__/file-counter.test.ts.snap

Since this interface is an inflight interface, the compiler assumes they are all async and there's a discrepancy between types and runtime.

fix(sdk): inflight `IResourceContext` methods are not async

---

apps/wing/project-templates/wing/react-vite/backend/package.json
apps/wing/project-templates/wing/slack/package.json

fix: `wing new` template out of date

---

docs/docs/02-concepts/01-preflight-and-inflight.md

fix(docs): fix typo in preflight and inflight docs

---

.github/workflows/build.yml
.mergify.yml
docs/turbo.json
examples/tests/doc_examples/valid/01-preflight-and-inflight.md_example_10/main.w

We have several processes that rely on doc changes going through a build process. I think there is room to optimize for the happy path, but missing the build process is now too disruptive with the new example testing system.

chore: docs changes now go through build workflow

---

docs/docs/03-language-reference.md

One of the bullets referenced an outdated issue, and another was accidentally repeated.
- [ x Docs updated (only required for features)

chore: update language roadmap items for optionality

---

.github/ISSUE_TEMPLATE/feature.yml

chore(repo): fix excess newline in placeholder

---

apps/wing-console/console/design-system/src/tree-item.tsx
apps/wing-console/console/ui/src/features/endpoints-pane/endpoint-tree.tsx
apps/wing-console/console/ui/src/features/tests-pane/test-tree.tsx

Resolves https://github.com/winglang/wing/issues/6796

feat(console): improve endpoints UI

---

docs/docs/09-typescript/01-resources.md

Fixed incorrect link (see https://github.com/winglang/wing/pull/6819 for info).

chore(docs): fixed incorrect link

---

apps/wing-console/console/ui/src/features/logs-pane/console-logs.tsx

Resolves https://github.com/winglang/wing/issues/6754

feat(console): show full date for log entries

---

apps/wing-console/console/design-system/src/tree-item.tsx
apps/wing-console/console/ui/src/features/hierarchy-pane/hierarchy.tsx

fix(console): hierarchy label

---

libs/wingsdk/src/target-sim/schedule.inflight.ts

Needed for https://github.com/winglang/wing/issues/6552

fix(sdk): cron events not triggered on simulator

---

docs/docs/04-standard-library/cloud/website.md
libs/wingsdk/src/cloud/website.md

adding use case of passing variables from main.w to website. using the AddJson methode in website.

docs(docs): adding docs for passing variables to website resource

---

apps/vscode-wing/src/bin-helper.ts
tools/hangar/src/benchmarking/cli.bench.ts

fix(vscode): extension can't find wing cli

---

libs/wingsdk/src/core/class-factory.ts

Fixes a regression introduced by https://github.com/winglang/wing/pull/6099

chore: fix azure tests failing in CI

---

libs/wingsdk/src/target-tf-gcp/platform.ts

fix: fix tf-gcp compilation

---

apps/wing-console/console/design-system/package.json
apps/wing-console/console/design-system/src/headless/tree-item.tsx
pnpm-lock.yaml

This changeset animates tree view items when expanding and collapsing.

feat(console): animate tree view items when expanding and collapsing

---

apps/wing-console/console/design-system/src/text-highlight.tsx
apps/wing-console/console/ui/src/features/logs-pane/console-logs.tsx

Fixes an issue where collapsed logs were not properly truncated.

fix(console): collapsing logs

---

libs/tree-sitter-wing/grammar.js
libs/tree-sitter-wing/jsconfig.json
libs/tree-sitter-wing/src/grammar.json
libs/wingc/src/parser.rs

Breaking up one of the larger functions into some smaller pieces to make it a bit more manageable

chore: refactor parser.rs

---

apps/wing-console/console/design-system/src/link.tsx
apps/wing-console/console/ui/src/features/endpoints-pane/endpoint-tree-item.tsx
apps/wing-console/console/ui/src/features/inspector-pane/resource-panes/custom-resource-ui-field.tsx

Amend the style of anchor links so they are more consistent.

fix(console): anchor style inconsistency

---

apps/wing-console/packages/utilities/src/debounce.test.ts
apps/wing-console/packages/utilities/src/debounce.ts
apps/wing-console/packages/utilities/src/throttle.test.ts
apps/wing-console/packages/utilities/src/throttle.ts

Fix implementation of debounce and throttle utilities, including the addition of tests.

fix(console): test debounce and throttle utilities

---

docs/contributing/04-roadmap.md
libs/@wingcloud/framework/src/main.ts

chore: add project roadmap

---

.github/workflows/matrix-update.yml
.github/workflows/sdk-spec-test.yml

Follow up to [xxx](https://github.com/winglang/wing/pull/7032). Attempts to fix the error shown here (https://github.com/winglang/wing/actions/runs/10477002918/job/29019610865)
```
Error: Unable to download artifact(s): Artifact not found for name: out
```

chore: fix matrix-update.yml pipeline

---

.github/workflows/sdk-spec-test.yml

chore: fix typo in sdk-spec-test.yml pipeline

---

.github/ISSUE_TEMPLATE/example.yml

chore: update example issue template

---

packages/@winglang/wingc/src/generate_docs.rs
packages/@winglibs/testfixture/API.md
packages/winglang/fixtures/valid1/API.md

Related to https://github.com/winglang/wing/issues/7068

fix(docs): section headers are not valid markdown

---

package.json
pnpm-lock.yaml

chore: upgrade turbo to v2.1.1

---

packages/@winglang/wingc/src/lib.rs
packages/@winglang/wingc/src/lsp/snapshots/completions/bring_suggestions.snap
packages/@winglang/wingc/src/lsp/snapshots/completions/bring_suggestions_partial.snap
tests/invalid/bring.test.w
tools/hangar/__snapshots__/invalid.ts.snap

Fixes https://github.com/winglang/wing/issues/7089

fix(compiler): regex is not bringable module

---

docs/docs/08-guides/02-ci-cd.md

chore: fix ci/cd docs to use latest version of workflow

---

package.json

chore: update monorepo node version to 20.17.0

---

wing-console/packages/utilities/package.json

chore: pnpm turbo test hangs after success

---

wing-console/console/ui/package.json

chore: pnpm turbo test hangs after success (part 2)

---

docs/api/05-language-reference.md

Specification for https://github.com/winglang/wing/issues/7118
[View as rendered markdown (Section 1.14)](https://github.com/winglang/wing/blob/rybickic/bytes-spec/docs/api/05-language-reference.md#114-bytes-type)

feat: bytes type RFC

---

docs/examples/redis.md

My OCD made me do this while reading website

chore(examples): tiny typo fix

---

packages/@winglang/wingc/src/type_check.rs

chore(compiler): remove dead code

---

docs/examples/quick-share.md
packages/@winglang/sdk/src/std/index.ts

chore(docs): tweaks to the quickshare doc

---

packages/@winglang/platform-awscdk/src/bucket.ts
packages/@winglang/platform-awscdk/src/counter.ts
packages/@winglang/platform-awscdk/src/function.ts
packages/@winglang/sdk/src/shared-aws/commons.ts
packages/@winglang/sdk/src/shared-aws/counter.inflight.ts
packages/@winglang/sdk/src/shared-aws/counter.ts
packages/@winglang/sdk/src/target-tf-aws/counter.ts

I made two small corrections and a refactoring in this PR:
1. There was an error in an environment variable related to the bucket name that was passed in the aws-cdk build.
2. When updating the lambda function log, I assigned the new enum to the old variable, but I have now corrected it to the proper variable.
3. It didn't make sense to have a file just to keep a global variable related to the Counter, so I removed the file and moved the global variable to the shared-aws/counter.ts file.

fix(sdk): some fixes and minor refactoring

---

docs/contributing/01-start-here/05-development.md

feat(docs): add toolchain validation to contrib docs

---

docs/docs/01-start-here/05-aws.md

- Thumbs up icon not rendered
- Prefix `cloud-Queue-` fixed to `Queue-`

fix(docs): small typos
